//! First-launch trust provisioning.
//!
//! # What this is, and what it honestly claims
//!
//! BroPS is a single-user desktop application. The owner installs it and everything
//! must already be done: no ceremony, no USB, no key to carry, no annual renewal,
//! nothing to run by hand, ever. So the trust material the engine's governance chain
//! requires — an operator-root keypair, the six other authority keypairs, the
//! operator-signed `trusted-key-registry`, the out-of-registry operator-root pin, and
//! the operator-signed artifacts the residual engine items name — is **minted on the
//! user's own machine, on first launch, by this module**.
//!
//! ## The posture, stated plainly (read this before trusting anything below)
//!
//! Trust material minted on the user's machine at install time protects against an
//! attacker who arrives **later**. It does **not** protect against one who already
//! owns the machine at install time — that attacker witnesses the mint, or performs
//! it. This is the normal, honest posture for locally-minted trust material: an SSH
//! host key works exactly the same way, and so does a TLS private key generated by an
//! installer. Everything downstream inherits that boundary:
//!
//! * The operator-root **private** key lives on the same disk as the process that
//!   uses it, under the same user account. `engine/runtime/bro_signature.py` calls
//!   this out by name — an anchor its reader can rewrite is not an anchor — and
//!   refuses such a pin unless the deployment sets
//!   `BRO_OPERATOR_ROOT_PIN_SELF_OWNED=acknowledged`. This deployment genuinely has
//!   no second principal to offer, so that is what it must set, which does not make
//!   the anchor stronger: it makes the weakness explicit and reportable instead of
//!   silent.
//! * Consequently the chain proves **integrity over time on one machine** (nothing was
//!   swapped after install; a registry cannot be replayed below its floor; a builder
//!   key cannot sign a verifier receipt), not **provenance from a vendor**. No claim
//!   of the second kind may be made on the strength of this module.
//!
//! `POSTURE.txt`, written beside the trust store, says the same thing to whoever finds
//! the directory without this source in front of them.
//!
//! # Properties
//!
//! * **Idempotent.** A second launch VERIFIES what is on disk and returns; it never
//!   re-mints over a working install. See [`verify_existing`].
//! * **Never half-provisioned.** The mint happens in a staging directory that is
//!   renamed into place as the last step. A failure anywhere removes the staging
//!   directory and returns an error naming what failed; a rename that loses a race
//!   against a concurrent instance falls back to verification.
//! * **Byte-compatible with the Python verifier.** Every signature is Ed25519 over
//!   [`canonical::canonical_bytes`], which reproduces `bro_signature.canonical_bytes`
//!   exactly. Proven by `tests/python_verifier.rs`, which runs the REAL
//!   `bro_signature` / `bro_deploy_preflight` against the REAL output of this module.
//! * **Cross-platform**, with the platform difference reported rather than skipped:
//!   see [`Protection`].

pub mod anchor;

pub mod canonical;

/// The Windows **second principal** for the audit-head anchor (O-2).
///
/// Additive and self-contained: nothing in this module runs unless a caller asks for it,
/// and the POSIX provisioning path above is untouched. See the module docs for the design,
/// the rejected alternatives, and the exact elevation the installer needs.
pub mod audit_signer;

use std::collections::BTreeMap;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use canonical::{canonical_bytes, NonCanonical};
use ed25519_dalek::{Signature, Signer, SigningKey, Verifier, VerifyingKey};
use serde_json::{json, Map, Value};
use sha2::{Digest, Sha256};

// ---------------------------------------------------------------------------
// The engine's tables, mirrored — and drift-tested against the real ones
// ---------------------------------------------------------------------------

/// Every authority this module MINTS a keypair for: `bro_signature.AUTHORITY_TYPES`
/// minus `audit-anchor`.
///
/// `audit-anchor` is absent because its private half must never exist in a process that
/// can write the audit ledger — the signer service mints its own seed and publishes only
/// the public half ([`audit_signer`]).
///
/// **Minted is not retained.** `operator-root` is in this list and NOT in
/// [`RETAINED_AUTHORITIES`]: it is generated in memory, signs the registry and the
/// conductor session, and is destroyed before [`mint`] returns. See
/// [`RETAINED_AUTHORITIES`] for why.
///
/// This is a mirror of a Python constant, so it can drift. It does not drift silently:
/// `tests/verify_provisioning.py` imports the REAL `bro_signature` and fails if the set
/// of authorities in the minted registry is not exactly `AUTHORITY_TYPES` minus the
/// anchor, or if any key's `allowed_artifact_types` is not exactly what the REAL
/// `ARTIFACT_AUTHORITY` binds to that authority.
pub const MINTED_AUTHORITIES: [&str; 9] = [
    "builder",
    "control-room",
    "evidence-floor",
    "evidence-recorder",
    "issuer",
    "operator-root",
    "recovery",
    "release",
    "verifier",
];

/// The authorities whose PRIVATE half survives provisioning — everything in
/// [`MINTED_AUTHORITIES`] except `operator-root`.
///
/// # Why the root does not survive
///
/// The record of what happened must not be forgeable by the thing being recorded.
/// `bro_audit_log.verify_signed_payload` resolves an anchor's `key_id` through
/// `bro_signature.load_trusted_keys`, i.e. through the trusted-key registry — and the
/// registry is signed by `operator-root`. While this module left that private half in
/// `<app_data>/trust/keys/`, the app could mint an `audit-anchor` keypair of its own,
/// admit it to the registry, re-sign the registry, raise the anti-rollback floor it also
/// owns, and sign whatever head it liked. Narrowing `ANCHOR_AUTHORITIES` did not reach
/// that; nothing downstream can, because the registry's signer WAS the ledger's writer.
///
/// So the root is generated inside [`mint`], used for the two things only it may sign,
/// and destroyed. What the app legitimately needs afterwards was moved off it:
/// `control-room-command` (O-4) and `evidence-floor-anchor` (O-5) are bound to the
/// delegated `control-room` and `evidence-floor` authorities in
/// `bro_signature.ARTIFACT_AUTHORITY`, and those keys ARE retained. They may be: a
/// machine that is compromised can authorise its own control-room command and state its
/// own evidence high-water mark anyway. Neither can sign a `trusted-key-registry`, a
/// `conductor-session` or an `audit-head`, and the engine refuses each by name.
///
/// # What this does NOT close
///
/// The operator-root PIN (`pin/operator-root.pub`) and the anti-rollback floor still live
/// in the app's own data directory under `BRO_OPERATOR_ROOT_PIN_SELF_OWNED=acknowledged`.
/// An account that can rewrite the pin can install a trust root of its own and re-sign
/// everything under it, with no need for the destroyed key at all. That route is proved
/// open, by running it, in `audit-signer/tests/anchor_end_to_end.py`
/// (`case_pin_rewrite`). Destroying the root removes the KEY; it does not move the
/// ANCHOR out of the app's reach, and only a second principal can do that.
pub const RETAINED_AUTHORITIES: [&str; 8] = [
    "builder",
    "control-room",
    "evidence-floor",
    "evidence-recorder",
    "issuer",
    "recovery",
    "release",
    "verifier",
];

/// `bro_signature.ARTIFACT_AUTHORITY` — artifact type -> the authority that may sign it.
pub const ARTIFACT_AUTHORITY: [(&str, &str); 17] = [
    ("agent-profile", "issuer"),
    ("completion-manifest", "builder"),
    ("conductor-session", "operator-root"),
    ("control-room-command", "control-room"),
    ("evidence-event", "evidence-recorder"),
    ("evidence-floor-anchor", "evidence-floor"),
    ("evidence-head", "evidence-recorder"),
    ("execution-lease", "issuer"),
    ("mode-grant", "issuer"),
    ("protected-authority", "operator-root"),
    ("recovery-proof", "recovery"),
    ("recovery-record", "issuer"),
    ("release-grant", "release"),
    ("task-contract", "issuer"),
    ("trusted-key-registry", "operator-root"),
    ("verifier-receipt", "verifier"),
    ("workspace-binding", "operator-root"),
];

pub const OPERATOR: &str = "operator-root";
pub const BUILDER: &str = "builder";
pub const VERIFIER: &str = "verifier";
/// O-4's delegated authority: signs `control-room-command` and nothing else.
pub const CONTROL_ROOM: &str = "control-room";
/// O-5's delegated authority: signs `evidence-floor-anchor` and nothing else.
pub const EVIDENCE_FLOOR: &str = "evidence-floor";

/// `engine/runtime/bro_policy.py`: `CANONICAL_CONDUCTOR_ID` / `CONDUCTOR_ROLE`.
pub const CONDUCTOR_AGENT_ID: &str = "bro-000";
pub const CONDUCTOR_ROLE: &str = "bro";

/// The agent identity the builder key speaks for.
///
/// `bro_completion._require_signer_identity` refuses a builder/verifier signature
/// whose key carries no `subject_agent_id`, and `bro_deploy_preflight.check_registry`
/// makes an unbound builder/verifier key a RED deployment posture. The two must differ
/// or "builder != verifier" becomes a string comparison one key satisfies on both
/// sides. The form is the one every engine schema requires: `^agt-p[0-9]{2,}-r[0-9]{2,}$`.
pub const BUILDER_AGENT_ID: &str = "agt-p01-r01";
pub const VERIFIER_AGENT_ID: &str = "agt-p01-r02";

// ---------------------------------------------------------------------------
// Expiry
// ---------------------------------------------------------------------------

/// The `not_after_epoch` / `expires_at_epoch` every key and artifact this module mints
/// carries: 9999-12-31T23:59:59Z.
///
/// **The decision.** `broctl`'s `DEFAULT_VALIDITY_SECONDS` is one year, which is right
/// for a fleet whose operator re-signs a registry on a schedule and wrong here: this
/// product has no operator other than the person who installed it, and a desktop app
/// that stops working after a year until its owner "renews" something is exactly the
/// ceremony this design forbids. So validity is unbounded in the only way the schema
/// allows — `not_after_epoch` must be an int, so it is set to a date no clock reaches.
///
/// **What it costs.** Expiry can never be the mechanism that retires a compromised
/// key. Retirement has to come from re-minting the registry with that key marked
/// `revoked` and raising [`REGISTRY_VERSION`], which the anti-rollback floor
/// (`BRO_OPERATOR_REGISTRY_MIN_FILE`, written by this module) then makes stick — a
/// superseded but still operator-signed registry replayed from a backup is refused.
/// On a machine whose owner is the attacker, both the re-mint and the floor are
/// rewritable, which is the boundary stated at the top of this module and not a
/// property a one-year expiry would have restored.
pub const NEVER_EXPIRES_EPOCH: i64 = 253_402_300_799;

/// `not_before_epoch` for every minted key: the epoch.
///
/// Not "now". `verify_artifact` refuses a key whose `not_before_epoch` is in the
/// future, so stamping the install moment turns any backwards clock correction — a
/// machine that was ahead at install and got fixed by NTP an hour later — into a
/// governance chain that refuses everything until the clock catches up, with nothing
/// the user could do about it. A start-of-validity bound buys nothing here anyway:
/// the registry that introduces the key is itself the moment the key becomes real.
pub const NOT_BEFORE_EPOCH: i64 = 0;

/// The version stamped into the registry payload and written to the anti-rollback
/// floor file. A re-mint (revocation, added authority) must raise both together.
pub const REGISTRY_VERSION: i64 = 1;

// ---------------------------------------------------------------------------
// Layout
// ---------------------------------------------------------------------------

/// The app-side half of the store lives under `<app_data_dir>/trust`: the private keys, the
/// trusted-key registry and the operator-signed artifacts. The app's account writes all of it,
/// which is why none of it is the anchor — see [`anchor`].
pub const TRUST_DIR: &str = "trust";
/// The record of what was minted; its presence is what makes provisioning idempotent.
///
/// It lives in the ANCHOR directory, not here, and it is re-exported from [`anchor`] so there
/// is one spelling. The manifest carries the sha256 of every app-side file, so it is the thing
/// that makes the app-side store unforgeable — which it can only be if the app cannot rewrite
/// it, and that is exactly what its location buys.
pub use anchor::MANIFEST_FILE;
/// The posture statement, for whoever finds this directory without the source.
pub const POSTURE_FILE: &str = "POSTURE.txt";
/// Private key material, one file per authority.
pub const KEYS_DIR: &str = "keys";
/// The registry ROOT: `bro_signature.load_trusted_keys` reads `<root>/config/trusted-keys.json`.
///
/// **It lives in the ANCHOR directory too**, and it has to. `bro_signature.resolve_registry_root`
/// runs `_refuse_writable_registry_root` on whatever `BRO_TRUSTED_REGISTRY_ROOT` names, which is
/// the same `bro_custody` question the pin asks, asked with the DIRECTORY right list — so a
/// registry root the reading account can add to or delete from is refused outright. That refusal
/// was invisible for as long as this deployment set `BRO_OPERATOR_ROOT_PIN_SELF_OWNED`, because
/// the acknowledgement short-circuits every custody rule in the runtime at once, not just the
/// pin's. Dropping the acknowledgement surfaced it immediately.
///
/// The engine states what it buys and it is smaller than it looks: the registry is
/// operator-signed and pinned, so an account that can write this directory cannot introduce a
/// key. What it can do is swap in a different registry the same operator signed, or delete it.
/// That is a downgrade and a denial rather than a forgery, and it is what the rule is for.
///
/// It sits BESIDE the pin, never above it: `_refuse_anchor_inside_registry_root` refuses a pin
/// lexically inside the registry root it anchors, because a root-controlled path must not be
/// able to select its own anchor. `<anchor>/registry` and `<anchor>/operator-root.pub` are
/// siblings, which is the same relationship `pin/` and `registry/` had inside the trust store.
pub const REGISTRY_ROOT_DIR: &str = "registry";
/// Relative to the registry root. `bro_signature.REGISTRY_REL`.
pub const REGISTRY_REL: &str = "config/trusted-keys.json";
/// The out-of-registry pins. Deliberately a SIBLING of the registry root, never inside
/// it: `bro_signature._pin_from_file` refuses a pin lexically inside the root it
/// anchors, because a root-controlled path must not be able to select its own anchor.
///
/// **They no longer live in this directory at all.** The pin and the floor were files in
/// `<app_data>/trust/pin/`, which the app's own account owns; an account that can rewrite the
/// pin installs a trust root of its own and re-signs everything under it, with no need for any
/// private key. They moved to [`anchor`], a location the app's account cannot write, and that
/// move is the whole of O-2. The names are re-exported so there is one spelling.
pub use anchor::{OPERATOR_PIN_FILE, REGISTRY_FLOOR_FILE};
/// Operator-signed artifacts.
pub const ARTIFACTS_DIR: &str = "artifacts";
pub const CONDUCTOR_SESSION_FILE: &str = "conductor-session.json";

pub const SCHEMA: i64 = 1;

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

#[derive(Debug)]
pub enum ProvisionError {
    Io { what: String, path: PathBuf, source: std::io::Error },
    Canonical(NonCanonical),
    /// The trust store on disk is present but does not verify. Never repaired and
    /// never re-minted over: a store that fails verification is either damaged or
    /// tampered with, and silently replacing it destroys the evidence of which.
    Corrupt { what: String, detail: String },
    /// This platform cannot do something the posture requires. Fails closed.
    Unsupported { platform: String, what: String },
    /// The trust anchor is not held where the policed account cannot write it — the one
    /// property O-2 reduces to. Raised by [`anchor::prove_unwritable`] with the path, the
    /// measurement that failed, and what a deployment has to change.
    ///
    /// Never softened into a warning and never given a fallback: a deployment that cannot
    /// provide the location has no trust anchor, and continuing without one would mean the
    /// application choosing its own trust root while reporting that it had one.
    Custody { path: PathBuf, what: String, remedy: String },
}

impl std::fmt::Display for ProvisionError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ProvisionError::Io { what, path, source } => {
                write!(f, "trust provisioning failed while {what} ({}): {source}", path.display())
            }
            ProvisionError::Canonical(e) => write!(f, "trust provisioning failed: {e}"),
            ProvisionError::Corrupt { what, detail } => write!(
                f,
                "the provisioned trust store is not usable — {what}: {detail}. Nothing was \
                 changed or deleted. Move or remove the `trust` directory in the application \
                 data directory to have it re-minted from scratch."
            ),
            ProvisionError::Unsupported { platform, what } => {
                write!(f, "trust provisioning refuses to continue on {platform}: {what}")
            }
            ProvisionError::Custody { path, what, remedy } => write!(
                f,
                "the trust anchor at {} is not out of this account's reach — {what}. {remedy}",
                path.display()
            ),
        }
    }
}

impl std::error::Error for ProvisionError {}

impl From<NonCanonical> for ProvisionError {
    fn from(e: NonCanonical) -> Self {
        ProvisionError::Canonical(e)
    }
}

fn io<T>(r: std::io::Result<T>, what: &str, path: &Path) -> Result<T, ProvisionError> {
    r.map_err(|source| ProvisionError::Io {
        what: what.to_string(),
        path: path.to_path_buf(),
        source,
    })
}

fn corrupt<T>(what: &str, detail: impl Into<String>) -> Result<T, ProvisionError> {
    Err(ProvisionError::Corrupt { what: what.to_string(), detail: detail.into() })
}

// ---------------------------------------------------------------------------
// Permissions — the existing per-OS routines, and what they honestly do
// ---------------------------------------------------------------------------

/// What was actually done to restrict access, per platform. Reported rather than
/// assumed, because the honest answer differs by platform and a caller that printed
/// "owner only" everywhere would be making a claim this code cannot support off unix.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Protection {
    /// POSIX: an explicit `chmod` to the stated mode.
    PosixMode(u32),
    /// Everywhere else: whatever the containing directory grants. On Windows the app
    /// data directory is per-user by default ACL, so key material is not world
    /// readable — but no explicit ACL was applied by this process, and this value says
    /// so instead of implying one was.
    InheritedFromParent { platform: &'static str },
}

impl std::fmt::Display for Protection {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Protection::PosixMode(m) => write!(f, "posix: chmod {m:04o} applied by this process"),
            Protection::InheritedFromParent { platform } => write!(
                f,
                "{platform}: NO explicit permission was applied by this process — \
                 `secure_data_dir`/`secure_owner_only_file` have no non-unix branch, so key \
                 material carries the access control the application data directory grants it \
                 (per-user by default on Windows, plus SYSTEM and Administrators)"
            ),
        }
    }
}

/// Restrict a directory to the owner (0700).
///
/// This is the routine `apps/desktop/src-tauri/src/lib.rs` has always called before
/// opening the database; it lives here so there is exactly one copy and both the host
/// and the provisioner use it.
#[cfg(unix)]
pub fn secure_data_dir(dir: &Path) -> std::io::Result<()> {
    use std::os::unix::fs::PermissionsExt;
    std::fs::set_permissions(dir, std::fs::Permissions::from_mode(0o700))
}
#[cfg(not(unix))]
pub fn secure_data_dir(_dir: &Path) -> std::io::Result<()> {
    Ok(())
}

/// Restrict a single file to the owner (0600). Same per-OS shape as
/// [`secure_data_dir`]; the host's `secure_db_files` calls this too, so the database
/// sidecars and the private keys are restricted by one implementation.
#[cfg(unix)]
pub fn secure_owner_only_file(path: &Path) -> std::io::Result<()> {
    use std::os::unix::fs::PermissionsExt;
    std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o600))
}
#[cfg(not(unix))]
pub fn secure_owner_only_file(_path: &Path) -> std::io::Result<()> {
    Ok(())
}

pub fn directory_protection() -> Protection {
    if cfg!(unix) {
        Protection::PosixMode(0o700)
    } else {
        Protection::InheritedFromParent { platform: platform_name() }
    }
}

pub fn key_file_protection() -> Protection {
    if cfg!(unix) {
        Protection::PosixMode(0o600)
    } else {
        Protection::InheritedFromParent { platform: platform_name() }
    }
}

pub fn platform_name() -> &'static str {
    if cfg!(target_os = "windows") {
        "windows"
    } else if cfg!(target_os = "macos") {
        "macos"
    } else if cfg!(target_os = "linux") {
        "linux"
    } else if cfg!(unix) {
        "unix"
    } else {
        "unknown"
    }
}

// ---------------------------------------------------------------------------
// Small helpers
// ---------------------------------------------------------------------------

pub fn hex(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push(char::from_digit((b >> 4) as u32, 16).unwrap());
        s.push(char::from_digit((b & 0x0f) as u32, 16).unwrap());
    }
    s
}

pub fn unhex(s: &str) -> Option<Vec<u8>> {
    if s.len() % 2 != 0 {
        return None;
    }
    let mut out = Vec::with_capacity(s.len() / 2);
    for pair in s.as_bytes().chunks(2) {
        let hi = (pair[0] as char).to_digit(16)?;
        let lo = (pair[1] as char).to_digit(16)?;
        out.push((hi * 16 + lo) as u8);
    }
    Some(out)
}

pub fn sha256_hex(bytes: &[u8]) -> String {
    hex(&Sha256::digest(bytes))
}

fn now_epoch() -> i64 {
    SystemTime::now().duration_since(UNIX_EPOCH).map(|d| d.as_secs() as i64).unwrap_or(0)
}

fn random_hex(bytes: usize) -> Result<String, ProvisionError> {
    let mut buf = vec![0u8; bytes];
    getrandom::getrandom(&mut buf).map_err(|e| ProvisionError::Unsupported {
        platform: platform_name().to_string(),
        what: format!("the OS CSPRNG is unavailable, so no key material can be minted: {e}"),
    })?;
    Ok(hex(&buf))
}

/// 32 raw CSPRNG bytes for a seed, on the caller's own stack.
///
/// Deliberately NOT `random_hex` + `unhex`. That route put the seed through a heap
/// `String` and a heap `Vec`, neither of which anything owned by this module could
/// afterwards overwrite — for a key that is meant to be destroyed, every extra copy is a
/// copy the destruction does not reach. This returns the array, which the caller wipes.
fn random_seed() -> Result<[u8; 32], ProvisionError> {
    let mut seed = [0u8; 32];
    getrandom::getrandom(&mut seed).map_err(|e| ProvisionError::Unsupported {
        platform: platform_name().to_string(),
        what: format!("the OS CSPRNG is unavailable, so no key material can be minted: {e}"),
    })?;
    Ok(seed)
}

/// Overwrite a seed buffer, through a write the optimiser may not elide.
///
/// `ed25519_dalek::SigningKey` is `ZeroizeOnDrop` (the `zeroize` feature is on by
/// default in 2.x, and `Drop` calls `secret_key.zeroize()`), so the copy inside the key
/// is handled. This is for the array the seed arrived in, which dalek copies out of.
fn wipe(seed: &mut [u8; 32]) {
    for byte in seed.iter_mut() {
        // `write_volatile` is what stops a "this store is never read" pass from removing
        // the loop entirely; a plain `*byte = 0` on a local about to go out of scope is
        // exactly the store LLVM is allowed to drop.
        unsafe { std::ptr::write_volatile(byte, 0) };
    }
}

/// Every artifact type the engine binds to `authority`, sorted — the same set
/// `broctl._artifacts_for` computes from `ARTIFACT_AUTHORITY`.
pub fn artifacts_for(authority: &str) -> Vec<String> {
    let mut v: Vec<String> = ARTIFACT_AUTHORITY
        .iter()
        .filter(|(_, a)| *a == authority)
        .map(|(t, _)| t.to_string())
        .collect();
    v.sort();
    v
}

fn subject_agent_id(authority: &str) -> Option<&'static str> {
    match authority {
        BUILDER => Some(BUILDER_AGENT_ID),
        VERIFIER => Some(VERIFIER_AGENT_ID),
        _ => None,
    }
}

// ---------------------------------------------------------------------------
// Signing
// ---------------------------------------------------------------------------

/// Sign `payload` and wrap it as the `{payload, signature}` document every
/// `bro_signature` verifier accepts. The signature is Ed25519 over
/// [`canonical_bytes`] of the payload, hex-encoded exactly as `broctl.sign_payload`
/// writes it (`private.sign(canonical_bytes(payload)).hex()`).
pub fn sign_document(key: &SigningKey, payload: Value) -> Result<Value, ProvisionError> {
    let bytes = canonical_bytes(&payload)?;
    let signature = key.sign(&bytes);
    Ok(json!({"payload": payload, "signature": hex(&signature.to_bytes())}))
}

/// The Rust half of `bro_signature.verify_detached`, used only to re-check this
/// module's own output on a later launch.
fn verify_document(document: &Value, public_key_hex: &str) -> Result<Value, ProvisionError> {
    let payload = match document.get("payload") {
        Some(p) => p.clone(),
        None => return corrupt("a signed document has no payload", "missing `payload`"),
    };
    let sig_hex = match document.get("signature").and_then(|s| s.as_str()) {
        Some(s) => s,
        None => return corrupt("a signed document has no signature", "missing `signature`"),
    };
    let raw_key: [u8; 32] = match unhex(public_key_hex).map(<[u8; 32]>::try_from) {
        Some(Ok(k)) => k,
        _ => {
            return corrupt(
                "the operator-root public key is unusable",
                format!("expected 64 hex characters, got {public_key_hex:?}"),
            )
        }
    };
    let vk = match VerifyingKey::from_bytes(&raw_key) {
        Ok(k) => k,
        Err(e) => return corrupt("the operator-root public key is unusable", e.to_string()),
    };
    let raw_sig: [u8; 64] = match unhex(sig_hex).map(<[u8; 64]>::try_from) {
        Some(Ok(s)) => s,
        _ => {
            return corrupt(
                "a signature is malformed",
                format!("expected 128 hex characters, got {} characters", sig_hex.len()),
            )
        }
    };
    let sig = Signature::from_bytes(&raw_sig);
    let bytes = canonical_bytes(&payload)?;
    match vk.verify(&bytes, &sig) {
        Ok(()) => Ok(payload),
        Err(e) => {
            corrupt("a signature does not verify against the operator-root pin", e.to_string())
        }
    }
}

// ---------------------------------------------------------------------------
// Key material
// ---------------------------------------------------------------------------

/// One authority's keypair, in the on-disk form `broctl sign --key` also reads
/// (`private_key` is the raw 32-byte Ed25519 seed as hex — the same bytes
/// `Ed25519PrivateKey.private_bytes_raw()` produces on the Python side).
pub struct AuthorityKey {
    pub authority_type: String,
    pub key_id: String,
    pub signing: SigningKey,
}

impl AuthorityKey {
    pub fn public_key_hex(&self) -> String {
        hex(self.signing.verifying_key().as_bytes())
    }

    fn to_json(&self) -> Value {
        let mut value = json!({
            "key_id": self.key_id,
            "authority_type": self.authority_type,
            "private_key": hex(self.signing.as_bytes()),
            "public_key": self.public_key_hex(),
            "production": true,
            "provenance": "minted on this machine at first launch; see POSTURE.txt",
        });
        if let Some(subject) = subject_agent_id(&self.authority_type) {
            value.as_object_mut().unwrap().insert("subject_agent_id".into(), json!(subject));
        }
        value
    }
}

fn mint_key(authority: &str, install_id: &str) -> Result<AuthorityKey, ProvisionError> {
    let mut seed = random_seed()?;
    let key = AuthorityKey {
        authority_type: authority.to_string(),
        key_id: format!("brops-{install_id}-{authority}"),
        signing: SigningKey::from_bytes(&seed),
    };
    wipe(&mut seed);
    Ok(key)
}

// ---------------------------------------------------------------------------
// The registry
// ---------------------------------------------------------------------------

/// The audit signer's PUBLISHED identity: a key id and a public half, and nothing else.
///
/// Parsed out of the custody record the signer service writes into its own protected
/// directory. The fields it does not read are the point — this type cannot carry a seed,
/// so a custody record that leaked one could not smuggle it into the registry through
/// here (and `brops_audit_signer::custody::read_custody` refuses such a record outright
/// on the reading side).
pub struct AnchorKey {
    pub key_id: String,
    pub public_key: String,
}

impl AnchorKey {
    /// Read `{key_id, public_key, authority}` out of a published custody record.
    ///
    /// The `authority` field must say `audit-anchor`. Registering a key under an
    /// authority its own publisher never claimed would be this module choosing what the
    /// signer's key is for, which is exactly the decision it must not make.
    pub fn from_custody(record: &Value) -> Result<AnchorKey, ProvisionError> {
        let key_id = match record.get("key_id").and_then(Value::as_str) {
            Some(s) if !s.is_empty() => s.to_string(),
            _ => return corrupt("the audit signer's custody record has no key_id", "missing"),
        };
        let public_key = match record.get("public_key").and_then(Value::as_str) {
            Some(s) => s.to_string(),
            None => {
                return corrupt("the audit signer's custody record has no public_key", "missing")
            }
        };
        if public_key.len() != 64 || !public_key.bytes().all(|b| b.is_ascii_hexdigit()) {
            return corrupt(
                "the audit signer's custody record does not carry a 32-byte Ed25519 public key",
                format!("got {} characters", public_key.len()),
            );
        }
        if record.get("authority").and_then(Value::as_str) != Some(audit_signer::ANCHOR_AUTHORITY)
        {
            return corrupt(
                "the audit signer's custody record does not claim the audit-anchor authority",
                format!(
                    "registering it would grant the key an authority its own publisher never \
                     claimed (got {:?})",
                    record.get("authority")
                ),
            );
        }
        if record.get("private_key").is_some() || record.get("seed").is_some() {
            return corrupt(
                "the audit signer's custody record carries secret material",
                "a published record must contain the public half only; a record with a seed in \
                 it means the signer's private half has already escaped its own account",
            );
        }
        Ok(AnchorKey { key_id, public_key })
    }
}

/// One registry entry, in the shape `bro_signature._parse_key` demands.
fn registry_entry(
    key_id: &str,
    public_key: &str,
    authority: &str,
    issued_by: &str,
    provenance: Option<&str>,
) -> Value {
    let mut entry = Map::new();
    entry.insert("key_id".into(), json!(key_id));
    entry.insert("public_key".into(), json!(public_key));
    entry.insert("authority_type".into(), json!(authority));
    // For `audit-anchor` this is deliberately EMPTY and must be: the authority binds no
    // registry artifact type, so `_parse_key` refuses any grant given to it — including
    // `audit-head` itself, which is out-of-registry. Its whole power is the hardcoded
    // `bro_audit_log.ANCHOR_AUTHORITIES` comparison, which is why writing the registry
    // cannot widen what the key is for.
    entry.insert("allowed_artifact_types".into(), json!(artifacts_for(authority)));
    entry.insert("not_before_epoch".into(), json!(NOT_BEFORE_EPOCH));
    entry.insert("not_after_epoch".into(), json!(NEVER_EXPIRES_EPOCH));
    entry.insert("status".into(), json!("active"));
    entry.insert("issued_by".into(), json!(issued_by));
    if let Some(subject) = subject_agent_id(authority) {
        entry.insert("subject_agent_id".into(), json!(subject));
    }
    if let Some(note) = provenance {
        entry.insert("provenance".into(), json!(note));
    }
    Value::Object(entry)
}

fn registry_payload(
    keys: &[AuthorityKey],
    operator: &AuthorityKey,
    anchor: Option<&AnchorKey>,
    now: i64,
) -> Value {
    let mut entries: Vec<Value> = keys
        .iter()
        .map(|key| {
            registry_entry(
                &key.key_id,
                &key.public_key_hex(),
                &key.authority_type,
                &operator.key_id,
                None,
            )
        })
        .collect();
    // The operator's own entry — its PUBLIC half. `load_trusted_keys` refuses a registry
    // that does not contain its own signer, and the entry is what downstream verifiers
    // resolve `conductor-session` signatures through. The private half it was signed with
    // is destroyed a few lines after this payload is signed, which the provenance note
    // says in the document itself rather than only in this comment.
    entries.push(registry_entry(
        &operator.key_id,
        &operator.public_key_hex(),
        OPERATOR,
        &operator.key_id,
        Some(
            "minted in memory at install, signed this registry and the conductor session, \
             and destroyed before provisioning returned: no file in this store carries the \
             private half, so this registry can never be re-signed and no key can ever be \
             added to it",
        ),
    ));
    if let Some(anchor) = anchor {
        entries.push(registry_entry(
            &anchor.key_id,
            &anchor.public_key,
            audit_signer::ANCHOR_AUTHORITY,
            &operator.key_id,
            Some(
                "minted by the audit signer principal on its own first start; this registry \
                 never held the private half, and the operator root that admitted it no longer \
                 exists",
            ),
        ));
    }
    entries.sort_by(|a, b| {
        a["key_id"].as_str().unwrap_or("").cmp(b["key_id"].as_str().unwrap_or(""))
    });

    json!({
        "schema": SCHEMA,
        "artifact_type": "trusted-key-registry",
        "operator_public_key": operator.public_key_hex(),
        "issued_at_epoch": now,
        "registry_version": REGISTRY_VERSION,
        // `load_trusted_keys` refuses a registry that is not marked production whenever
        // the operator pin comes from the production `BRO_OPERATOR_ROOT_PUBKEY_FILE`
        // path, which is the only pin path this deployment has. The marking is true in
        // the sense that check is about — these are not `broctl` development keys shared
        // out of a repository — and not in the sense a fleet operator would mean: the
        // private halves live on this machine. `provenance` and `posture` say which, in
        // the signed payload itself, so no reader has to infer it.
        "production": true,
        "provenance": "locally-minted-at-install",
        "posture": POSTURE_SUMMARY,
        "keys": entries,
    })
}

// ---------------------------------------------------------------------------
// Operator-signed artifacts
// ---------------------------------------------------------------------------

/// The **O-3** artifact: `engine/runtime/bro_policy.py`'s `conductor-session`.
///
/// `verify_conductor_session_token` requires a document that verifies as a
/// `conductor-session` against the registry AND binds `session_id`, `agent_id` and
/// `role` to the running state, with an integer `expires_at_epoch` in the future.
/// The session id is install-scoped rather than per-run: the harness reads it from
/// `BRO_SESSION_ID`, this deployment is the thing that would set it, and a per-run
/// token would mean using the operator-root private key on every launch to buy a
/// rotation whose only threat model is an attacker who already holds that key.
pub fn conductor_session_payload(operator_key_id: &str, session_id: &str, now: i64) -> Value {
    json!({
        "schema": SCHEMA,
        "artifact_type": "conductor-session",
        "key_id": operator_key_id,
        "session_id": session_id,
        "agent_id": CONDUCTOR_AGENT_ID,
        "role": CONDUCTOR_ROLE,
        "issued_at_epoch": now,
        "expires_at_epoch": NEVER_EXPIRES_EPOCH,
    })
}

/// The **O-5** artifact: `bro_completion._signed_floor_anchor`'s `evidence-floor-anchor`.
///
/// **Deliberately not minted at install, and deliberately not minted automatically.**
/// The anchor answers one question — "was this task's evidence floor wiped, or is this
/// the first time we have seen the task?" — and it only answers it because a principal
/// outside the policed process states the high-water mark. At install no task exists,
/// so there is nothing to state; and an anchor this application minted by reading the
/// very store the check polices would restate the store's own claim under a signature,
/// which is worse than no anchor because it looks like corroboration. It is exposed as
/// a function so a lost floor can be re-established deliberately, for a named task and
/// a chosen sequence — never as a startup side effect.
///
/// Signed by the **delegated `evidence-floor` key**, not the operator root, which no
/// longer exists by the time anyone can call this. That is the whole point of the
/// delegation: stating a high-water mark is routine and the trust root is not, so the
/// ability to do the routine thing survives while the ability to re-sign the trusted-key
/// registry does not. The `evidence-floor` key can sign this artifact and nothing else —
/// `bro_signature.ARTIFACT_AUTHORITY` binds it to exactly one type and `_parse_key`
/// refuses any registry entry that tries to grant it a second.
pub fn mint_floor_anchor(
    trust_dir: &Path,
    task_id: &str,
    head_sequence: i64,
    out: &Path,
) -> Result<Value, ProvisionError> {
    if head_sequence < 1 {
        return corrupt(
            "an evidence-floor-anchor needs a positive head_sequence",
            format!("got {head_sequence}"),
        );
    }
    let key = load_key(trust_dir, EVIDENCE_FLOOR)?;
    let payload = json!({
        "schema": SCHEMA,
        "artifact_type": "evidence-floor-anchor",
        "key_id": key.key_id,
        "task_id": task_id,
        "head_sequence": head_sequence,
        "issued_at_epoch": now_epoch(),
    });
    let document = sign_document(&key.signing, payload)?;
    write_json(out, &document)?;
    Ok(document)
}

/// The **O-4** artifact: `bro_control_room_api`'s `control-room-command`.
///
/// The owner's per-command attestation. `_prove_command_actor` verifies it as a
/// `control-room-command` and then requires `command_id`, `task_id` and `command` to
/// equal the command in hand, so signing one cancellation authorises exactly that
/// cancellation — never a window, which is what makes it stronger than the conductor's
/// `conductor-session`.
///
/// Signed by the **delegated `control-room` key**, for the reason given on
/// [`RETAINED_AUTHORITIES`]. That this key lives on the same machine as the app is not a
/// weakening worth avoiding: an account that can drive the control room can already
/// issue the command by other means. What it must not be able to do is rewrite the audit
/// record afterwards, and this key cannot — it is not an `audit-anchor`, and it cannot
/// sign the registry that would introduce one.
///
/// `expires_at_epoch` is an argument rather than [`NEVER_EXPIRES_EPOCH`]: a command
/// attestation that never expires is a bearer token for that command forever, and unlike
/// the install-scoped conductor session there is no ceremony cost to bounding it.
pub fn mint_control_room_command(
    trust_dir: &Path,
    command_id: &str,
    task_id: &str,
    command: &str,
    session_id: &str,
    expires_at_epoch: i64,
    out: &Path,
) -> Result<Value, ProvisionError> {
    let now = now_epoch();
    if expires_at_epoch <= now {
        return corrupt(
            "a control-room-command must expire in the future",
            format!("expires_at_epoch {expires_at_epoch} is not after {now}"),
        );
    }
    for (field, value) in
        [("command_id", command_id), ("task_id", task_id), ("command", command),
         ("session_id", session_id)]
    {
        if value.is_empty() {
            return corrupt(
                "a control-room-command must bind the command it authorises",
                format!("{field} is empty"),
            );
        }
    }
    let key = load_key(trust_dir, CONTROL_ROOM)?;
    let payload = json!({
        "schema": SCHEMA,
        "artifact_type": "control-room-command",
        "key_id": key.key_id,
        // `_prove_command_actor` checks these against the claimed actor before it looks
        // at the binding, so they are the owner identity `CONTROL_ROOM_ACTORS` names.
        "role": "owner",
        "agent_id": "owner-gev",
        "session_id": session_id,
        "command_id": command_id,
        "task_id": task_id,
        "command": command,
        "issued_at_epoch": now,
        "expires_at_epoch": expires_at_epoch,
    });
    let document = sign_document(&key.signing, payload)?;
    write_json(out, &document)?;
    Ok(document)
}

/// Read one authority's private key back off disk.
pub fn load_key(trust_dir: &Path, authority: &str) -> Result<AuthorityKey, ProvisionError> {
    let path = trust_dir.join(KEYS_DIR).join(format!("{authority}.json"));
    let raw = io(std::fs::read(&path), "reading a private key", &path)?;
    let value: Value = match serde_json::from_slice(&raw) {
        Ok(v) => v,
        Err(e) => return corrupt("a private key file is not JSON", e.to_string()),
    };
    let key_id = match value.get("key_id").and_then(|v| v.as_str()) {
        Some(s) => s.to_string(),
        None => return corrupt("a private key file has no key_id", path.display().to_string()),
    };
    let seed: [u8; 32] =
        match value.get("private_key").and_then(|v| v.as_str()).and_then(unhex).map(<[u8; 32]>::try_from)
        {
            Some(Ok(s)) => s,
            _ => {
                return corrupt(
                    "a private key file has no usable 32-byte seed",
                    path.display().to_string(),
                )
            }
        };
    Ok(AuthorityKey {
        authority_type: authority.to_string(),
        key_id,
        signing: SigningKey::from_bytes(&seed),
    })
}

// ---------------------------------------------------------------------------
// Writing
// ---------------------------------------------------------------------------

fn write_bytes(path: &Path, bytes: &[u8]) -> Result<(), ProvisionError> {
    if let Some(parent) = path.parent() {
        io(std::fs::create_dir_all(parent), "creating a directory", parent)?;
    }
    let mut file = io(std::fs::File::create(path), "creating a file", path)?;
    io(file.write_all(bytes), "writing a file", path)?;
    io(file.sync_all(), "flushing a file", path)?;
    Ok(())
}

fn write_json(path: &Path, value: &Value) -> Result<(), ProvisionError> {
    let mut bytes = canonical_bytes(value)?;
    bytes.push(b'\n');
    write_bytes(path, &bytes)
}

/// Key material only: created with an owner-only mode where the platform has one, then
/// restricted again through [`secure_owner_only_file`] because the creation mode is
/// masked by the process umask. `create_new` refuses to clobber an existing key file —
/// silently replacing a signing key is a rotation, and rotations must never be
/// accidental (the rule `broctl._write_key` states).
fn write_key_file(path: &Path, value: &Value) -> Result<(), ProvisionError> {
    let mut bytes = canonical_bytes(value)?;
    bytes.push(b'\n');
    if let Some(parent) = path.parent() {
        io(std::fs::create_dir_all(parent), "creating the key directory", parent)?;
    }
    let mut options = std::fs::OpenOptions::new();
    options.write(true).create_new(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        options.mode(0o600);
    }
    let mut file = io(options.open(path), "creating a private key file", path)?;
    io(file.write_all(&bytes), "writing a private key file", path)?;
    io(file.sync_all(), "flushing a private key file", path)?;
    drop(file);
    io(secure_owner_only_file(path), "restricting a private key file to its owner", path)?;
    Ok(())
}

// ---------------------------------------------------------------------------
// The result
// ---------------------------------------------------------------------------

#[derive(Debug, Clone)]
pub struct Provisioned {
    pub trust_dir: PathBuf,
    /// Where the pin, the anti-rollback floor and the manifest live: a directory this
    /// account cannot write. See [`anchor`].
    pub anchor_dir: PathBuf,
    /// Pass this as `root` to `bro_signature.load_trusted_keys`.
    pub registry_root: PathBuf,
    pub registry_path: PathBuf,
    pub operator_pin_path: PathBuf,
    pub registry_floor_path: PathBuf,
    pub conductor_session_path: PathBuf,
    pub keys_dir: PathBuf,
    pub install_id: String,
    pub session_id: String,
    pub operator_key_id: String,
    pub operator_public_key: String,
    /// True when THIS call minted the store; false when it verified an existing one.
    pub freshly_minted: bool,
    pub dir_protection: Protection,
    pub key_file_protection: Protection,
    /// The OS's own answer to "can this account rewrite the anchor?", re-measured on THIS
    /// call. Never read from a file: a stored proof is a claim about the past.
    ///
    /// `None` ONLY when the store came from [`mint_store_without_custody_proof`] or
    /// [`verify_store_without_custody_proof`], which exist so the mint and the verifier can be
    /// tested without permanently sealing a directory on the machine running the tests. A
    /// `None` here means the anchor's custody was never established and the store must not be
    /// used: `provision`, `provision_with_anchor` and `verify_existing` — every path the
    /// application actually takes — always carry `Some`.
    pub custody: Option<anchor::CustodyProof>,
}

impl Provisioned {
    /// The environment a deployment must export for the engine to USE what was minted.
    ///
    /// Returned rather than applied. Two of these change how the engine resolves its
    /// trust root process-wide, and `bro_signature` hard-fails when a file pin and a
    /// raw CI pin disagree — so which process gets them, and when, is a deployment
    /// decision, not this module's to make silently at startup.
    pub fn engine_env(&self) -> Vec<(&'static str, String)> {
        vec![
            ("BRO_OPERATOR_ROOT_PUBKEY_FILE", self.operator_pin_path.display().to_string()),
            ("BRO_OPERATOR_REGISTRY_MIN_FILE", self.registry_floor_path.display().to_string()),
            // `BRO_OPERATOR_ROOT_PIN_SELF_OWNED` is deliberately ABSENT, and its absence is
            // the point of this whole round. It used to be set to `acknowledged`, which is
            // the deployment saying out loud that the account reading the pin can also write
            // it — `bro_custody` short-circuits every custody rule when it is set. The pin
            // and the floor now live in [`anchor`], which this account cannot write, so the
            // engine's own unacknowledged rule (`bro_signature._pin_from_file` ->
            // `bro_custody.refuse_windows_writable` / `posix_rewrite_verdict`) accepts them
            // on their merits. Setting it again would re-disable the check that is now the
            // only thing standing between the app and a trust root of its own choosing.
            ("BRO_CONDUCTOR_SESSION_TOKEN", self.conductor_session_path.display().to_string()),
            ("BRO_SESSION_ID", self.session_id.clone()),
        ]
    }
}

// ---------------------------------------------------------------------------
// Provisioning
// ---------------------------------------------------------------------------

/// The audit signer's published custody record, if this machine has one.
///
/// `machine_root` is `%ProgramData%\BroPS` — the same root [`audit_signer::SignerPaths`]
/// derives from, restated as an argument so a caller can point it anywhere for a test.
///
/// * absent → `Ok(None)`: this machine has no audit signer, which is the POSIX case and
///   the case before the elevated installer has run. Provisioning proceeds without an
///   anchor and every keyed `bro_audit_log.verify()` then fails closed, which is correct
///   and is not this function's business to paper over.
/// * present but unreadable or not JSON → `Err`: a signer that IS installed and whose
///   published identity cannot be read must not be silently downgraded to "no signer".
///   That is the difference between "this deployment has no audit anchor" and "this
///   deployment has one and I could not see it", and only one of them is safe to assume.
pub fn published_anchor_custody(machine_root: &Path) -> Result<Option<Value>, ProvisionError> {
    let path = machine_root
        .join(audit_signer::SIGNER_DIR_NAME)
        .join(audit_signer::CUSTODY_FILE_NAME);
    if !path.exists() {
        return Ok(None);
    }
    let raw = io(std::fs::read(&path), "reading the audit signer's custody record", &path)?;
    match serde_json::from_slice(&raw) {
        Ok(value) => Ok(Some(value)),
        Err(e) => corrupt(
            "the audit signer's published custody record is not JSON",
            format!("{}: {e}", path.display()),
        ),
    }
}

/// Mint the trust store on first launch, or verify the one that is already there.
///
/// Call this immediately after `secure_data_dir(&app_data_dir)` and before the
/// database is opened. An `Err` must abort startup: a half-trusted governance chain is
/// worse than an absent one, so there is no degraded mode to fall back to.
///
/// Equivalent to [`provision_with_anchor`] with no anchor. A store minted this way can
/// NEVER be given one afterwards — see that function for why. A Windows deployment that
/// installs the audit signer must call [`provision_with_anchor`] with
/// [`published_anchor_custody`] instead.
pub fn provision(
    app_data_dir: &Path,
    machine_root: &Path,
) -> Result<Provisioned, ProvisionError> {
    provision_with_anchor(app_data_dir, machine_root, None)
}

/// Mint the trust store, optionally admitting the audit signer's published key.
///
/// # Why the anchor key has to arrive HERE and nowhere later
///
/// `bro_audit_log.verify_signed_payload` resolves an anchor's `key_id` through the
/// trusted-key registry, and `bro_signature.ARTIFACT_AUTHORITY` binds
/// `trusted-key-registry` to `operator-root`. Since [`mint`] destroys the root before it
/// returns, the registry is **sealed** at that moment: no key can ever be added to it
/// again. So the signer service's public half must be in hand when the registry is
/// signed, or the deployment has no verifiable audit anchor at all.
///
/// That is the install order the plan already specifies
/// (`audit_signer::install_steps`): the elevated installer registers and starts the
/// service, the service mints its own seed under its own account and publishes
/// `custody.json`, and only then does the app run for the first time. `custody` is that
/// published record — `{key_id, public_key, authority}` — and nothing secret, which
/// `brops_audit_signer::custody::read_custody` enforces on the reading side.
///
/// **The cost, stated rather than discovered.** Rotating the signer's key, or installing
/// the signer service after the app has already provisioned, means re-minting the whole
/// trust store: move the `trust` directory aside and let the next launch build a new one.
/// Every artifact signed under the old keys stops verifying, which `POSTURE.txt` already
/// says about deleting the directory. The alternative — keeping a key that can amend the
/// registry — is the thing this design exists to remove.
pub fn provision_with_anchor(
    app_data_dir: &Path,
    machine_root: &Path,
    anchor: Option<&Value>,
) -> Result<Provisioned, ProvisionError> {
    let anchor_dir = anchor::anchor_dir(machine_root);
    let trust = app_data_dir.join(TRUST_DIR);
    // The MANIFEST is the idempotency marker, and it lives in the anchor directory. That is
    // not incidental: the marker that says "this machine is provisioned" must not itself be a
    // file the provisioned machine can delete, or a first launch can be staged over and over.
    if anchor_dir.join(MANIFEST_FILE).is_file() {
        return verify_existing(&trust, &anchor_dir);
    }
    // Refuse BEFORE minting anything if the location cannot become an anchor. Everything below
    // this point is expensive and, once sealed, irreversible for this account; discovering
    // afterwards that the path can be renamed aside would leave a sealed directory nothing
    // running as this account can remove.
    anchor::precheck_location(&anchor_dir, machine_root)?;
    if anchor_dir.exists() {
        return corrupt(
            "the trust anchor path already holds something that is not a provisioned anchor",
            format!(
                "{} exists but has no {MANIFEST_FILE}. It is either a half-removed anchor or a \
                 directory something else owns; minting over it would destroy whichever it is, \
                 and sealing over it would make that permanent",
                anchor_dir.display()
            ),
        );
    }
    // Something is at the trust path but it is not a provisioned store. Refuse rather
    // than mint over it. This is also where the two platforms would otherwise differ:
    // `std::fs::rename` on Windows carries `MOVEFILE_REPLACE_EXISTING`, so renaming the
    // staging directory over an existing FILE succeeds there and fails with ENOTDIR on
    // unix. Deciding here, before anything is minted, makes the behaviour the same
    // everywhere and the refusal explicit.
    refuse_occupied_trust_path(&trust)?;

    // Mint into a staging directory and rename it into place as the last step, so the
    // trust directory only ever exists complete. A failure in between removes the
    // staging directory and leaves nothing behind.
    let staging = app_data_dir.join(format!(".trust-staging-{}", random_hex(8)?));
    let minted = match mint(&staging, anchor) {
        Ok(minted) => minted,
        Err(e) => {
            let _ = std::fs::remove_dir_all(&staging);
            return Err(e);
        }
    };
    if let Err(source) = std::fs::rename(&staging, &trust) {
        let _ = std::fs::remove_dir_all(&staging);
        // A concurrent first launch may have won the race and put a complete store
        // there. That is a success, not a failure — verify theirs.
        if anchor_dir.join(MANIFEST_FILE).is_file() {
            return verify_existing(&trust, &anchor_dir);
        }
        return Err(ProvisionError::Io {
            what: "moving the newly minted trust store into place".into(),
            path: trust,
            source,
        });
    }

    // The anchor half: the pin, the floor and the manifest, then the seal, then the operating
    // system's own answer to whether the seal took.
    if let Err(e) = establish_anchor(&anchor_dir, machine_root, &trust, &minted) {
        // Whatever failed, it failed at or before the proof — so either nothing was sealed or
        // the seal did not take, and in both cases this account can still remove what it just
        // wrote. A half-provisioned pair must never survive: an app-side store without its
        // anchor is a trust store with no trust root.
        let _ = std::fs::remove_dir_all(&anchor_dir);
        let _ = std::fs::remove_dir_all(&trust);
        return Err(e);
    }

    // Verify what we just wrote through exactly the same code a later launch uses. A mint that
    // produces something the verifier rejects must not survive — but the anchor is sealed by
    // now, so removing it is no longer this account's to do. That is stated rather than papered
    // over: the refusal names the paths and an administrator has to clear them.
    let mut provisioned = verify_existing(&trust, &anchor_dir)?;
    provisioned.freshly_minted = true;
    Ok(provisioned)
}

/// Write the anchor half, seal it, and prove the seal took.
///
/// The order is the whole safety argument:
///
/// 1. the pin, the floor and `CUSTODY.txt` — plain writes, still this account's to make;
/// 2. the manifest LAST, because its presence is what makes the machine "provisioned" and it
///    must not appear until everything it describes is in place;
/// 3. [`anchor::seal`], after which this account can no longer write, delete or rename any of
///    them, or any directory on the path to them;
/// 4. [`anchor::prove_unwritable`], which asks the operating system — rather than this code —
///    whether step 3 did what it claimed.
///
/// Step 4 is not a formality. Step 3 can succeed on every call and still leave the anchor
/// reachable, because a security descriptor cannot restrain a parent directory. That is not
/// hypothetical: it is what the first construction for this round did, and the rename that
/// defeated it took one call.
fn establish_anchor(
    anchor_dir: &Path,
    machine_root: &Path,
    trust: &Path,
    minted: &Minted,
) -> Result<(), ProvisionError> {
    write_anchor_files(anchor_dir, trust, minted)?;
    anchor::seal(anchor_dir, machine_root)?;
    anchor::prove_unwritable(anchor_dir)?;
    Ok(())
}

/// Steps 1 and 2 of [`establish_anchor`]: the pin, the floor, `CUSTODY.txt` and the manifest.
fn write_anchor_files(
    anchor_dir: &Path,
    trust: &Path,
    minted: &Minted,
) -> Result<(), ProvisionError> {
    io(std::fs::create_dir_all(anchor_dir), "creating the trust anchor directory", anchor_dir)?;

    write_bytes(
        &anchor_dir.join(OPERATOR_PIN_FILE),
        format!("{}\n", minted.operator_public_key).as_bytes(),
    )?;
    write_bytes(&anchor_dir.join(REGISTRY_FLOOR_FILE), format!("{REGISTRY_VERSION}\n").as_bytes())?;
    write_json(
        &under(&anchor_dir.join(REGISTRY_ROOT_DIR), REGISTRY_REL),
        &minted.registry,
    )?;
    write_bytes(&anchor_dir.join(anchor::CUSTODY_FILE), anchor::custody_text().as_bytes())?;

    // The manifest records the digest of every APP-SIDE file. That direction is the point: the
    // half this account can rewrite is vouched for by the half it cannot.
    let mut files = BTreeMap::new();
    for relative in provisioned_files() {
        let path = under(trust, &relative);
        let bytes = io(std::fs::read(&path), "hashing a provisioned file", &path)?;
        files.insert(relative, Value::from(sha256_hex(&bytes)));
    }
    let manifest = json!({
        "schema": SCHEMA,
        "install_id": minted.install_id,
        "session_id": minted.session_id,
        "provisioned_at_epoch": minted.now,
        "registry_version": REGISTRY_VERSION,
        "operator_key_id": minted.operator_key_id,
        "operator_public_key": minted.operator_public_key,
        // Which store this anchor is the anchor FOR. An anchor that named no store could be
        // pointed at a second one the same account minted somewhere it CAN write.
        "trust_dir": trust.display().to_string(),
        "operator_root_custody": OPERATOR_ROOT_CUSTODY,
        "anchor_custody": ANCHOR_CUSTODY,
        "anchor_key_id": minted.anchor_key_id,
        "not_before_epoch": NOT_BEFORE_EPOCH,
        "not_after_epoch": NEVER_EXPIRES_EPOCH,
        "expiry_policy": "non-expiring by design: this product has no operator but its owner, \
                          so nothing may ever require a renewal. Revocation is a re-mint plus a \
                          registry_version rise, enforced by the anti-rollback floor, not an \
                          expiry date.",
        "platform": platform_name(),
        "directory_protection": directory_protection().to_string(),
        "key_file_protection": key_file_protection().to_string(),
        "posture": POSTURE_SUMMARY,
        "files": files.into_iter().collect::<Map<String, Value>>(),
    });
    write_json(&anchor_dir.join(MANIFEST_FILE), &manifest)?;
    Ok(())
}

/// Refuse to mint over whatever is already at the trust path.
///
/// Asked before anything is minted, and identically on both platforms, because the two differ
/// where it matters: `std::fs::rename` on Windows carries `MOVEFILE_REPLACE_EXISTING`, so
/// renaming the staging directory over an existing FILE succeeds there and fails with `ENOTDIR`
/// on unix. Deciding here makes the behaviour the same everywhere and the refusal explicit.
///
/// It lives in one function rather than in `provision_with_anchor` because
/// `mint_store_without_custody_proof` mints too, and a refusal that only one of two minting
/// paths performs is a refusal the other one does not have.
fn refuse_occupied_trust_path(trust: &Path) -> Result<(), ProvisionError> {
    if !trust.exists() {
        return Ok(());
    }
    corrupt(
        "the trust path already holds something that is not a provisioned store",
        format!(
            "{} exists but the trust anchor records no provisioning for it. It is either a \
             half-removed store or a directory something else owns, and minting over it would \
             destroy whichever it is",
            trust.display()
        ),
    )
}

/// Every file the mint writes, relative to the trust directory, in manifest order.
///
/// Driven by [`RETAINED_AUTHORITIES`], so `keys/operator-root.json` is not merely absent
/// from the directory — it is absent from the list `verify_existing` requires the manifest
/// to cover, which is what makes a later launch refuse a store that grew one.
fn provisioned_files() -> Vec<String> {
    let mut relatives: Vec<String> =
        RETAINED_AUTHORITIES.iter().map(|a| format!("{KEYS_DIR}/{a}.json")).collect();
    // The registry is NOT here either: it moved to the anchor with the pin and the floor,
    // because `bro_signature.resolve_registry_root` refuses a registry root the reading
    // account can write. What is left in this list is the private key material the app
    // legitimately uses and the conductor-session artifact — neither of which can be forged
    // without a key that no longer exists, and both of which are bound by digest from a
    // manifest that account cannot rewrite.
    // The pin and the floor are NOT here: they are not in the trust directory any more, and
    // a digest recorded for them would be a digest of a file this manifest sits beside. What
    // this list covers is exactly the app-WRITABLE half — the half whose integrity has to be
    // vouched for from outside it.
    relatives.push(format!("{ARTIFACTS_DIR}/{CONDUCTOR_SESSION_FILE}"));
    relatives.push(POSTURE_FILE.to_string());
    relatives
}

fn under(root: &Path, relative: &str) -> PathBuf {
    let mut path = root.to_path_buf();
    for component in relative.split('/') {
        path.push(component);
    }
    path
}

/// Mint the whole store into `staging`, and destroy the operator root before returning.
///
/// The ordering below is load-bearing. Everything the root will ever sign is signed
/// inside one scope, and the key leaves that scope only by being dropped. Nothing after
/// the drop can reach it, and — because no `write_key_file` call names `operator-root` —
/// nothing before the drop wrote it down.
/// What [`mint`] produces that the ANCHOR half needs. Every field is public information:
/// the private halves are on disk under `staging`, and the one that never was — the operator
/// root — is represented here only by its 64-character public key.
struct Minted {
    install_id: String,
    session_id: String,
    operator_key_id: String,
    operator_public_key: String,
    anchor_key_id: Option<String>,
    now: i64,
    /// The signed `trusted-key-registry` document. It is carried here rather than written by
    /// `mint`, because it belongs on the anchor side: see [`REGISTRY_ROOT_DIR`].
    registry: Value,
}

fn mint(staging: &Path, anchor: Option<&Value>) -> Result<Minted, ProvisionError> {
    io(std::fs::create_dir_all(staging), "creating the staging directory", staging)?;
    io(secure_data_dir(staging), "restricting the staging directory to its owner", staging)?;

    let install_id = random_hex(8)?;
    let now = now_epoch();
    let session_id = format!("brops-{install_id}");
    let anchor = match anchor {
        Some(record) => Some(AnchorKey::from_custody(record)?),
        None => None,
    };

    let mut keys: Vec<AuthorityKey> = Vec::with_capacity(RETAINED_AUTHORITIES.len());
    for authority in RETAINED_AUTHORITIES {
        keys.push(mint_key(authority, &install_id)?);
    }

    let keys_dir = staging.join(KEYS_DIR);
    io(std::fs::create_dir_all(&keys_dir), "creating the key directory", &keys_dir)?;
    io(secure_data_dir(&keys_dir), "restricting the key directory to its owner", &keys_dir)?;
    // Only the RETAINED keys are in `keys`, so there is no operator-root file to forget
    // to skip. A filter here would be a line somebody could later relax; an absence
    // cannot be.
    for key in &keys {
        write_key_file(&keys_dir.join(format!("{}.json", key.authority_type)), &key.to_json())?;
    }

    // --- everything the operator root will ever sign, inside one scope ----------------
    //
    // The root is minted here rather than with the others, and it is never added to
    // `keys`: `keys` is what gets written to disk, and the whole point is that this one
    // does not. `operator_public_key` is what survives — the pin, the registry's own
    // `operator_public_key` field and the manifest all carry the PUBLIC half.
    let operator_public_key;
    let registry_document;
    let operator_key_id = format!("brops-{install_id}-{OPERATOR}");
    {
        let operator = mint_key(OPERATOR, &install_id)?;
        operator_public_key = operator.public_key_hex();

        registry_document = sign_document(
            &operator.signing,
            registry_payload(&keys, &operator, anchor.as_ref(), now),
        )?;

        let session = sign_document(
            &operator.signing,
            conductor_session_payload(&operator.key_id, &session_id, now),
        )?;
        write_json(&staging.join(ARTIFACTS_DIR).join(CONDUCTOR_SESSION_FILE), &session)?;

        // `operator` is dropped HERE. `ed25519_dalek::SigningKey` is `ZeroizeOnDrop`
        // (dalek 2.x enables `zeroize` by default and its `Drop` wipes `secret_key`), and
        // the seed array it was built from was wiped inside `mint_key`. What is left in
        // this function is a 64-character PUBLIC key hex string.
    }
    debug_assert_eq!(operator_public_key.len(), 64);

    // The pin and the anti-rollback floor are NOT written here any more, and that absence is
    // the change this whole round is. They used to be `staging/pin/*`, restricted to their
    // owner — which is the account being policed, so the restriction protected the anchor from
    // everyone except the one principal it needed to be protected from. They are written by
    // `establish_anchor` into a directory that account cannot write, and so is the manifest.
    write_bytes(&staging.join(POSTURE_FILE), posture_text(&install_id).as_bytes())?;

    Ok(Minted {
        install_id,
        session_id,
        operator_key_id,
        operator_public_key,
        anchor_key_id: anchor.as_ref().map(|a| a.key_id.clone()),
        now,
        registry: registry_document,
    })
}

pub const POSTURE_SUMMARY: &str =
    "trust material minted on the installing user's machine: it protects against an attacker \
     who arrives later, not against one who already owned the machine at install time (the \
     same posture as an SSH host key)";

/// What became of the operator root, recorded in the manifest.
///
/// Two claims, and the second is as important as the first. Not writing the key down is
/// not the same as putting the anchor out of reach, and a manifest that said only the
/// first would be inviting exactly the overclaim this store must not make.
/// What became of the trust ANCHOR — the claim `OPERATOR_ROOT_CUSTODY` had to decline to make.
///
/// The two are deliberately separate strings. Destroying a key and moving an anchor are
/// different properties, they were closed in different rounds, and a single sentence covering
/// both would let either be believed on the strength of the other.
pub const ANCHOR_CUSTODY: &str =
    "the operator-root pin, the registry anti-rollback floor and this manifest live OUTSIDE the \
     application\'s data directory, in a location the account the application runs as cannot \
     write: on Windows a PROTECTED DACL whose OWNER RIGHTS (S-1-3-4) entry replaces the owner\'s \
     implicit READ_CONTROL|WRITE_DAC with read+execute, applied to the anchor, its files and \
     every ancestor up to the machine root; on POSIX a uid the application is not. This is \
     re-proved on EVERY launch by asking the operating system - creating a file here, opening \
     each file here for writing, and opening this directory and every ancestor for DELETE must \
     all be refused - and the application refuses to start if any of them succeeds. Because of \
     it, BRO_OPERATOR_ROOT_PIN_SELF_OWNED is NOT set: the engine\'s own custody rule passes on \
     its merits rather than being switched off.";

pub const OPERATOR_ROOT_CUSTODY: &str =
    "destroyed at the end of provisioning: the operator-root private half was generated in \
     memory, signed the trusted-key registry and the conductor session, and was dropped before \
     the mint returned. No file in this store carries it. The registry is therefore SEALED — no \
     key can be added to it, including an audit-anchor one. This does NOT make the trust root \
     external: pin/operator-root.pub still lives in this directory, so an account that can \
     rewrite it can install a root of its own and re-sign everything under it. Removing the key \
     removed one route, not the anchor's custody.";

fn posture_text(install_id: &str) -> String {
    format!(
        "BroPS local trust store (install {install_id})\n\
         =================================================\n\
         \n\
         WHAT THIS IS\n\
         Every key here was generated on this machine the first time BroPS started.\n\
         The operator-root key signed the trusted-key registry under registry/config/,\n\
         and pin/{OPERATOR_PIN_FILE} holds its public half as the out-of-registry trust\n\
         anchor the engine pins from BRO_OPERATOR_ROOT_PUBKEY_FILE.\n\
         \n\
         THE OPERATOR-ROOT PRIVATE HALF IS NOT HERE\n\
         It was generated in memory, used to sign the registry and the conductor\n\
         session, and destroyed before provisioning returned. keys/ therefore holds no\n\
         operator-root.json and never did. The consequence is deliberate: the registry\n\
         is SEALED. No key can be added to it afterwards -- not a replacement authority,\n\
         and not an audit-anchor key for the audit ledger's head. If the audit signer\n\
         service is installed or rotated after this store was minted, the store has to\n\
         be re-minted (move this directory aside; the next launch builds a new one).\n\
         \n\
         WHAT IT PROTECTS AGAINST\n\
         An attacker who arrives AFTER installation. From that moment the chain is\n\
         real: the registry cannot be re-signed by anybody, it cannot be replayed below\n\
         the version in pin/{REGISTRY_FLOOR_FILE}, and a builder key cannot sign a\n\
         verifier receipt. In particular the account that writes the audit ledger holds\n\
         no key that can anchor it and no key that can admit one.\n\
         \n\
         WHAT IT DOES NOT PROTECT AGAINST\n\
         An attacker who already owned this machine when BroPS was installed. They\n\
         witnessed the mint or performed it. This is the normal posture for\n\
         locally-minted trust material -- an SSH host key works the same way -- and it\n\
         is stated here rather than implied away. Nothing in this store is evidence of\n\
         provenance from a vendor.\n\
         \n\
         And, specifically: destroying the operator root did NOT move the trust anchor\n\
         out of this account's reach. pin/{OPERATOR_PIN_FILE} is a file in this\n\
         directory. An account that can rewrite it can generate an operator key of its\n\
         own, pin it, and re-sign the registry under it -- with no need for the key that\n\
         was destroyed. Closing that needs a second principal holding the pin, which a\n\
         single-user install does not have.\n\
         \n\
         WHY THE ENGINE IS TOLD TO ACCEPT IT\n\
         The engine refuses a trust anchor the reading account can rewrite, unless the\n\
         deployment sets BRO_OPERATOR_ROOT_PIN_SELF_OWNED=acknowledged. A single-user\n\
         desktop has no second principal to offer, so that is what it must set. That\n\
         does not make the anchor stronger; it makes the weakness explicit.\n\
         \n\
         NOTHING HERE EVER EXPIRES\n\
         Keys carry not_after_epoch = {NEVER_EXPIRES_EPOCH} (9999-12-31Z) so this\n\
         application never asks its owner to renew anything. With no operator root\n\
         alive, retiring a key means re-minting this whole directory.\n\
         \n\
         Deleting this directory makes BroPS mint a new one on the next launch. Every\n\
         artifact signed under the old keys stops verifying.\n"
    )
}

/// Verify a trust store that is already on disk. Never repairs, never re-mints.
///
/// # The first thing it does, and why it is first
///
/// It proves the anchor's custody before it reads a single byte out of it. Every other check
/// below — the digests, the registry signature, the conductor session — resolves through the
/// pin, and a pin the reading account can rewrite makes all of them checks against a value that
/// account chose. Reading first and checking custody afterwards would be the same defect one
/// step later.
///
/// This runs on EVERY launch, not only at install. An anchor is not a thing that was true once:
/// an administrator can re-permission the directory, the application can be moved to a machine
/// where the path means something else, and the account it runs as can change. The property is
/// re-measured against the operating system each time and a launch that cannot demonstrate it
/// fails closed.
pub fn verify_existing(
    trust: &Path,
    anchor_dir: &Path,
) -> Result<Provisioned, ProvisionError> {
    let custody = anchor::prove_unwritable(anchor_dir)?;
    let mut provisioned = verify_store(trust, anchor_dir)?;
    provisioned.custody = Some(custody);
    Ok(provisioned)
}

/// Everything `verify_existing` checks EXCEPT the anchor's custody.
fn verify_store(trust: &Path, anchor_dir: &Path) -> Result<Provisioned, ProvisionError> {
    let manifest_path = anchor_dir.join(MANIFEST_FILE);
    let raw =
        io(std::fs::read(&manifest_path), "reading the provisioning manifest", &manifest_path)?;
    let manifest: Value = match serde_json::from_slice(&raw) {
        Ok(v) => v,
        Err(e) => return corrupt("the provisioning manifest is not JSON", e.to_string()),
    };
    if manifest.get("schema").and_then(|v| v.as_i64()) != Some(SCHEMA) {
        return corrupt(
            "the provisioning manifest is not schema 1",
            format!("got {:?}", manifest.get("schema")),
        );
    }

    // 1. The manifest names the store it is the anchor FOR.
    //
    //    Without this, an anchor is a floating claim: the same account that owns the app data
    //     directory could mint a SECOND trust store somewhere it CAN write, point the engine at
    //    the sealed anchor and the second store together, and every digest in the manifest
    //    would simply be a digest of files that are not the ones being used. The manifest is
    //    unforgeable, so binding the path into it is enough to make that mismatch visible.
    match manifest.get("trust_dir").and_then(|v| v.as_str()) {
        Some(recorded) if recorded == trust.display().to_string() => {}
        other => {
            return corrupt(
                "the trust anchor was provisioned for a different trust store",
                format!(
                    "the manifest in the anchor names {other:?}, but the store being verified is \
                     {}. An anchor that did not name its store could be paired with a second \
                     store minted somewhere this account CAN write",
                    trust.display()
                ),
            )
        }
    }

    // 2. Every file the mint recorded is present with the digest it recorded, and the
    //    manifest covers every file the mint is supposed to write (so dropping an entry
    //    cannot smuggle a file past the digest check).
    let files = match manifest.get("files").and_then(|v| v.as_object()) {
        Some(f) if !f.is_empty() => f,
        _ => return corrupt("the provisioning manifest lists no files", "empty `files`"),
    };
    for (relative, expected) in files {
        let path = under(trust, relative);
        let bytes = io(std::fs::read(&path), "re-hashing a provisioned file", &path)?;
        let actual = sha256_hex(&bytes);
        if Some(actual.as_str()) != expected.as_str() {
            return corrupt(
                "a provisioned file no longer matches the digest recorded at install",
                format!("{relative}: recorded {expected}, found {actual}"),
            );
        }
    }
    for relative in provisioned_files() {
        if !files.contains_key(&relative) {
            return corrupt(
                "the provisioning manifest does not cover every provisioned file",
                format!("no digest recorded for {relative}"),
            );
        }
    }

    // 2b. The key directory holds the RETAINED authorities and nothing else — asked of
    //     the directory, not of the manifest that describes it.
    //
    //     The digest loop above cannot see this. It checks that every file the manifest
    //     names is unchanged and that the manifest names every file the mint writes;
    //     neither says anything about a file the mint never wrote. Dropping a key seed
    //     into `keys/operator-root.json` after the fact adds no digest to compare and
    //     removes none, so without this check the store would go on verifying with a
    //     registry-signing key sitting beside it — which is precisely the state the
    //     destruction exists to prevent, whether it arrived by a future edit to `mint`
    //     or by somebody's hand.
    let keys_dir = trust.join(KEYS_DIR);
    let listing = io(std::fs::read_dir(&keys_dir), "listing the key directory", &keys_dir)?;
    for entry in listing {
        let entry = io(entry, "reading the key directory", &keys_dir)?;
        let name = entry.file_name().to_string_lossy().to_string();
        let stem = name.strip_suffix(".json").unwrap_or(&name);
        if !RETAINED_AUTHORITIES.contains(&stem) {
            return corrupt(
                "the key directory holds private key material provisioning never wrote",
                format!(
                    "{} is not one of the retained authorities ({}). {OPERATOR_ROOT_CUSTODY}",
                    keys_dir.join(&name).display(),
                    RETAINED_AUTHORITIES.join(", ")
                ),
            );
        }
    }

    // 3. The pin file and the registry agree on the operator-root public key.
    let pin_path = anchor_dir.join(OPERATOR_PIN_FILE);
    let pin = io(std::fs::read_to_string(&pin_path), "reading the operator-root pin", &pin_path)?
        .trim()
        .to_string();
    let registry_root = anchor_dir.join(REGISTRY_ROOT_DIR);
    let registry_path = under(&registry_root, REGISTRY_REL);
    let registry_raw =
        io(std::fs::read(&registry_path), "reading the trusted-key registry", &registry_path)?;
    let registry: Value = match serde_json::from_slice(&registry_raw) {
        Ok(v) => v,
        Err(e) => return corrupt("the trusted-key registry is not JSON", e.to_string()),
    };

    // 4. The registry verifies under the pin — the same check `load_trusted_keys` runs.
    let payload = verify_document(&registry, &pin)?;
    if payload.get("operator_public_key").and_then(|v| v.as_str()) != Some(pin.as_str()) {
        return corrupt(
            "the registry names an operator key other than the pinned one",
            "payload.operator_public_key != the pinned operator-root public key",
        );
    }
    if payload.get("production").and_then(|v| v.as_bool()) != Some(true) {
        return corrupt(
            "the registry is not marked production",
            "`load_trusted_keys` refuses a non-production registry whenever the pin comes from \
             BRO_OPERATOR_ROOT_PUBKEY_FILE, which is the only pin path this deployment has",
        );
    }

    // 5. Every authority the engine knows has an ACTIVE key, and the registry's
    //    operator-root key is the pinned one (`load_trusted_keys`'s last check).
    let entries = match payload.get("keys").and_then(|v| v.as_array()) {
        Some(k) if !k.is_empty() => k.clone(),
        _ => return corrupt("the registry contains no keys", "empty `keys`"),
    };
    let mut operator_key_id = String::new();
    // `MINTED_AUTHORITIES`, not `RETAINED_AUTHORITIES`: the registry must still name an
    // ACTIVE operator-root key — its PUBLIC half, which is the pin, and which
    // `load_trusted_keys` refuses a registry for not containing. What is gone is the
    // private half, and a registry entry is not one.
    for authority in MINTED_AUTHORITIES {
        let found = entries.iter().find(|e| {
            e.get("authority_type").and_then(|v| v.as_str()) == Some(authority)
                && e.get("status").and_then(|v| v.as_str()) == Some("active")
        });
        let entry = match found {
            Some(entry) => entry,
            None => {
                return corrupt(
                    "the registry has no active key for an authority the engine knows",
                    format!("missing an active {authority} key"),
                )
            }
        };
        if authority == OPERATOR {
            if entry.get("public_key").and_then(|v| v.as_str()) != Some(pin.as_str()) {
                return corrupt(
                    "the registry's operator-root key is not the pinned key",
                    "an operator-signed registry that does not contain its own signer is refused \
                     by `load_trusted_keys`",
                );
            }
            operator_key_id =
                entry.get("key_id").and_then(|v| v.as_str()).unwrap_or_default().to_string();
        }
    }

    // 6. The conductor-session artifact still verifies and still binds what O-3 requires.
    let session_path = trust.join(ARTIFACTS_DIR).join(CONDUCTOR_SESSION_FILE);
    let session_raw =
        io(std::fs::read(&session_path), "reading the conductor-session artifact", &session_path)?;
    let session: Value = match serde_json::from_slice(&session_raw) {
        Ok(v) => v,
        Err(e) => return corrupt("the conductor-session artifact is not JSON", e.to_string()),
    };
    let session_payload = verify_document(&session, &pin)?;
    for (field, expected) in [
        ("artifact_type", "conductor-session"),
        ("agent_id", CONDUCTOR_AGENT_ID),
        ("role", CONDUCTOR_ROLE),
        ("key_id", operator_key_id.as_str()),
    ] {
        if session_payload.get(field).and_then(|v| v.as_str()) != Some(expected) {
            return corrupt(
                "the conductor-session artifact does not bind what the engine checks",
                format!("{field} is {:?}, expected {expected:?}", session_payload.get(field)),
            );
        }
    }
    let session_id = match session_payload.get("session_id").and_then(|v| v.as_str()) {
        Some(s) if !s.is_empty() => s.to_string(),
        _ => return corrupt("the conductor-session artifact carries no session_id", "empty"),
    };
    match session_payload.get("expires_at_epoch").and_then(|v| v.as_i64()) {
        Some(e) if e > now_epoch() => {}
        other => {
            return corrupt(
                "the conductor-session artifact has expired",
                format!(
                    "expires_at_epoch is {other:?}; the engine refuses a token whose expiry is \
                     not an integer in the future"
                ),
            )
        }
    }

    Ok(Provisioned {
        trust_dir: trust.to_path_buf(),
        anchor_dir: anchor_dir.to_path_buf(),
        registry_root,
        registry_path,
        operator_pin_path: pin_path,
        registry_floor_path: anchor_dir.join(REGISTRY_FLOOR_FILE),
        conductor_session_path: session_path,
        keys_dir: trust.join(KEYS_DIR),
        install_id: manifest
            .get("install_id")
            .and_then(|v| v.as_str())
            .unwrap_or_default()
            .to_string(),
        session_id,
        operator_key_id,
        operator_public_key: pin,
        freshly_minted: false,
        dir_protection: directory_protection(),
        key_file_protection: key_file_protection(),
        custody: None,
    })
}

/// Verify the app-side store against the anchor's manifest and pin — **and do not ask who can
/// write the anchor**.
///
/// This is the mechanism, not an entry point. [`verify_existing`] is the entry point: it runs
/// [`anchor::prove_unwritable`] first and then this. The split exists for one reason, and it is
/// a property of what was built rather than a convenience: [`anchor::seal`] is one-way for the
/// account that applies it, so a test that wanted a sealed anchor would have to leave a
/// directory on the machine that nothing running as the test's own account could ever remove.
/// The digest, registry and conductor-session logic is testable without that; the custody
/// property is tested separately, against a real sealed directory, in `tests/anchor_custody.rs`
/// and `audit-signer/tests/anchor_end_to_end.rs`.
///
/// The name is deliberately unpleasant. Nothing shipping may call it: a store verified this way
/// carries `custody: None`, and `custody: None` means the pin it was verified against may be
/// one the verifying account wrote a moment earlier.
pub fn verify_store_without_custody_proof(
    trust: &Path,
    anchor_dir: &Path,
) -> Result<Provisioned, ProvisionError> {
    verify_store(trust, anchor_dir)
}

/// Mint both halves and **do not seal or prove the anchor**. See
/// [`verify_store_without_custody_proof`] for why this exists and why nothing shipping may
/// call it.
pub fn mint_store_without_custody_proof(
    app_data_dir: &Path,
    anchor_dir: &Path,
    anchor: Option<&Value>,
) -> Result<Provisioned, ProvisionError> {
    let trust = app_data_dir.join(TRUST_DIR);
    if anchor_dir.join(MANIFEST_FILE).is_file() {
        return verify_store(&trust, anchor_dir);
    }
    refuse_occupied_trust_path(&trust)?;
    let staging = app_data_dir.join(format!(".trust-staging-{}", random_hex(8)?));
    let minted = match mint(&staging, anchor) {
        Ok(minted) => minted,
        Err(e) => {
            let _ = std::fs::remove_dir_all(&staging);
            return Err(e);
        }
    };
    io(std::fs::rename(&staging, &trust), "moving the newly minted trust store into place", &trust)?;
    write_anchor_files(anchor_dir, &trust, &minted)?;
    let mut provisioned = verify_store(&trust, anchor_dir)?;
    provisioned.freshly_minted = true;
    Ok(provisioned)
}
