//! First-launch trust provisioning.
//!
//! # What this is, and what it honestly claims
//!
//! BroPS is a single-user desktop application. The owner installs it and everything
//! must already be done: no ceremony, no USB, no key to carry, no annual renewal,
//! nothing to run by hand, ever. So the trust material the engine's governance chain
//! requires — an operator-root keypair, the six other authority keypairs, the
//! operator-signed `trusted-key-registry`, the out-of-registry operator-root pin, and
//! the operator-signed artifacts the residual engine items name — is **minted on the
//! user's own machine, on first launch, by this module**.
//!
//! ## The posture, stated plainly (read this before trusting anything below)
//!
//! Trust material minted on the user's machine at install time protects against an
//! attacker who arrives **later**. It does **not** protect against one who already
//! owns the machine at install time — that attacker witnesses the mint, or performs
//! it. This is the normal, honest posture for locally-minted trust material: an SSH
//! host key works exactly the same way, and so does a TLS private key generated by an
//! installer. Everything downstream inherits that boundary:
//!
//! * The operator-root **private** key lives on the same disk as the process that
//!   uses it, under the same user account. `engine/runtime/bro_signature.py` calls
//!   this out by name — an anchor its reader can rewrite is not an anchor — and
//!   refuses such a pin unless the deployment sets
//!   `BRO_OPERATOR_ROOT_PIN_SELF_OWNED=acknowledged`. This deployment genuinely has
//!   no second principal to offer, so that is what it must set, which does not make
//!   the anchor stronger: it makes the weakness explicit and reportable instead of
//!   silent.
//! * Consequently the chain proves **integrity over time on one machine** (nothing was
//!   swapped after install; a registry cannot be replayed below its floor; a builder
//!   key cannot sign a verifier receipt), not **provenance from a vendor**. No claim
//!   of the second kind may be made on the strength of this module.
//!
//! `POSTURE.txt`, written beside the trust store, says the same thing to whoever finds
//! the directory without this source in front of them.
//!
//! # Properties
//!
//! * **Idempotent.** A second launch VERIFIES what is on disk and returns; it never
//!   re-mints over a working install. See [`verify_existing`].
//! * **Never half-provisioned.** The mint happens in a staging directory that is
//!   renamed into place as the last step. A failure anywhere removes the staging
//!   directory and returns an error naming what failed; a rename that loses a race
//!   against a concurrent instance falls back to verification.
//! * **Byte-compatible with the Python verifier.** Every signature is Ed25519 over
//!   [`canonical::canonical_bytes`], which reproduces `bro_signature.canonical_bytes`
//!   exactly. Proven by `tests/python_verifier.rs`, which runs the REAL
//!   `bro_signature` / `bro_deploy_preflight` against the REAL output of this module.
//! * **Cross-platform**, with the platform difference reported rather than skipped:
//!   see [`Protection`].

pub mod canonical;

/// The Windows **second principal** for the audit-head anchor (O-2).
///
/// Additive and self-contained: nothing in this module runs unless a caller asks for it,
/// and the POSIX provisioning path above is untouched. See the module docs for the design,
/// the rejected alternatives, and the exact elevation the installer needs.
pub mod audit_signer;

use std::collections::BTreeMap;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use canonical::{canonical_bytes, NonCanonical};
use ed25519_dalek::{Signature, Signer, SigningKey, Verifier, VerifyingKey};
use serde_json::{json, Map, Value};
use sha2::{Digest, Sha256};

// ---------------------------------------------------------------------------
// The engine's tables, mirrored — and drift-tested against the real ones
// ---------------------------------------------------------------------------

/// `bro_signature.AUTHORITY_TYPES`. One keypair is minted per entry.
///
/// This is a mirror of a Python constant, so it can drift. It does not drift
/// silently: `tests/verify_provisioning.py` imports the REAL `bro_signature` and
/// fails if the set of authorities in the minted registry is not exactly
/// `AUTHORITY_TYPES`, or if any key's `allowed_artifact_types` is not exactly what
/// the REAL `ARTIFACT_AUTHORITY` binds to that authority.
pub const AUTHORITY_TYPES: [&str; 7] = [
    "builder",
    "evidence-recorder",
    "issuer",
    "operator-root",
    "recovery",
    "release",
    "verifier",
];

/// `bro_signature.ARTIFACT_AUTHORITY` — artifact type -> the authority that may sign it.
pub const ARTIFACT_AUTHORITY: [(&str, &str); 17] = [
    ("agent-profile", "issuer"),
    ("completion-manifest", "builder"),
    ("conductor-session", "operator-root"),
    ("control-room-command", "operator-root"),
    ("evidence-event", "evidence-recorder"),
    ("evidence-floor-anchor", "operator-root"),
    ("evidence-head", "evidence-recorder"),
    ("execution-lease", "issuer"),
    ("mode-grant", "issuer"),
    ("protected-authority", "operator-root"),
    ("recovery-proof", "recovery"),
    ("recovery-record", "issuer"),
    ("release-grant", "release"),
    ("task-contract", "issuer"),
    ("trusted-key-registry", "operator-root"),
    ("verifier-receipt", "verifier"),
    ("workspace-binding", "operator-root"),
];

pub const OPERATOR: &str = "operator-root";
pub const BUILDER: &str = "builder";
pub const VERIFIER: &str = "verifier";

/// `engine/runtime/bro_policy.py`: `CANONICAL_CONDUCTOR_ID` / `CONDUCTOR_ROLE`.
pub const CONDUCTOR_AGENT_ID: &str = "bro-000";
pub const CONDUCTOR_ROLE: &str = "bro";

/// The agent identity the builder key speaks for.
///
/// `bro_completion._require_signer_identity` refuses a builder/verifier signature
/// whose key carries no `subject_agent_id`, and `bro_deploy_preflight.check_registry`
/// makes an unbound builder/verifier key a RED deployment posture. The two must differ
/// or "builder != verifier" becomes a string comparison one key satisfies on both
/// sides. The form is the one every engine schema requires: `^agt-p[0-9]{2,}-r[0-9]{2,}$`.
pub const BUILDER_AGENT_ID: &str = "agt-p01-r01";
pub const VERIFIER_AGENT_ID: &str = "agt-p01-r02";

// ---------------------------------------------------------------------------
// Expiry
// ---------------------------------------------------------------------------

/// The `not_after_epoch` / `expires_at_epoch` every key and artifact this module mints
/// carries: 9999-12-31T23:59:59Z.
///
/// **The decision.** `broctl`'s `DEFAULT_VALIDITY_SECONDS` is one year, which is right
/// for a fleet whose operator re-signs a registry on a schedule and wrong here: this
/// product has no operator other than the person who installed it, and a desktop app
/// that stops working after a year until its owner "renews" something is exactly the
/// ceremony this design forbids. So validity is unbounded in the only way the schema
/// allows — `not_after_epoch` must be an int, so it is set to a date no clock reaches.
///
/// **What it costs.** Expiry can never be the mechanism that retires a compromised
/// key. Retirement has to come from re-minting the registry with that key marked
/// `revoked` and raising [`REGISTRY_VERSION`], which the anti-rollback floor
/// (`BRO_OPERATOR_REGISTRY_MIN_FILE`, written by this module) then makes stick — a
/// superseded but still operator-signed registry replayed from a backup is refused.
/// On a machine whose owner is the attacker, both the re-mint and the floor are
/// rewritable, which is the boundary stated at the top of this module and not a
/// property a one-year expiry would have restored.
pub const NEVER_EXPIRES_EPOCH: i64 = 253_402_300_799;

/// `not_before_epoch` for every minted key: the epoch.
///
/// Not "now". `verify_artifact` refuses a key whose `not_before_epoch` is in the
/// future, so stamping the install moment turns any backwards clock correction — a
/// machine that was ahead at install and got fixed by NTP an hour later — into a
/// governance chain that refuses everything until the clock catches up, with nothing
/// the user could do about it. A start-of-validity bound buys nothing here anyway:
/// the registry that introduces the key is itself the moment the key becomes real.
pub const NOT_BEFORE_EPOCH: i64 = 0;

/// The version stamped into the registry payload and written to the anti-rollback
/// floor file. A re-mint (revocation, added authority) must raise both together.
pub const REGISTRY_VERSION: i64 = 1;

// ---------------------------------------------------------------------------
// Layout
// ---------------------------------------------------------------------------

/// Everything this module writes lives under `<app_data_dir>/trust`.
pub const TRUST_DIR: &str = "trust";
/// The record of what was minted; its presence is what makes provisioning idempotent.
pub const MANIFEST_FILE: &str = "PROVISIONING.json";
/// The posture statement, for whoever finds this directory without the source.
pub const POSTURE_FILE: &str = "POSTURE.txt";
/// Private key material, one file per authority.
pub const KEYS_DIR: &str = "keys";
/// The registry ROOT: `bro_signature.load_trusted_keys` reads `<root>/config/trusted-keys.json`.
pub const REGISTRY_ROOT_DIR: &str = "registry";
/// Relative to the registry root. `bro_signature.REGISTRY_REL`.
pub const REGISTRY_REL: &str = "config/trusted-keys.json";
/// The out-of-registry pins. Deliberately a SIBLING of the registry root, never inside
/// it: `bro_signature._pin_from_file` refuses a pin lexically inside the root it
/// anchors, because a root-controlled path must not be able to select its own anchor.
pub const PIN_DIR: &str = "pin";
pub const OPERATOR_PIN_FILE: &str = "operator-root.pub";
pub const REGISTRY_FLOOR_FILE: &str = "registry-min";
/// Operator-signed artifacts.
pub const ARTIFACTS_DIR: &str = "artifacts";
pub const CONDUCTOR_SESSION_FILE: &str = "conductor-session.json";

pub const SCHEMA: i64 = 1;

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

#[derive(Debug)]
pub enum ProvisionError {
    Io { what: String, path: PathBuf, source: std::io::Error },
    Canonical(NonCanonical),
    /// The trust store on disk is present but does not verify. Never repaired and
    /// never re-minted over: a store that fails verification is either damaged or
    /// tampered with, and silently replacing it destroys the evidence of which.
    Corrupt { what: String, detail: String },
    /// This platform cannot do something the posture requires. Fails closed.
    Unsupported { platform: String, what: String },
}

impl std::fmt::Display for ProvisionError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ProvisionError::Io { what, path, source } => {
                write!(f, "trust provisioning failed while {what} ({}): {source}", path.display())
            }
            ProvisionError::Canonical(e) => write!(f, "trust provisioning failed: {e}"),
            ProvisionError::Corrupt { what, detail } => write!(
                f,
                "the provisioned trust store is not usable — {what}: {detail}. Nothing was \
                 changed or deleted. Move or remove the `trust` directory in the application \
                 data directory to have it re-minted from scratch."
            ),
            ProvisionError::Unsupported { platform, what } => {
                write!(f, "trust provisioning refuses to continue on {platform}: {what}")
            }
        }
    }
}

impl std::error::Error for ProvisionError {}

impl From<NonCanonical> for ProvisionError {
    fn from(e: NonCanonical) -> Self {
        ProvisionError::Canonical(e)
    }
}

fn io<T>(r: std::io::Result<T>, what: &str, path: &Path) -> Result<T, ProvisionError> {
    r.map_err(|source| ProvisionError::Io {
        what: what.to_string(),
        path: path.to_path_buf(),
        source,
    })
}

fn corrupt<T>(what: &str, detail: impl Into<String>) -> Result<T, ProvisionError> {
    Err(ProvisionError::Corrupt { what: what.to_string(), detail: detail.into() })
}

// ---------------------------------------------------------------------------
// Permissions — the existing per-OS routines, and what they honestly do
// ---------------------------------------------------------------------------

/// What was actually done to restrict access, per platform. Reported rather than
/// assumed, because the honest answer differs by platform and a caller that printed
/// "owner only" everywhere would be making a claim this code cannot support off unix.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Protection {
    /// POSIX: an explicit `chmod` to the stated mode.
    PosixMode(u32),
    /// Everywhere else: whatever the containing directory grants. On Windows the app
    /// data directory is per-user by default ACL, so key material is not world
    /// readable — but no explicit ACL was applied by this process, and this value says
    /// so instead of implying one was.
    InheritedFromParent { platform: &'static str },
}

impl std::fmt::Display for Protection {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Protection::PosixMode(m) => write!(f, "posix: chmod {m:04o} applied by this process"),
            Protection::InheritedFromParent { platform } => write!(
                f,
                "{platform}: NO explicit permission was applied by this process — \
                 `secure_data_dir`/`secure_owner_only_file` have no non-unix branch, so key \
                 material carries the access control the application data directory grants it \
                 (per-user by default on Windows, plus SYSTEM and Administrators)"
            ),
        }
    }
}

/// Restrict a directory to the owner (0700).
///
/// This is the routine `apps/desktop/src-tauri/src/lib.rs` has always called before
/// opening the database; it lives here so there is exactly one copy and both the host
/// and the provisioner use it.
#[cfg(unix)]
pub fn secure_data_dir(dir: &Path) -> std::io::Result<()> {
    use std::os::unix::fs::PermissionsExt;
    std::fs::set_permissions(dir, std::fs::Permissions::from_mode(0o700))
}
#[cfg(not(unix))]
pub fn secure_data_dir(_dir: &Path) -> std::io::Result<()> {
    Ok(())
}

/// Restrict a single file to the owner (0600). Same per-OS shape as
/// [`secure_data_dir`]; the host's `secure_db_files` calls this too, so the database
/// sidecars and the private keys are restricted by one implementation.
#[cfg(unix)]
pub fn secure_owner_only_file(path: &Path) -> std::io::Result<()> {
    use std::os::unix::fs::PermissionsExt;
    std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o600))
}
#[cfg(not(unix))]
pub fn secure_owner_only_file(_path: &Path) -> std::io::Result<()> {
    Ok(())
}

pub fn directory_protection() -> Protection {
    if cfg!(unix) {
        Protection::PosixMode(0o700)
    } else {
        Protection::InheritedFromParent { platform: platform_name() }
    }
}

pub fn key_file_protection() -> Protection {
    if cfg!(unix) {
        Protection::PosixMode(0o600)
    } else {
        Protection::InheritedFromParent { platform: platform_name() }
    }
}

pub fn platform_name() -> &'static str {
    if cfg!(target_os = "windows") {
        "windows"
    } else if cfg!(target_os = "macos") {
        "macos"
    } else if cfg!(target_os = "linux") {
        "linux"
    } else if cfg!(unix) {
        "unix"
    } else {
        "unknown"
    }
}

// ---------------------------------------------------------------------------
// Small helpers
// ---------------------------------------------------------------------------

pub fn hex(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push(char::from_digit((b >> 4) as u32, 16).unwrap());
        s.push(char::from_digit((b & 0x0f) as u32, 16).unwrap());
    }
    s
}

pub fn unhex(s: &str) -> Option<Vec<u8>> {
    if s.len() % 2 != 0 {
        return None;
    }
    let mut out = Vec::with_capacity(s.len() / 2);
    for pair in s.as_bytes().chunks(2) {
        let hi = (pair[0] as char).to_digit(16)?;
        let lo = (pair[1] as char).to_digit(16)?;
        out.push((hi * 16 + lo) as u8);
    }
    Some(out)
}

pub fn sha256_hex(bytes: &[u8]) -> String {
    hex(&Sha256::digest(bytes))
}

fn now_epoch() -> i64 {
    SystemTime::now().duration_since(UNIX_EPOCH).map(|d| d.as_secs() as i64).unwrap_or(0)
}

fn random_hex(bytes: usize) -> Result<String, ProvisionError> {
    let mut buf = vec![0u8; bytes];
    getrandom::getrandom(&mut buf).map_err(|e| ProvisionError::Unsupported {
        platform: platform_name().to_string(),
        what: format!("the OS CSPRNG is unavailable, so no key material can be minted: {e}"),
    })?;
    Ok(hex(&buf))
}

/// Every artifact type the engine binds to `authority`, sorted — the same set
/// `broctl._artifacts_for` computes from `ARTIFACT_AUTHORITY`.
pub fn artifacts_for(authority: &str) -> Vec<String> {
    let mut v: Vec<String> = ARTIFACT_AUTHORITY
        .iter()
        .filter(|(_, a)| *a == authority)
        .map(|(t, _)| t.to_string())
        .collect();
    v.sort();
    v
}

fn subject_agent_id(authority: &str) -> Option<&'static str> {
    match authority {
        BUILDER => Some(BUILDER_AGENT_ID),
        VERIFIER => Some(VERIFIER_AGENT_ID),
        _ => None,
    }
}

// ---------------------------------------------------------------------------
// Signing
// ---------------------------------------------------------------------------

/// Sign `payload` and wrap it as the `{payload, signature}` document every
/// `bro_signature` verifier accepts. The signature is Ed25519 over
/// [`canonical_bytes`] of the payload, hex-encoded exactly as `broctl.sign_payload`
/// writes it (`private.sign(canonical_bytes(payload)).hex()`).
pub fn sign_document(key: &SigningKey, payload: Value) -> Result<Value, ProvisionError> {
    let bytes = canonical_bytes(&payload)?;
    let signature = key.sign(&bytes);
    Ok(json!({"payload": payload, "signature": hex(&signature.to_bytes())}))
}

/// The Rust half of `bro_signature.verify_detached`, used only to re-check this
/// module's own output on a later launch.
fn verify_document(document: &Value, public_key_hex: &str) -> Result<Value, ProvisionError> {
    let payload = match document.get("payload") {
        Some(p) => p.clone(),
        None => return corrupt("a signed document has no payload", "missing `payload`"),
    };
    let sig_hex = match document.get("signature").and_then(|s| s.as_str()) {
        Some(s) => s,
        None => return corrupt("a signed document has no signature", "missing `signature`"),
    };
    let raw_key: [u8; 32] = match unhex(public_key_hex).map(<[u8; 32]>::try_from) {
        Some(Ok(k)) => k,
        _ => {
            return corrupt(
                "the operator-root public key is unusable",
                format!("expected 64 hex characters, got {public_key_hex:?}"),
            )
        }
    };
    let vk = match VerifyingKey::from_bytes(&raw_key) {
        Ok(k) => k,
        Err(e) => return corrupt("the operator-root public key is unusable", e.to_string()),
    };
    let raw_sig: [u8; 64] = match unhex(sig_hex).map(<[u8; 64]>::try_from) {
        Some(Ok(s)) => s,
        _ => {
            return corrupt(
                "a signature is malformed",
                format!("expected 128 hex characters, got {} characters", sig_hex.len()),
            )
        }
    };
    let sig = Signature::from_bytes(&raw_sig);
    let bytes = canonical_bytes(&payload)?;
    match vk.verify(&bytes, &sig) {
        Ok(()) => Ok(payload),
        Err(e) => {
            corrupt("a signature does not verify against the operator-root pin", e.to_string())
        }
    }
}

// ---------------------------------------------------------------------------
// Key material
// ---------------------------------------------------------------------------

/// One authority's keypair, in the on-disk form `broctl sign --key` also reads
/// (`private_key` is the raw 32-byte Ed25519 seed as hex — the same bytes
/// `Ed25519PrivateKey.private_bytes_raw()` produces on the Python side).
pub struct AuthorityKey {
    pub authority_type: String,
    pub key_id: String,
    pub signing: SigningKey,
}

impl AuthorityKey {
    pub fn public_key_hex(&self) -> String {
        hex(self.signing.verifying_key().as_bytes())
    }

    fn to_json(&self) -> Value {
        let mut value = json!({
            "key_id": self.key_id,
            "authority_type": self.authority_type,
            "private_key": hex(self.signing.as_bytes()),
            "public_key": self.public_key_hex(),
            "production": true,
            "provenance": "minted on this machine at first launch; see POSTURE.txt",
        });
        if let Some(subject) = subject_agent_id(&self.authority_type) {
            value.as_object_mut().unwrap().insert("subject_agent_id".into(), json!(subject));
        }
        value
    }
}

fn mint_key(authority: &str, install_id: &str) -> Result<AuthorityKey, ProvisionError> {
    let seed_hex = random_hex(32)?;
    let seed: [u8; 32] = unhex(&seed_hex).expect("hex round-trip").try_into().expect("32 bytes");
    Ok(AuthorityKey {
        authority_type: authority.to_string(),
        key_id: format!("brops-{install_id}-{authority}"),
        signing: SigningKey::from_bytes(&seed),
    })
}

// ---------------------------------------------------------------------------
// The registry
// ---------------------------------------------------------------------------

fn registry_payload(keys: &[AuthorityKey], operator: &AuthorityKey, now: i64) -> Value {
    let mut entries: Vec<Value> = keys
        .iter()
        .map(|key| {
            let mut entry = Map::new();
            entry.insert("key_id".into(), json!(key.key_id));
            entry.insert("public_key".into(), json!(key.public_key_hex()));
            entry.insert("authority_type".into(), json!(key.authority_type));
            entry.insert(
                "allowed_artifact_types".into(),
                json!(artifacts_for(&key.authority_type)),
            );
            entry.insert("not_before_epoch".into(), json!(NOT_BEFORE_EPOCH));
            entry.insert("not_after_epoch".into(), json!(NEVER_EXPIRES_EPOCH));
            entry.insert("status".into(), json!("active"));
            entry.insert("issued_by".into(), json!(operator.key_id));
            if let Some(subject) = subject_agent_id(&key.authority_type) {
                entry.insert("subject_agent_id".into(), json!(subject));
            }
            Value::Object(entry)
        })
        .collect();
    entries.sort_by(|a, b| {
        a["key_id"].as_str().unwrap_or("").cmp(b["key_id"].as_str().unwrap_or(""))
    });

    json!({
        "schema": SCHEMA,
        "artifact_type": "trusted-key-registry",
        "operator_public_key": operator.public_key_hex(),
        "issued_at_epoch": now,
        "registry_version": REGISTRY_VERSION,
        // `load_trusted_keys` refuses a registry that is not marked production whenever
        // the operator pin comes from the production `BRO_OPERATOR_ROOT_PUBKEY_FILE`
        // path, which is the only pin path this deployment has. The marking is true in
        // the sense that check is about — these are not `broctl` development keys shared
        // out of a repository — and not in the sense a fleet operator would mean: the
        // private halves live on this machine. `provenance` and `posture` say which, in
        // the signed payload itself, so no reader has to infer it.
        "production": true,
        "provenance": "locally-minted-at-install",
        "posture": POSTURE_SUMMARY,
        "keys": entries,
    })
}

// ---------------------------------------------------------------------------
// Operator-signed artifacts
// ---------------------------------------------------------------------------

/// The **O-3** artifact: `engine/runtime/bro_policy.py`'s `conductor-session`.
///
/// `verify_conductor_session_token` requires a document that verifies as a
/// `conductor-session` against the registry AND binds `session_id`, `agent_id` and
/// `role` to the running state, with an integer `expires_at_epoch` in the future.
/// The session id is install-scoped rather than per-run: the harness reads it from
/// `BRO_SESSION_ID`, this deployment is the thing that would set it, and a per-run
/// token would mean using the operator-root private key on every launch to buy a
/// rotation whose only threat model is an attacker who already holds that key.
pub fn conductor_session_payload(operator_key_id: &str, session_id: &str, now: i64) -> Value {
    json!({
        "schema": SCHEMA,
        "artifact_type": "conductor-session",
        "key_id": operator_key_id,
        "session_id": session_id,
        "agent_id": CONDUCTOR_AGENT_ID,
        "role": CONDUCTOR_ROLE,
        "issued_at_epoch": now,
        "expires_at_epoch": NEVER_EXPIRES_EPOCH,
    })
}

/// The **O-5** artifact: `bro_completion._signed_floor_anchor`'s `evidence-floor-anchor`.
///
/// **Deliberately not minted at install, and deliberately not minted automatically.**
/// The anchor answers one question — "was this task's evidence floor wiped, or is this
/// the first time we have seen the task?" — and it only answers it because a principal
/// outside the policed process states the high-water mark. At install no task exists,
/// so there is nothing to state; and an anchor this application minted by reading the
/// very store the check polices would restate the store's own claim under a signature,
/// which is worse than no anchor because it looks like corroboration. It is exposed as
/// a function so a lost floor can be re-established deliberately, for a named task and
/// a chosen sequence — never as a startup side effect.
pub fn mint_floor_anchor(
    trust_dir: &Path,
    task_id: &str,
    head_sequence: i64,
    out: &Path,
) -> Result<Value, ProvisionError> {
    if head_sequence < 1 {
        return corrupt(
            "an evidence-floor-anchor needs a positive head_sequence",
            format!("got {head_sequence}"),
        );
    }
    let operator = load_key(trust_dir, OPERATOR)?;
    let payload = json!({
        "schema": SCHEMA,
        "artifact_type": "evidence-floor-anchor",
        "key_id": operator.key_id,
        "task_id": task_id,
        "head_sequence": head_sequence,
        "issued_at_epoch": now_epoch(),
    });
    let document = sign_document(&operator.signing, payload)?;
    write_json(out, &document)?;
    Ok(document)
}

/// Read one authority's private key back off disk.
pub fn load_key(trust_dir: &Path, authority: &str) -> Result<AuthorityKey, ProvisionError> {
    let path = trust_dir.join(KEYS_DIR).join(format!("{authority}.json"));
    let raw = io(std::fs::read(&path), "reading a private key", &path)?;
    let value: Value = match serde_json::from_slice(&raw) {
        Ok(v) => v,
        Err(e) => return corrupt("a private key file is not JSON", e.to_string()),
    };
    let key_id = match value.get("key_id").and_then(|v| v.as_str()) {
        Some(s) => s.to_string(),
        None => return corrupt("a private key file has no key_id", path.display().to_string()),
    };
    let seed: [u8; 32] =
        match value.get("private_key").and_then(|v| v.as_str()).and_then(unhex).map(<[u8; 32]>::try_from)
        {
            Some(Ok(s)) => s,
            _ => {
                return corrupt(
                    "a private key file has no usable 32-byte seed",
                    path.display().to_string(),
                )
            }
        };
    Ok(AuthorityKey {
        authority_type: authority.to_string(),
        key_id,
        signing: SigningKey::from_bytes(&seed),
    })
}

// ---------------------------------------------------------------------------
// Writing
// ---------------------------------------------------------------------------

fn write_bytes(path: &Path, bytes: &[u8]) -> Result<(), ProvisionError> {
    if let Some(parent) = path.parent() {
        io(std::fs::create_dir_all(parent), "creating a directory", parent)?;
    }
    let mut file = io(std::fs::File::create(path), "creating a file", path)?;
    io(file.write_all(bytes), "writing a file", path)?;
    io(file.sync_all(), "flushing a file", path)?;
    Ok(())
}

fn write_json(path: &Path, value: &Value) -> Result<(), ProvisionError> {
    let mut bytes = canonical_bytes(value)?;
    bytes.push(b'\n');
    write_bytes(path, &bytes)
}

/// Key material only: created with an owner-only mode where the platform has one, then
/// restricted again through [`secure_owner_only_file`] because the creation mode is
/// masked by the process umask. `create_new` refuses to clobber an existing key file —
/// silently replacing a signing key is a rotation, and rotations must never be
/// accidental (the rule `broctl._write_key` states).
fn write_key_file(path: &Path, value: &Value) -> Result<(), ProvisionError> {
    let mut bytes = canonical_bytes(value)?;
    bytes.push(b'\n');
    if let Some(parent) = path.parent() {
        io(std::fs::create_dir_all(parent), "creating the key directory", parent)?;
    }
    let mut options = std::fs::OpenOptions::new();
    options.write(true).create_new(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        options.mode(0o600);
    }
    let mut file = io(options.open(path), "creating a private key file", path)?;
    io(file.write_all(&bytes), "writing a private key file", path)?;
    io(file.sync_all(), "flushing a private key file", path)?;
    drop(file);
    io(secure_owner_only_file(path), "restricting a private key file to its owner", path)?;
    Ok(())
}

// ---------------------------------------------------------------------------
// The result
// ---------------------------------------------------------------------------

#[derive(Debug, Clone)]
pub struct Provisioned {
    pub trust_dir: PathBuf,
    /// Pass this as `root` to `bro_signature.load_trusted_keys`.
    pub registry_root: PathBuf,
    pub registry_path: PathBuf,
    pub operator_pin_path: PathBuf,
    pub registry_floor_path: PathBuf,
    pub conductor_session_path: PathBuf,
    pub keys_dir: PathBuf,
    pub install_id: String,
    pub session_id: String,
    pub operator_key_id: String,
    pub operator_public_key: String,
    /// True when THIS call minted the store; false when it verified an existing one.
    pub freshly_minted: bool,
    pub dir_protection: Protection,
    pub key_file_protection: Protection,
}

impl Provisioned {
    /// The environment a deployment must export for the engine to USE what was minted.
    ///
    /// Returned rather than applied. Two of these change how the engine resolves its
    /// trust root process-wide, and `bro_signature` hard-fails when a file pin and a
    /// raw CI pin disagree — so which process gets them, and when, is a deployment
    /// decision, not this module's to make silently at startup.
    pub fn engine_env(&self) -> Vec<(&'static str, String)> {
        vec![
            ("BRO_OPERATOR_ROOT_PUBKEY_FILE", self.operator_pin_path.display().to_string()),
            ("BRO_OPERATOR_REGISTRY_MIN_FILE", self.registry_floor_path.display().to_string()),
            // The anchor and the floor both live under an account this process can
            // write. `bro_signature`/`bro_custody` refuse exactly that unless the
            // deployment says out loud that it has no second principal to offer.
            ("BRO_OPERATOR_ROOT_PIN_SELF_OWNED", "acknowledged".to_string()),
            ("BRO_CONDUCTOR_SESSION_TOKEN", self.conductor_session_path.display().to_string()),
            ("BRO_SESSION_ID", self.session_id.clone()),
        ]
    }
}

// ---------------------------------------------------------------------------
// Provisioning
// ---------------------------------------------------------------------------

/// Mint the trust store on first launch, or verify the one that is already there.
///
/// Call this immediately after `secure_data_dir(&app_data_dir)` and before the
/// database is opened. An `Err` must abort startup: a half-trusted governance chain is
/// worse than an absent one, so there is no degraded mode to fall back to.
pub fn provision(app_data_dir: &Path) -> Result<Provisioned, ProvisionError> {
    let trust = app_data_dir.join(TRUST_DIR);
    if trust.join(MANIFEST_FILE).is_file() {
        return verify_existing(&trust);
    }
    // Something is at the trust path but it is not a provisioned store. Refuse rather
    // than mint over it. This is also where the two platforms would otherwise differ:
    // `std::fs::rename` on Windows carries `MOVEFILE_REPLACE_EXISTING`, so renaming the
    // staging directory over an existing FILE succeeds there and fails with ENOTDIR on
    // unix. Deciding here, before anything is minted, makes the behaviour the same
    // everywhere and the refusal explicit.
    if trust.exists() {
        return corrupt(
            "the trust path already holds something that is not a provisioned store",
            format!(
                "{} exists but has no {MANIFEST_FILE}. It is either a half-removed store or a \
                 directory something else owns, and minting over it would destroy whichever it is",
                trust.display()
            ),
        );
    }

    // Mint into a staging directory and rename it into place as the last step, so the
    // trust directory only ever exists complete. A failure in between removes the
    // staging directory and leaves nothing behind.
    let staging = app_data_dir.join(format!(".trust-staging-{}", random_hex(8)?));
    if let Err(e) = mint(&staging) {
        let _ = std::fs::remove_dir_all(&staging);
        return Err(e);
    }
    if let Err(source) = std::fs::rename(&staging, &trust) {
        let _ = std::fs::remove_dir_all(&staging);
        // A concurrent first launch may have won the race and put a complete store
        // there. That is a success, not a failure — verify theirs.
        if trust.join(MANIFEST_FILE).is_file() {
            return verify_existing(&trust);
        }
        return Err(ProvisionError::Io {
            what: "moving the newly minted trust store into place".into(),
            path: trust,
            source,
        });
    }

    // Verify what we just wrote through exactly the same code a later launch uses. A
    // mint that produces something the verifier rejects must not survive, so this is
    // the one case where an existing store IS removed: this call created it.
    match verify_existing(&trust) {
        Ok(mut provisioned) => {
            provisioned.freshly_minted = true;
            Ok(provisioned)
        }
        Err(e) => {
            let _ = std::fs::remove_dir_all(&trust);
            Err(e)
        }
    }
}

/// Every file the mint writes, relative to the trust directory, in manifest order.
fn provisioned_files() -> Vec<String> {
    let mut relatives: Vec<String> =
        AUTHORITY_TYPES.iter().map(|a| format!("{KEYS_DIR}/{a}.json")).collect();
    relatives.push(format!("{REGISTRY_ROOT_DIR}/{REGISTRY_REL}"));
    relatives.push(format!("{PIN_DIR}/{OPERATOR_PIN_FILE}"));
    relatives.push(format!("{PIN_DIR}/{REGISTRY_FLOOR_FILE}"));
    relatives.push(format!("{ARTIFACTS_DIR}/{CONDUCTOR_SESSION_FILE}"));
    relatives.push(POSTURE_FILE.to_string());
    relatives
}

fn under(root: &Path, relative: &str) -> PathBuf {
    let mut path = root.to_path_buf();
    for component in relative.split('/') {
        path.push(component);
    }
    path
}

fn mint(staging: &Path) -> Result<(), ProvisionError> {
    io(std::fs::create_dir_all(staging), "creating the staging directory", staging)?;
    io(secure_data_dir(staging), "restricting the staging directory to its owner", staging)?;

    let install_id = random_hex(8)?;
    let now = now_epoch();

    let mut keys: Vec<AuthorityKey> = Vec::with_capacity(AUTHORITY_TYPES.len());
    for authority in AUTHORITY_TYPES {
        keys.push(mint_key(authority, &install_id)?);
    }
    let operator_index = keys
        .iter()
        .position(|k| k.authority_type == OPERATOR)
        .expect("AUTHORITY_TYPES contains operator-root");

    let keys_dir = staging.join(KEYS_DIR);
    io(std::fs::create_dir_all(&keys_dir), "creating the key directory", &keys_dir)?;
    io(secure_data_dir(&keys_dir), "restricting the key directory to its owner", &keys_dir)?;
    for key in &keys {
        write_key_file(&keys_dir.join(format!("{}.json", key.authority_type)), &key.to_json())?;
    }

    let operator = &keys[operator_index];
    let registry = sign_document(&operator.signing, registry_payload(&keys, operator, now))?;
    write_json(&under(staging, &format!("{REGISTRY_ROOT_DIR}/{REGISTRY_REL}")), &registry)?;

    let pin_dir = staging.join(PIN_DIR);
    io(std::fs::create_dir_all(&pin_dir), "creating the pin directory", &pin_dir)?;
    io(secure_data_dir(&pin_dir), "restricting the pin directory to its owner", &pin_dir)?;
    let pin_path = pin_dir.join(OPERATOR_PIN_FILE);
    write_bytes(&pin_path, format!("{}\n", operator.public_key_hex()).as_bytes())?;
    io(secure_owner_only_file(&pin_path), "restricting the operator pin to its owner", &pin_path)?;
    let floor_path = pin_dir.join(REGISTRY_FLOOR_FILE);
    write_bytes(&floor_path, format!("{REGISTRY_VERSION}\n").as_bytes())?;
    io(
        secure_owner_only_file(&floor_path),
        "restricting the registry anti-rollback floor to its owner",
        &floor_path,
    )?;

    let session_id = format!("brops-{install_id}");
    let session = sign_document(
        &operator.signing,
        conductor_session_payload(&operator.key_id, &session_id, now),
    )?;
    write_json(&staging.join(ARTIFACTS_DIR).join(CONDUCTOR_SESSION_FILE), &session)?;

    write_bytes(&staging.join(POSTURE_FILE), posture_text(&install_id).as_bytes())?;

    // The manifest LAST: its presence is what makes the store "provisioned", and it
    // records the digest of every other file so a later launch verifies rather than
    // assumes. It is not listed in its own `files` map.
    let mut files = BTreeMap::new();
    for relative in provisioned_files() {
        let path = under(staging, &relative);
        let bytes = io(std::fs::read(&path), "hashing a provisioned file", &path)?;
        files.insert(relative, Value::from(sha256_hex(&bytes)));
    }

    let manifest = json!({
        "schema": SCHEMA,
        "install_id": install_id,
        "session_id": session_id,
        "provisioned_at_epoch": now,
        "registry_version": REGISTRY_VERSION,
        "operator_key_id": operator.key_id,
        "operator_public_key": operator.public_key_hex(),
        "not_before_epoch": NOT_BEFORE_EPOCH,
        "not_after_epoch": NEVER_EXPIRES_EPOCH,
        "expiry_policy": "non-expiring by design: this product has no operator but its owner, \
                          so nothing may ever require a renewal. Revocation is a re-mint plus a \
                          registry_version rise, enforced by the anti-rollback floor, not an \
                          expiry date.",
        "platform": platform_name(),
        "directory_protection": directory_protection().to_string(),
        "key_file_protection": key_file_protection().to_string(),
        "posture": POSTURE_SUMMARY,
        "files": files.into_iter().collect::<Map<String, Value>>(),
    });
    write_json(&staging.join(MANIFEST_FILE), &manifest)?;
    Ok(())
}

pub const POSTURE_SUMMARY: &str =
    "trust material minted on the installing user's machine: it protects against an attacker \
     who arrives later, not against one who already owned the machine at install time (the \
     same posture as an SSH host key)";

fn posture_text(install_id: &str) -> String {
    format!(
        "BroPS local trust store (install {install_id})\n\
         =================================================\n\
         \n\
         WHAT THIS IS\n\
         Every key here was generated on this machine the first time BroPS started.\n\
         The operator-root key signs the trusted-key registry under registry/config/,\n\
         and pin/{OPERATOR_PIN_FILE} holds its public half as the out-of-registry trust\n\
         anchor the engine pins from BRO_OPERATOR_ROOT_PUBKEY_FILE.\n\
         \n\
         WHAT IT PROTECTS AGAINST\n\
         An attacker who arrives AFTER installation. From that moment the chain is\n\
         real: the registry cannot be replaced without the operator key, it cannot be\n\
         replayed below the version in pin/{REGISTRY_FLOOR_FILE}, and a builder key\n\
         cannot sign a verifier receipt.\n\
         \n\
         WHAT IT DOES NOT PROTECT AGAINST\n\
         An attacker who already owned this machine when BroPS was installed. They\n\
         witnessed the mint or performed it, and they hold the same private keys this\n\
         process does. This is the normal posture for locally-minted trust material --\n\
         an SSH host key works the same way -- and it is stated here rather than\n\
         implied away. Nothing in this store is evidence of provenance from a vendor.\n\
         \n\
         WHY THE ENGINE IS TOLD TO ACCEPT IT\n\
         The engine refuses a trust anchor the reading account can rewrite, unless the\n\
         deployment sets BRO_OPERATOR_ROOT_PIN_SELF_OWNED=acknowledged. A single-user\n\
         desktop has no second principal to offer, so that is what it must set. That\n\
         does not make the anchor stronger; it makes the weakness explicit.\n\
         \n\
         NOTHING HERE EVER EXPIRES\n\
         Keys carry not_after_epoch = {NEVER_EXPIRES_EPOCH} (9999-12-31Z) so this\n\
         application never asks its owner to renew anything. Retiring a key means\n\
         re-minting the registry with it marked revoked and raising the number in\n\
         pin/{REGISTRY_FLOOR_FILE}.\n\
         \n\
         Deleting this directory makes BroPS mint a new one on the next launch. Every\n\
         artifact signed under the old keys stops verifying.\n"
    )
}

/// Verify a trust store that is already on disk. Never repairs, never re-mints.
pub fn verify_existing(trust: &Path) -> Result<Provisioned, ProvisionError> {
    let manifest_path = trust.join(MANIFEST_FILE);
    let raw =
        io(std::fs::read(&manifest_path), "reading the provisioning manifest", &manifest_path)?;
    let manifest: Value = match serde_json::from_slice(&raw) {
        Ok(v) => v,
        Err(e) => return corrupt("the provisioning manifest is not JSON", e.to_string()),
    };
    if manifest.get("schema").and_then(|v| v.as_i64()) != Some(SCHEMA) {
        return corrupt(
            "the provisioning manifest is not schema 1",
            format!("got {:?}", manifest.get("schema")),
        );
    }

    // 1. Every file the mint recorded is present with the digest it recorded, and the
    //    manifest covers every file the mint is supposed to write (so dropping an entry
    //    cannot smuggle a file past the digest check).
    let files = match manifest.get("files").and_then(|v| v.as_object()) {
        Some(f) if !f.is_empty() => f,
        _ => return corrupt("the provisioning manifest lists no files", "empty `files`"),
    };
    for (relative, expected) in files {
        let path = under(trust, relative);
        let bytes = io(std::fs::read(&path), "re-hashing a provisioned file", &path)?;
        let actual = sha256_hex(&bytes);
        if Some(actual.as_str()) != expected.as_str() {
            return corrupt(
                "a provisioned file no longer matches the digest recorded at install",
                format!("{relative}: recorded {expected}, found {actual}"),
            );
        }
    }
    for relative in provisioned_files() {
        if !files.contains_key(&relative) {
            return corrupt(
                "the provisioning manifest does not cover every provisioned file",
                format!("no digest recorded for {relative}"),
            );
        }
    }

    // 2. The pin file and the registry agree on the operator-root public key.
    let pin_path = trust.join(PIN_DIR).join(OPERATOR_PIN_FILE);
    let pin = io(std::fs::read_to_string(&pin_path), "reading the operator-root pin", &pin_path)?
        .trim()
        .to_string();
    let registry_root = trust.join(REGISTRY_ROOT_DIR);
    let registry_path = under(&registry_root, REGISTRY_REL);
    let registry_raw =
        io(std::fs::read(&registry_path), "reading the trusted-key registry", &registry_path)?;
    let registry: Value = match serde_json::from_slice(&registry_raw) {
        Ok(v) => v,
        Err(e) => return corrupt("the trusted-key registry is not JSON", e.to_string()),
    };

    // 3. The registry verifies under the pin — the same check `load_trusted_keys` runs.
    let payload = verify_document(&registry, &pin)?;
    if payload.get("operator_public_key").and_then(|v| v.as_str()) != Some(pin.as_str()) {
        return corrupt(
            "the registry names an operator key other than the pinned one",
            "payload.operator_public_key != the pinned operator-root public key",
        );
    }
    if payload.get("production").and_then(|v| v.as_bool()) != Some(true) {
        return corrupt(
            "the registry is not marked production",
            "`load_trusted_keys` refuses a non-production registry whenever the pin comes from \
             BRO_OPERATOR_ROOT_PUBKEY_FILE, which is the only pin path this deployment has",
        );
    }

    // 4. Every authority the engine knows has an ACTIVE key, and the registry's
    //    operator-root key is the pinned one (`load_trusted_keys`'s last check).
    let entries = match payload.get("keys").and_then(|v| v.as_array()) {
        Some(k) if !k.is_empty() => k.clone(),
        _ => return corrupt("the registry contains no keys", "empty `keys`"),
    };
    let mut operator_key_id = String::new();
    for authority in AUTHORITY_TYPES {
        let found = entries.iter().find(|e| {
            e.get("authority_type").and_then(|v| v.as_str()) == Some(authority)
                && e.get("status").and_then(|v| v.as_str()) == Some("active")
        });
        let entry = match found {
            Some(entry) => entry,
            None => {
                return corrupt(
                    "the registry has no active key for an authority the engine knows",
                    format!("missing an active {authority} key"),
                )
            }
        };
        if authority == OPERATOR {
            if entry.get("public_key").and_then(|v| v.as_str()) != Some(pin.as_str()) {
                return corrupt(
                    "the registry's operator-root key is not the pinned key",
                    "an operator-signed registry that does not contain its own signer is refused \
                     by `load_trusted_keys`",
                );
            }
            operator_key_id =
                entry.get("key_id").and_then(|v| v.as_str()).unwrap_or_default().to_string();
        }
    }

    // 5. The conductor-session artifact still verifies and still binds what O-3 requires.
    let session_path = trust.join(ARTIFACTS_DIR).join(CONDUCTOR_SESSION_FILE);
    let session_raw =
        io(std::fs::read(&session_path), "reading the conductor-session artifact", &session_path)?;
    let session: Value = match serde_json::from_slice(&session_raw) {
        Ok(v) => v,
        Err(e) => return corrupt("the conductor-session artifact is not JSON", e.to_string()),
    };
    let session_payload = verify_document(&session, &pin)?;
    for (field, expected) in [
        ("artifact_type", "conductor-session"),
        ("agent_id", CONDUCTOR_AGENT_ID),
        ("role", CONDUCTOR_ROLE),
        ("key_id", operator_key_id.as_str()),
    ] {
        if session_payload.get(field).and_then(|v| v.as_str()) != Some(expected) {
            return corrupt(
                "the conductor-session artifact does not bind what the engine checks",
                format!("{field} is {:?}, expected {expected:?}", session_payload.get(field)),
            );
        }
    }
    let session_id = match session_payload.get("session_id").and_then(|v| v.as_str()) {
        Some(s) if !s.is_empty() => s.to_string(),
        _ => return corrupt("the conductor-session artifact carries no session_id", "empty"),
    };
    match session_payload.get("expires_at_epoch").and_then(|v| v.as_i64()) {
        Some(e) if e > now_epoch() => {}
        other => {
            return corrupt(
                "the conductor-session artifact has expired",
                format!(
                    "expires_at_epoch is {other:?}; the engine refuses a token whose expiry is \
                     not an integer in the future"
                ),
            )
        }
    }

    Ok(Provisioned {
        trust_dir: trust.to_path_buf(),
        registry_root,
        registry_path,
        operator_pin_path: pin_path,
        registry_floor_path: trust.join(PIN_DIR).join(REGISTRY_FLOOR_FILE),
        conductor_session_path: session_path,
        keys_dir: trust.join(KEYS_DIR),
        install_id: manifest
            .get("install_id")
            .and_then(|v| v.as_str())
            .unwrap_or_default()
            .to_string(),
        session_id,
        operator_key_id,
        operator_public_key: pin,
        freshly_minted: false,
        dir_protection: directory_protection(),
        key_file_protection: key_file_protection(),
    })
}
