# Windows LIVE governed-turn machine-proof harness (same-account).
#
# Drives, over REAL \\.\pipe\ named pipes across THREE separate Windows processes (challenge-authority /
# governed-supervisor / isolated-signer) plus a driver, one full governed turn, and shows the peer-SID
# trust boundary is fail-closed:
#
#   POSITIVE: driver's peer SID == the provisioned broker SID  -> the chain completes
#   NEGATIVE: a bogus broker SID in the config                 -> blocked (the servers deny the peer SID)
#
# ---------------------------------------------------------------------------------------------------
# WHAT THIS SCRIPT NEEDS, AND WHY IT CANNOT BE SELF-CONTAINED  (remediation audit, R1)
# ---------------------------------------------------------------------------------------------------
# Until this fix, line 30 of this file passed `win_provision` a hardcoded 32-byte seed described as "the
# operator's OFFLINE root private key (proof constant)". It was in fact the DEMONSTRATION root seed from
# win-live/src/proof.rs, whose public half is `tcb::DEMO_ROOT_PUBLIC_KEY_HEX`. `win_provision` compares
# the supplied private against the TCB-pinned PRODUCTION public (`tcb::ROOT_PUBLIC_KEY_HEX`) and exits 3
# when they differ -- so this script could not complete a single run, while it and CROSS_ACCOUNT_PROOF.md
# were both cited as reproducible evidence of a production `trusted_verified`.
#
# It cannot be fixed by embedding a working key: the whole point of the production anchor is that its
# private half lives OFFLINE and never reaches a serving box or a source tree. A checked-in key that
# `win_provision` accepted would BE the compiled-in-demo posture the pinning was introduced to escape.
#
# So this script now REQUIRES the operator to supply the offline material, and FAILS LOUDLY without it.
# It never fabricates a pass. What you must provide:
#
#   -RootKey <path>       A file containing the 64-hex-char ed25519 seed of the root private key whose
#                         public half is pinned in src-tauri/win-live/src/tcb.rs::ROOT_PUBLIC_KEY_HEX.
#                         Generated by `win_gen_root` on an airgapped machine (see CUSTODY_CEREMONY.md)
#                         and normally carried on removable media. Any other key -> win_provision exits 3.
#   -RootProvenance       The custody declaration for that anchor: external | kit_generated |
#                         demonstration. Only `external` can render a production verdict; anything else
#                         completes the chain and reports demonstration custody, honestly.
#   elevated PowerShell   `win_provision` and `win_tcb_pin` set ACLs/owners with icacls.
#
# What this proof does and does NOT establish:
#   * It DOES exercise the real named-pipe transport, the real peer-SID gate (both directions), the real
#     Sec.2.5 TCB integrity floor, and the real crypto chain in three separate processes.
#   * It is SAME-ACCOUNT: all four processes run as the invoking user, so the broker IS the servers'
#     principal. The pipe DACL therefore cannot withhold FILE_CREATE_PIPE_INSTANCE from it (win-live's
#     pipe.rs prints a warning saying so), and no cross-account isolation is demonstrated here.
#   * The host-independent half of the chain (challenge -> lease -> attest -> sign -> verify_and_accept)
#     is proven separately and reproducibly by `cargo test -p brops-win-live`, which needs no Windows.
#
# Requires the workspace built: cargo build -p brops-win-live --bins
param(
  [string]$Dbg  = "$PSScriptRoot\..\..\target\debug",
  [string]$Root = "C:\ProgramData\brops-live-selfproof",
  [string]$RootKey,
  [ValidateSet("external","kit_generated","demonstration")]
  [string]$RootProvenance = "external"
)
$ErrorActionPreference = "Stop"

function Fail-Loudly([string[]]$lines) {
  Write-Host ""
  Write-Host "RESULT: NOT RUN -- this harness cannot proceed." -ForegroundColor Red
  foreach ($l in $lines) { Write-Host "  $l" -ForegroundColor Red }
  Write-Host ""
  exit 3
}

if (-not $RootKey) {
  Fail-Loudly @(
    "-RootKey was not supplied.",
    "",
    "This proof provisions a deployment whose key manifest must be signed by the OFFLINE root private",
    "key matching the TCB-pinned public in src-tauri/win-live/src/tcb.rs (ROOT_PUBLIC_KEY_HEX). That",
    "key is deliberately NOT in this repository and NOT on this machine -- if it were, the pinning would",
    "be worthless.",
    "",
    "To run:  .\win_live_proof.ps1 -RootKey <path to the offline root private seed hex>",
    "",
    "If you do not hold that key, this harness CANNOT produce a production trusted_verified, and no",
    "document should cite it as though it had. The host-independent chain proof that anyone can",
    "reproduce is:  cargo test -p brops-win-live"
  )
}
if (-not (Test-Path -LiteralPath $RootKey)) {
  Fail-Loudly @("-RootKey `"$RootKey`" does not exist.")
}

$bin = Join-Path $Root "bin"
$cfg = Join-Path $Root "config.json"
$pin = Join-Path $Root "tcb-pin.json"
New-Item -ItemType Directory -Force -Path $bin | Out-Null
foreach ($e in "win_provision.exe","win_tcb_pin.exe","win_authority.exe","win_supervisor.exe","win_signer.exe","win_live_turn.exe","win_executor.exe") {
  $src = Join-Path $Dbg $e
  if (-not (Test-Path -LiteralPath $src)) {
    Fail-Loudly @("$e is missing from $Dbg.", "Build first:  cargo build -p brops-win-live --bins")
  }
  try { Copy-Item $src (Join-Path $bin $e) -Force }
  catch { Fail-Loudly @("cannot stage $e into $bin : $_",
                        "A previous run may have left $Root owned/ACL'd by another principal.",
                        "Remove it (elevated) or pass -Root <fresh dir>.") }
}

# The account that will own the three principal seeds. This harness is same-account, so that is the
# invoking user; a cross-account deployment passes three distinct service accounts instead.
$me       = [System.Security.Principal.WindowsIdentity]::GetCurrent()
$mySid    = $me.User.Value
$myAccount = $me.Name

function Invoke-Turn([string]$brokerSid, [string]$prefix, [string]$label) {
  & (Join-Path $bin "win_provision.exe") --root-dir $Root --allowed-broker-sid $brokerSid `
      --executor-path (Join-Path $bin "win_executor.exe") --pipe-prefix $prefix `
      --root-key $RootKey --root-provenance $RootProvenance `
      --challenge-account $myAccount --supervisor-account $myAccount --signer-account $myAccount | Out-Null
  switch ($LASTEXITCODE) {
    0 { }
    3 { Fail-Loudly @(
          "win_provision rejected -RootKey: it does not match the TCB-pinned root public key",
          "(src-tauri/win-live/src/tcb.rs::ROOT_PUBLIC_KEY_HEX).",
          "Supply the offline private half of THAT key -- no other key can sign a manifest this driver accepts."
        ) }
    4 { Fail-Loudly @("win_provision could not apply the seed ACLs. Run this from an ELEVATED PowerShell.") }
    default { Fail-Loudly @("win_provision failed with exit code $LASTEXITCODE.") }
  }

  # Sec.2.5 TCB integrity floor: measure the deployed binaries + steering files BEFORE anything serves.
  # Without this the servers and the driver refuse to start at all (fail-closed, by design).
  & (Join-Path $bin "win_tcb_pin.exe") --root-dir $Root --bin-dir $bin --out $pin | Out-Null
  if ($LASTEXITCODE -ne 0) {
    Fail-Loudly @(
      "win_tcb_pin failed with exit code $LASTEXITCODE.",
      "It must run ELEVATED: it sets the pin manifest's owner to BUILTIN\Administrators and strips",
      "inherited ACEs, because tcb_floor refuses a manifest any other principal could rewrite."
    )
  }

  $a = Start-Process (Join-Path $bin "win_authority.exe")  -ArgumentList "--config",$cfg -PassThru -WindowStyle Hidden
  $s = Start-Process (Join-Path $bin "win_supervisor.exe") -ArgumentList "--config",$cfg -PassThru -WindowStyle Hidden
  $g = Start-Process (Join-Path $bin "win_signer.exe")     -ArgumentList "--config",$cfg -PassThru -WindowStyle Hidden
  Start-Sleep -Milliseconds 900
  # A server that refused the Sec.2.5 floor exits 5; surface that instead of timing out on a dead pipe.
  foreach ($p in @($a,$s,$g)) {
    if ($p.HasExited -and $p.ExitCode -eq 5) {
      Fail-Loudly @("A server refused to start: the Sec.2.5 TCB integrity floor was not satisfied (exit 5).",
                    "Its stderr names the failing artifact.")
    }
  }
  $out = & (Join-Path $bin "win_live_turn.exe") --config $cfg 2>&1 | Out-String
  Stop-Process -Id $a.Id,$s.Id,$g.Id -Force -ErrorAction SilentlyContinue
  Write-Output ("{0}: {1}" -f $label, $out.Trim())
}

Write-Host "NOTE: same-account harness -- all four processes run as $myAccount." -ForegroundColor Yellow
Write-Host "      The broker shares the servers' principal, so no cross-account isolation is shown here." -ForegroundColor Yellow
Invoke-Turn $mySid                         "brops-pos" "POSITIVE (correct broker SID)"
Invoke-Turn "S-1-5-21-0-0-0-9999"          "brops-neg" "NEGATIVE (wrong broker SID)"
