// Phase-6 (Multi-Agent) — renderer-side GOVERNED DISPATCH composer.
//
// What this module is for
// -----------------------
// Before it existed, the Agents/Tasks surfaces could show a roster and a board but had
// no way to hand a task to an agent under the authority contract: there was no dispatch
// at all, governed or otherwise. This module builds the thing that would be dispatched —
// a real, contract-shaped assignment — and attempts to hand it to the engine.
//
// The owner's model, restated as code — and note carefully WHICH half is enforced:
//
//   * The CAPABILITY half is the TIER, and only the tier. `apps/desktop/src-tauri/src/ai.rs`
//     passes the three tiers (`reader`, `runner`, `builder`) to the CLI inline via
//     `--agents`, and that tool list is the only thing that actually bounds what a
//     specialist can do. Bro spawns a TIER.
//   * The 262 pack-role definitions in `.claude/agents/` (generated by
//     `tools/generate_agent_definitions.py` from `engine/packs/registry.json` +
//     `engine/agents/authority-policy.json`) are READ — to decide the specialism and which
//     authority record it falls under — and then Bro spawns the matching tier. A pack role
//     is a REFERENCE, not an enforcement point, and this module must never imply otherwise:
//     `CapabilityGrant.packRole` is explicitly advisory, `CapabilityGrant.tier` is what
//     binds. Painting a pack role as the thing that contains a specialist would be exactly
//     the decorative-authority problem the generated definitions were written to end.
//   * The PATH half is a property of the JOB. It lives in the task contract as `scope` and
//     `prohibited_scope` (`engine/schemas/task-contract.schema.json`).
//
// So one assignment = one enforced tier + one advisory pack-role reference + one contract
// draft (paths, risk, mode, verifier). Bro decides WHO gets WHAT capability at WHICH path.
//
// What this module is NOT
// -----------------------
// It is not the engine, and it never speaks for it.
//
//   1. `validateAssignment` is a PRE-FLIGHT refusal, not an acceptance. It mirrors the
//      engine schema's rules so an obviously-bad draft never leaves the renderer, and it
//      can only ever say NO. A draft with zero problems is "locally well-formed", which is
//      strictly weaker than "the engine accepted it". The UI must never conflate the two.
//   2. The draft is deliberately INCOMPLETE. `engine/schemas/task-contract.schema.json`
//      requires a `repository` block with `base_commit` (40 hex) and `tree_identity`
//      (64 hex). Those are host facts about a real git worktree; the desktop has no IPC
//      that can observe them and MUST NOT invent them. The engine seals that block at
//      dispatch time and echoes it back — see `RepositoryBinding` and `DISPATCH_REQUIREMENT`.
//   3. Only a well-formed `accepted` reply from the backend is ever reported as accepted.
//      Every other reply — malformed, unknown, thrown, absent command, no Tauri runtime —
//      degrades to `refused` or `unreachable`. There is no path from a missing backend to
//      a green state.
//
// Today no such backend command exists (`apps/desktop/src-tauri` registers no dispatch
// command), so a real attempt resolves to `unreachable` with the transport's own reason.
// That is the honest outcome and the surface says exactly that instead of pretending.

import { hasBackend } from './desktop';

// ─────────────────────────────────────────────────────────────────────────────
// 1. Contract vocabulary — mirrored from engine/schemas/task-contract.schema.json
// ─────────────────────────────────────────────────────────────────────────────

/** `schema` const in the task-contract schema. */
export const CONTRACT_SCHEMA_VERSION = 1;
/** The single normative source these rules mirror. Quoted in the UI so a reader can check. */
export const CONTRACT_SCHEMA_SOURCE = 'engine/schemas/task-contract.schema.json';
/** The authority record source. */
export const AUTHORITY_POLICY_SOURCE = 'engine/agents/authority-policy.json';
/** Where the capability half of a grant is declared. */
export const AGENT_DEFINITION_DIR = '.claude/agents';

export const MODES = ['review', 'work', 'release'] as const;
export type Mode = (typeof MODES)[number];

export const RISKS = ['low', 'medium', 'high', 'critical'] as const;
export type Risk = (typeof RISKS)[number];

/** Rank of a risk level, in the order `authority-policy.json.risk_order` declares. */
export function riskRank(r: Risk): number {
  return RISKS.indexOf(r);
}

// ─────────────────────────────────────────────────────────────────────────────
// 2. Capability tiers — mirrored from tools/generate_agent_definitions.py TIERS
// ─────────────────────────────────────────────────────────────────────────────

export const CAPABILITY_TIERS = ['reader', 'runner', 'builder'] as const;
export type CapabilityTier = (typeof CAPABILITY_TIERS)[number];

/** The exact tool list each tier's generated definition declares. */
export const TIER_TOOLS: Record<CapabilityTier, readonly string[]> = {
  reader: ['Read', 'Grep', 'Glob'],
  runner: ['Read', 'Grep', 'Glob', 'Bash'],
  builder: ['Read', 'Edit', 'Write', 'Grep', 'Glob', 'Bash'],
};

/** Can the tier CHANGE files? Only `builder` can. */
export const TIER_CAN_WRITE: Record<CapabilityTier, boolean> = {
  reader: false, runner: false, builder: true,
};
/** Can the tier RUN anything (build, test, git inspection)? */
export const TIER_CAN_RUN: Record<CapabilityTier, boolean> = {
  reader: false, runner: true, builder: true,
};

// ─────────────────────────────────────────────────────────────────────────────
// 3. Authority — the DEFAULT record, and only the default
// ─────────────────────────────────────────────────────────────────────────────
//
// `authority-policy.json` has a default record, a designated-verifier record, and exact
// per-(pack, role) overrides. The desktop has no IPC that can read which record applies to
// a given agent, so it applies the DEFAULT and can only REFUSE beyond it. It never grants
// an override it cannot prove: a `release` mode or a `critical` risk is refused here with
// a reason that names the missing proof, not silently allowed.

export const DEFAULT_AUTHORITY = {
  can_build: true,
  can_verify: false,
  can_release: false,
  allowed_modes: ['review', 'work'] as readonly Mode[],
  risk_ceiling: 'high' as Risk,
} as const;

/** `authority-policy.json.independence_minimum_by_risk`. */
export const INDEPENDENCE_MINIMUM_BY_RISK: Record<Risk, string> = {
  low: 'L1', medium: 'L1', high: 'L2', critical: 'L3',
};

/** Risk levels at which an independent verifier is not optional (L2+). */
export function verifierIsMandatory(risk: Risk): boolean {
  return riskRank(risk) >= riskRank('high');
}

// ─────────────────────────────────────────────────────────────────────────────
// 4. Path grammar — the SAME patterns the schema's $defs declare
// ─────────────────────────────────────────────────────────────────────────────
//
// Copied literally from `task-contract.schema.json` $defs.repoPath / $defs.absolutePath.
// Segment rule: no empty / '.' / '..' segment, no leading or trailing whitespace, no
// backslash, no ':', no glob metacharacter, no NUL. A scope must be provably literal.
//
// DRIFT WARNING: these are a mirror. If the schema changes, this changes with it, and
// `agentsDispatch.test.ts` pins the corpus that proves the two agree on the cases that
// matter. A mirror that has drifted is worse than none — but it can only ever refuse
// MORE than the engine, never accept more, because the engine re-validates everything.

const ID_PATTERN = /^[a-z0-9][a-z0-9._-]{1,127}$/;
const REPO_PATH_PATTERN =
  /^(?:\.|(?!~)(?!\.\.?(?:\/|$))[^\s\\/:*?[\x00](?:[^\\/:*?[\x00]*[^\s\\/:*?[\x00])?(?:\/(?!\.\.?(?:\/|$))[^\s\\/:*?[\x00](?:[^\\/:*?[\x00]*[^\s\\/:*?[\x00])?)*)$/;
const ABSOLUTE_PATH_PATTERN =
  /^(?:\/|[A-Za-z]:\/)(?!\.\.?(?:\/|$))[^\s\\/:*?[\x00](?:[^\\/:*?[\x00]*[^\s\\/:*?[\x00])?(?:\/(?!\.\.?(?:\/|$))[^\s\\/:*?[\x00](?:[^\\/:*?[\x00]*[^\s\\/:*?[\x00])?)*$/;

/** A `$defs.id` — task_id, pack_id, agent_id, every skill id. */
export function isContractId(v: string): boolean {
  return ID_PATTERN.test(v);
}
/** A `$defs.repoPath` — relative to this checkout. `inputs` entries must be this. */
export function isRepoPath(v: string): boolean {
  return REPO_PATH_PATTERN.test(v);
}
/** A `$defs.absolutePath` — POSIX `/x` or Windows `C:/x`, forward slashes only. */
export function isAbsolutePath(v: string): boolean {
  return ABSOLUTE_PATH_PATTERN.test(v);
}
/** A `$defs.workPath` — where a task may act: repo-relative OR absolute. */
export function isWorkPath(v: string): boolean {
  return isRepoPath(v) || isAbsolutePath(v);
}

/**
 * `parent` covers `child` in the containment sense the enforcement layer uses:
 * the same entry, or a path beneath it. `.` is the repository root entry and covers
 * every repo-relative path (but no absolute one).
 *
 * This is a SYNTACTIC test only. Real containment is decided at use time by
 * `bro_security.enforce_scope`, which resolves symlinks and `..` first. It is used here
 * for one narrow purpose: to catch a grant that contradicts itself.
 */
export function pathCovers(parent: string, child: string): boolean {
  if (parent === child) return true;
  if (parent === '.') return isRepoPath(child) && child !== '.';
  return child.startsWith(`${parent}/`);
}

/** Split a textarea into path/id entries: one per line, blanks dropped, order kept. */
export function splitLines(text: string): string[] {
  return text.split(/\r?\n/).map((l) => l.trim()).filter((l) => l.length > 0);
}

/**
 * The slug function `tools/generate_agent_definitions.py` uses to name a definition file.
 * Kept identical in behaviour so a name derived here resolves to a real file.
 */
export function slug(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

/** `<pack-slug>--<role-slug>` — the generated pack-role definition name. */
export function packRoleDefinitionName(packId: string, role: string): string {
  return `${slug(packId)}--${slug(role)}`;
}

// ─────────────────────────────────────────────────────────────────────────────
// 5. The assignment
// ─────────────────────────────────────────────────────────────────────────────

export interface Verification {
  required: boolean;
  verifier_agent_id: string | null;
  verifier_role: string | null;
  commands: string[];
}

export interface Rollback {
  strategy: string;
  commands: string[];
}

/**
 * The `repository` block of a complete task contract. The desktop CANNOT produce this:
 * `base_commit` and `tree_identity` are facts about a real worktree at a real instant, and
 * inventing them would make a contract that reads authoritative and binds nothing. The
 * engine seals it at dispatch and echoes it in the accepted reply, which is why it appears
 * here only as an OUTPUT type.
 */
export interface RepositoryBinding {
  full_name: string;
  branch: string;
  worktree: string;
  base_commit: string;
  tree_identity: string;
}

const SHA1_HEX = /^[0-9a-f]{40}$/;
const SHA256_HEX = /^[0-9a-f]{64}$/;

/**
 * Everything a task contract requires EXCEPT `repository`. Field names are the schema's
 * snake_case on purpose: this object is the wire body, not a view model, and a rename
 * between here and the engine is exactly the kind of drift that makes a contract decorative.
 */
export interface ContractDraft {
  schema: typeof CONTRACT_SCHEMA_VERSION;
  task_id: string;
  title: string;
  objective: string;
  mode: Mode;
  risk: Risk;
  pack_id: string;
  agent_id: string;
  assignee_role: string;
  scope: string[];
  prohibited_scope: string[];
  inputs: string[];
  core_skills: string[];
  additional_skills: string[];
  reference_skills: string[];
  done_criteria: string[];
  verification: Verification;
  rollback: Rollback;
}

/**
 * The capability half of the grant, split by what is actually enforced.
 *
 * `tier` BINDS: it is the definition Bro spawns, and `ai.rs` hands its tool list to the
 * CLI inline via `--agents`. `packRole` DOES NOT bind: it names the generated pack-role
 * definition that was consulted for the specialism and its authority record. Keeping the
 * two fields apart — rather than one vague `definition` — is the point, because a surface
 * that shows a pack role as the grant would be claiming containment that does not exist.
 */
export interface CapabilityGrant {
  /** ENFORCED. The tier Bro spawns; its tool list is the real bound. */
  tier: CapabilityTier;
  /** ENFORCED. Exactly the tools that tier's definition declares. */
  tools: readonly string[];
  /** The file that decides those tools, so the claim is checkable. */
  tierDefinitionPath: string;
  /** ADVISORY. The consulted pack-role definition (`<pack>--<role>`), or null when the
   *  pack/role are not both stated. Read for specialism + authority; never enforced. */
  packRole: string | null;
  /** ADVISORY. Where that definition lives, so a reader can check what it claims. */
  packRolePath: string | null;
}

/** One capability grant + one contract draft. This is what "a dispatch" means. */
export interface Assignment {
  grant: CapabilityGrant;
  draft: ContractDraft;
}

/** A validation refusal. `field` is the contract path it belongs to. */
export interface Problem {
  field: string;
  message: string;
}

export interface AssignmentInput {
  taskId: string;
  title: string;
  objective: string;
  mode: Mode;
  risk: Risk;
  packId: string;
  /** The agent's slug (or id) — becomes `agent_id` in contract-id form. */
  agentSlug: string;
  assigneeRole: string;
  tier: CapabilityTier;
  scope: string[];
  prohibitedScope: string[];
  inputs?: string[];
  coreSkills: string[];
  additionalSkills?: string[];
  referenceSkills?: string[];
  doneCriteria: string[];
  verifierAgentSlug: string | null;
  verifierRole: string | null;
  verificationCommands: string[];
  rollbackStrategy: string;
  rollbackCommands?: string[];
}

/**
 * Build the assignment. Pure and total: it never throws and never silently repairs an
 * input. A field the caller gave badly stays bad and `validateAssignment` reports it —
 * quietly fixing a malformed id here would hide the very thing the contract exists to pin.
 */
export function buildAssignment(input: AssignmentInput): Assignment {
  const agentId = slug(input.agentSlug);
  const verifierId = input.verifierAgentSlug ? slug(input.verifierAgentSlug) : null;
  const required = verifierIsMandatory(input.risk) || verifierId !== null;
  // The advisory reference resolves only when both halves of the name are really stated.
  // Half a name would point at no file, and a dangling reference reads as an authority.
  const packRole = input.packId.trim() && input.assigneeRole.trim()
    ? packRoleDefinitionName(input.packId, input.assigneeRole)
    : null;
  return {
    grant: {
      tier: input.tier,
      tools: TIER_TOOLS[input.tier],
      tierDefinitionPath: `${AGENT_DEFINITION_DIR}/${input.tier}.md`,
      packRole,
      packRolePath: packRole ? `${AGENT_DEFINITION_DIR}/${packRole}.md` : null,
    },
    draft: {
      schema: CONTRACT_SCHEMA_VERSION,
      task_id: slug(input.taskId),
      title: input.title,
      objective: input.objective,
      mode: input.mode,
      risk: input.risk,
      pack_id: slug(input.packId),
      agent_id: agentId,
      assignee_role: input.assigneeRole,
      scope: input.scope,
      prohibited_scope: input.prohibitedScope,
      inputs: input.inputs ?? [],
      core_skills: input.coreSkills,
      additional_skills: input.additionalSkills ?? [],
      reference_skills: input.referenceSkills ?? [],
      done_criteria: input.doneCriteria,
      verification: {
        required,
        verifier_agent_id: verifierId,
        verifier_role: input.verifierRole,
        commands: input.verificationCommands,
      },
      rollback: {
        strategy: input.rollbackStrategy,
        commands: input.rollbackCommands ?? [],
      },
    },
  };
}

function dupes(list: readonly string[]): string[] {
  const seen = new Set<string>();
  const out = new Set<string>();
  for (const v of list) {
    if (seen.has(v)) out.add(v);
    seen.add(v);
  }
  return [...out];
}

function checkIdList(list: readonly string[], field: string, problems: Problem[]): void {
  for (const id of list) {
    if (!isContractId(id)) {
      problems.push({ field, message: `'${id}' is not a valid contract id (^[a-z0-9][a-z0-9._-]{1,127}$)` });
    }
  }
  for (const d of dupes(list)) problems.push({ field, message: `'${d}' is listed twice; entries must be unique` });
}

/**
 * Pre-flight refusal. Returns every problem found — an empty array means "locally
 * well-formed", NOT "accepted". Ordered checks: shape (what the schema requires), then
 * authority (what the default record permits), then coherence (a grant that contradicts
 * itself). Each message says what is wrong AND why the rule exists, because a refusal a
 * person cannot act on just gets worked around.
 */
export function validateAssignment(a: Assignment): Problem[] {
  const p: Problem[] = [];
  const d = a.draft;

  // — shape —
  if (d.schema !== CONTRACT_SCHEMA_VERSION) {
    p.push({ field: 'schema', message: `schema must be ${CONTRACT_SCHEMA_VERSION}` });
  }
  for (const [field, value] of [['task_id', d.task_id], ['pack_id', d.pack_id], ['agent_id', d.agent_id]] as const) {
    if (!isContractId(value)) {
      p.push({ field, message: value ? `'${value}' is not a valid contract id` : 'is required' });
    }
  }
  if (!d.title.trim()) p.push({ field: 'title', message: 'is required' });
  if (!d.objective.trim()) p.push({ field: 'objective', message: 'is required — the agent is told this, not the UI label' });
  if (!d.assignee_role.trim()) p.push({ field: 'assignee_role', message: 'is required' });
  if (!MODES.includes(d.mode)) p.push({ field: 'mode', message: `must be one of ${MODES.join(', ')}` });
  if (!RISKS.includes(d.risk)) p.push({ field: 'risk', message: `must be one of ${RISKS.join(', ')}` });

  if (d.scope.length === 0) {
    p.push({ field: 'scope', message: 'at least one path is required — a task with no scope grants nothing and is not a grant' });
  }
  for (const s of d.scope) {
    if (!isWorkPath(s)) p.push({ field: 'scope', message: `'${s}' is not a valid work path (no '..', no backslash, no ':', no glob, no bare root)` });
  }
  for (const dup of dupes(d.scope)) p.push({ field: 'scope', message: `'${dup}' is listed twice; entries must be unique` });
  for (const s of d.prohibited_scope) {
    if (!isWorkPath(s)) p.push({ field: 'prohibited_scope', message: `'${s}' is not a valid work path` });
  }
  for (const dup of dupes(d.prohibited_scope)) p.push({ field: 'prohibited_scope', message: `'${dup}' is listed twice; entries must be unique` });
  for (const s of d.inputs) {
    if (!isRepoPath(s)) p.push({ field: 'inputs', message: `'${s}' must be a path relative to this checkout` });
  }

  if (d.core_skills.length === 0) {
    p.push({
      field: 'core_skills',
      message: 'at least one skill id is required. The desktop has no IPC that lists engine/skills, so it cannot fill this in — state the ids the task really needs',
    });
  }
  checkIdList(d.core_skills, 'core_skills', p);
  checkIdList(d.additional_skills, 'additional_skills', p);
  checkIdList(d.reference_skills, 'reference_skills', p);

  if (d.done_criteria.length === 0) {
    p.push({ field: 'done_criteria', message: 'at least one criterion is required — otherwise nobody can say the task finished' });
  }
  if (!d.rollback.strategy.trim()) {
    p.push({ field: 'rollback.strategy', message: 'is required — a grant with no way back is not reversible' });
  }

  // — authority (default record only; the desktop cannot read an override) —
  if (!DEFAULT_AUTHORITY.allowed_modes.includes(d.mode)) {
    p.push({
      field: 'mode',
      message: `'${d.mode}' is outside the default authority (${DEFAULT_AUTHORITY.allowed_modes.join(', ')}). Only a declared exact override in ${AUTHORITY_POLICY_SOURCE} grants it, and the desktop cannot read that record — so it refuses rather than assumes`,
    });
  }
  if (riskRank(d.risk) > riskRank(DEFAULT_AUTHORITY.risk_ceiling)) {
    p.push({
      field: 'risk',
      message: `'${d.risk}' exceeds the default risk ceiling '${DEFAULT_AUTHORITY.risk_ceiling}'. Raising it needs an authority record the desktop cannot read`,
    });
  }

  // — verification —
  const v = d.verification;
  if (verifierIsMandatory(d.risk) && !v.required) {
    p.push({
      field: 'verification.required',
      message: `risk '${d.risk}' requires independence ${INDEPENDENCE_MINIMUM_BY_RISK[d.risk]} — verification cannot be optional`,
    });
  }
  if (v.required) {
    if (!v.verifier_agent_id || !isContractId(v.verifier_agent_id)) {
      p.push({ field: 'verification.verifier_agent_id', message: 'a required verification needs a named verifier' });
    } else if (v.verifier_agent_id === d.agent_id) {
      p.push({
        field: 'verification.verifier_agent_id',
        message: 'the assignee cannot verify its own work — that is what independence means',
      });
    }
    if (!v.verifier_role || !v.verifier_role.trim()) {
      p.push({ field: 'verification.verifier_role', message: "a required verification needs the verifier's role" });
    }
    if (v.commands.length === 0) {
      p.push({
        field: 'verification.commands',
        message: 'a verifier that runs nothing can only opine — state the commands whose output is the evidence',
      });
    }
  }

  // — coherence of the grant itself —
  for (const s of d.scope) {
    const killer = d.prohibited_scope.find((x) => pathCovers(x, s));
    if (killer) {
      p.push({
        field: 'prohibited_scope',
        message: `'${killer}' covers the whole of scope entry '${s}' — this grant permits nothing`,
      });
    }
  }
  // A rollback plan handed to a tier that cannot change files means either the tier or
  // the intent is wrong. Stated rather than hidden: it is the common mistake.
  if (!TIER_CAN_WRITE[a.grant.tier] && d.rollback.commands.length > 0) {
    p.push({
      field: 'grant.tier',
      message: `tier '${a.grant.tier}' cannot change files, yet the draft declares rollback commands — either the tier or the intent is wrong`,
    });
  }

  return p;
}

/** `true` only when the draft cleared every pre-flight check. Still not acceptance. */
export function isLocallyWellFormed(a: Assignment): boolean {
  return validateAssignment(a).length === 0;
}

// ─────────────────────────────────────────────────────────────────────────────
// 6. The dispatch channel
// ─────────────────────────────────────────────────────────────────────────────

/** The Tauri command a governed dispatch would go through. Not registered in this build. */
export const DISPATCH_COMMAND = 'dispatch_task_contract';
export const DISPATCH_REQUEST_PROTOCOL = 'brops.agent-dispatch.v1';
export const DISPATCH_RESULT_PROTOCOL = 'brops.agent-dispatch-result.v1';
/** A payload that carries NO contract, so no conforming backend can mistake it for a dispatch. */
export const DISPATCH_PROBE_PROTOCOL = 'brops.agent-dispatch-probe.v1';

/**
 * What `apps/desktop/src-tauri` must add before a dispatch can be anything but
 * `unreachable`. Written here because the surface quotes it verbatim: a page that says
 * "not wired" without saying what is missing is just a shrug.
 */
export const DISPATCH_REQUIREMENT = [
  `a \`${DISPATCH_COMMAND}\` Tauri command in apps/desktop/src-tauri`,
  'which seals the repository block (full_name, branch, worktree, base_commit, tree_identity) from the real worktree',
  'hands the sealed contract to the engine supervisor for a lease',
  `and replies with protocol '${DISPATCH_RESULT_PROTOCOL}' carrying the assignment id, the contract digest and that sealed block`,
].join(', ');

/** The CLOSED set of reasons a backend may refuse a dispatch. Anything else is not a refusal. */
export const DISPATCH_REFUSALS = [
  'malformed_contract', 'unknown_agent', 'unknown_pack', 'scope_denied',
  'authority_denied', 'risk_ceiling_exceeded', 'verifier_denied', 'no_lease',
] as const;
export type DispatchRefusal = (typeof DISPATCH_REFUSALS)[number];

export interface DispatchRequest {
  protocol: typeof DISPATCH_REQUEST_PROTOCOL;
  client_request_id: string;
  /** The definition that is actually spawned — always a tier, because a tier is the only
   *  thing whose tool list bounds anything. */
  agent_definition: CapabilityTier;
  capability_tier: CapabilityTier;
  /** Advisory: the pack-role definition consulted for specialism + authority. The backend
   *  may log or check it, but it is not what contains the specialist. */
  pack_role_reference: string | null;
  contract_draft: ContractDraft;
}

export interface ProbeRequest {
  protocol: typeof DISPATCH_PROBE_PROTOCOL;
  client_request_id: string;
}

/**
 * The honest outcomes. `accepted` is the ONLY one that may be rendered as a real dispatch,
 * and it is reachable solely from a well-formed backend reply.
 */
export type DispatchOutcome =
  | { state: 'invalid'; problems: Problem[] }
  | { state: 'unreachable'; reason: string }
  | { state: 'refused'; clientRequestId: string; reason: DispatchRefusal; detail: string | null }
  | {
      state: 'accepted';
      clientRequestId: string;
      assignmentId: string;
      contractDigest: string;
      leaseId: string;
      repository: RepositoryBinding;
    };

export type DispatchTransport = (request: DispatchRequest | ProbeRequest) => Promise<unknown>;
export type IdGen = () => string;

const UUIDV4 = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;

function rec(v: unknown): Record<string, unknown> | null {
  return typeof v === 'object' && v !== null && !Array.isArray(v) ? (v as Record<string, unknown>) : null;
}
function s(o: Record<string, unknown>, k: string): string | null {
  const v = o[k];
  return typeof v === 'string' && v.length > 0 ? v : null;
}

function parseRepository(v: unknown): RepositoryBinding | null {
  const o = rec(v);
  if (!o) return null;
  const full_name = s(o, 'full_name');
  const branch = s(o, 'branch');
  const worktree = s(o, 'worktree');
  const base_commit = s(o, 'base_commit');
  const tree_identity = s(o, 'tree_identity');
  if (!full_name || !branch || !worktree || !base_commit || !tree_identity) return null;
  // The two identity fields are the whole point of the block: a repository binding whose
  // commit/tree are not real digests binds nothing, so it is not a binding.
  if (!SHA1_HEX.test(base_commit) || !SHA256_HEX.test(tree_identity)) return null;
  return { full_name, branch, worktree, base_commit, tree_identity };
}

/**
 * Parse a backend reply FAIL-CLOSED. It will never upgrade an unknown, partial or
 * odd reply into `accepted`; anything it cannot fully authenticate as an accepted or
 * refused frame becomes `unreachable` with the reason it failed on.
 */
export function parseDispatchReply(raw: unknown): DispatchOutcome {
  const o = rec(raw);
  if (!o) return { state: 'unreachable', reason: 'dispatch reply was not an object' };
  if (o.protocol !== DISPATCH_RESULT_PROTOCOL) {
    return { state: 'unreachable', reason: `dispatch reply has the wrong protocol: ${String(o.protocol)}` };
  }
  const clientRequestId = s(o, 'client_request_id');
  if (!clientRequestId) return { state: 'unreachable', reason: 'dispatch reply has no client_request_id to correlate' };

  if (o.status === 'accepted') {
    if ('reason' in o) return { state: 'unreachable', reason: 'an accepted frame must not carry a refusal reason' };
    const assignmentId = s(o, 'assignment_id');
    const contractDigest = s(o, 'contract_digest');
    const leaseId = s(o, 'lease_id');
    const repository = parseRepository(o.repository);
    if (!assignmentId) return { state: 'unreachable', reason: 'accepted frame has no assignment_id' };
    if (!contractDigest || !SHA256_HEX.test(contractDigest)) {
      return { state: 'unreachable', reason: 'accepted frame has no sha256 contract_digest — nothing pins what was accepted' };
    }
    if (!leaseId) {
      return { state: 'unreachable', reason: 'accepted frame has no lease_id — an assignment without a lease was not governed' };
    }
    if (!repository) {
      return { state: 'unreachable', reason: 'accepted frame has no sealed repository binding — the contract the engine took is not identified' };
    }
    return { state: 'accepted', clientRequestId, assignmentId, contractDigest, leaseId, repository };
  }

  if (o.status === 'refused') {
    const reason = o.reason;
    if (typeof reason !== 'string' || !(DISPATCH_REFUSALS as readonly string[]).includes(reason)) {
      return { state: 'unreachable', reason: `refusal reason is outside the closed set: ${String(reason)}` };
    }
    return { state: 'refused', clientRequestId, reason: reason as DispatchRefusal, detail: s(o, 'detail') };
  }

  return { state: 'unreachable', reason: `unknown dispatch status ${String(o.status)}` };
}

/**
 * Attempt one governed dispatch.
 *
 * Order matters: the draft is validated FIRST and a failing draft is never sent. The
 * renderer refusing to transmit a malformed contract is not a substitute for engine
 * validation — the engine validates again — it just means the renderer does not ask for
 * something it already knows is wrong.
 */
export async function attemptDispatch(
  assignment: Assignment,
  transport: DispatchTransport,
  genId: IdGen,
): Promise<DispatchOutcome> {
  const problems = validateAssignment(assignment);
  if (problems.length > 0) return { state: 'invalid', problems };

  const clientRequestId = genId();
  if (!UUIDV4.test(clientRequestId)) {
    return { state: 'unreachable', reason: 'client_request_id must be a lowercase UUIDv4' };
  }

  const request: DispatchRequest = {
    protocol: DISPATCH_REQUEST_PROTOCOL,
    client_request_id: clientRequestId,
    agent_definition: assignment.grant.tier,
    capability_tier: assignment.grant.tier,
    pack_role_reference: assignment.grant.packRole,
    contract_draft: assignment.draft,
  };

  let raw: unknown;
  try {
    raw = await transport(request);
  } catch (e) {
    return { state: 'unreachable', reason: e instanceof Error ? e.message : String(e) };
  }
  const outcome = parseDispatchReply(raw);
  if (outcome.state === 'accepted' && outcome.clientRequestId !== clientRequestId) {
    return { state: 'unreachable', reason: 'accepted frame does not correlate with this request' };
  }
  return outcome;
}

/** Whether the dispatch channel exists at all. `present` says nothing about acceptance. */
export type ChannelState =
  | { state: 'present'; detail: string }
  | { state: 'absent'; reason: string };

/**
 * Ask, live, whether a dispatch channel exists. Sends a probe frame that carries NO
 * contract, so it cannot be mistaken for a dispatch by any backend that reads its own
 * protocol field. A rejection (command not registered, no Tauri runtime, IPC error) is the
 * honest `absent`; ANY resolution means something answered on that command — which is all
 * `present` claims.
 */
export async function probeDispatchChannel(transport: DispatchTransport, genId: IdGen): Promise<ChannelState> {
  if (!hasBackend()) {
    return { state: 'absent', reason: 'no Tauri runtime — this window has no IPC to a backend at all' };
  }
  try {
    const reply = await transport({ protocol: DISPATCH_PROBE_PROTOCOL, client_request_id: genId() });
    const o = rec(reply);
    return {
      state: 'present',
      detail: o && typeof o.protocol === 'string'
        ? `the command answered with protocol ${o.protocol}`
        : 'the command answered; the reply carried no protocol',
    };
  } catch (e) {
    return { state: 'absent', reason: e instanceof Error ? e.message : String(e) };
  }
}

/** A UUIDv4 from the platform CSPRNG. Never falls back to a weak id — a value that fails
 *  the UUIDv4 check makes `attemptDispatch` refuse rather than send something
 *  uncorrelatable. */
export const uuid: IdGen = () =>
  (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function' ? crypto.randomUUID() : 'unavailable');

/** The real transport: `invoke(DISPATCH_COMMAND, …)`. Rejects in this build — no such command. */
export function tauriDispatchTransport(): DispatchTransport {
  return async (request) => {
    const { invoke } = await import('@tauri-apps/api/core');
    return invoke<unknown>(DISPATCH_COMMAND, { request });
  };
}

/**
 * Stable, readable JSON of what would go over the wire — the thing the surface shows.
 * The two capability fields are labelled by what they DO, so a reader of the preview
 * cannot come away thinking the pack role is the containment.
 */
export function previewJson(assignment: Assignment): string {
  return JSON.stringify(
    {
      enforced_capability: {
        agent_definition: assignment.grant.tier,
        tools: assignment.grant.tools,
        source: assignment.grant.tierDefinitionPath,
      },
      advisory_pack_role: assignment.grant.packRole
        ? { reference: assignment.grant.packRole, source: assignment.grant.packRolePath,
            note: 'read for specialism and authority; not enforced' }
        : null,
      contract_draft: assignment.draft,
      repository: '<sealed by the engine at dispatch — the desktop cannot observe it>',
    },
    null,
    2,
  );
}
