//! Wave 3b-2 — signed key manifest + pinned root trust anchor + anti-rollback (implements the 3b-0
//! isolated-signer DESIGN-GREEN manifest contract: an operator-provisioned signed key manifest validated
//! against a **binary-pinned root trust anchor**, per-key trust class / validity / revocation /
//! allowed-protocols, and **anti-rollback** on a durable highest accepted `manifest_epoch` + hash).
//!
//! This is what turns a verified governed turn into a PRODUCTION `trusted_verified`: only a manifest that
//! (a) is signed by the pinned root, (b) is not rolled back, and (c) resolves a **production**-class,
//! in-window, non-revoked, protocol-allowed key renders "Verified". Anything else fails closed
//! (`NoTrustedManifest`-equivalent). Pure + fully unit-tested (the root key + signing appear only in tests).

use ed25519_dalek::{Signature, VerifyingKey};
use serde::{Deserialize, Serialize};

use crate::governed_message_store::sha256_hex;

/// Per-key trust class. Only [`TrustClass::Production`] keys may render production `trusted_verified`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TrustClass {
    Production,
    Development,
}

/// One key entry in the manifest.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ManifestKey {
    pub key_id: String,
    /// lowercase-hex Ed25519 public key (64 hex chars = 32 bytes).
    pub public_key_hex: String,
    pub trust_class: TrustClass,
    pub valid_from_ms: i64,
    pub valid_to_ms: i64,
    pub key_epoch: u64,
    pub revoked: bool,
    /// Protocol audiences this key may sign for (a resolve for a protocol not listed is refused).
    pub allowed_protocols: Vec<String>,
}

/// The operator-provisioned signed key manifest.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct KeyManifest {
    /// Monotonic manifest epoch — the anti-rollback key.
    pub manifest_epoch: u64,
    /// The root key id that must have signed this manifest (selects among pinned roots).
    pub root_key_id: String,
    pub keys: Vec<ManifestKey>,
}

impl KeyManifest {
    /// Canonical bytes the root signs: sorted-key compact JSON (the JCS-ish convention shared with the
    /// receipt/store side). Deterministic — the same manifest always yields the same bytes.
    pub fn canonical_bytes(&self) -> Vec<u8> {
        // serde_json with sorted keys via a BTreeMap round-trip is overkill; the struct field order is
        // fixed, so serde_json::to_vec is deterministic for this closed shape.
        serde_json::to_vec(self).expect("KeyManifest serializes")
    }

    /// The content hash used by the anti-rollback floor (distinguishes two manifests at the same epoch).
    pub fn content_hash(&self) -> String {
        sha256_hex(&self.canonical_bytes())
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ManifestError {
    /// The root signature did not verify under the pinned root public key.
    RootSignatureInvalid,
    /// The manifest names a root key id that is not the pinned root.
    UnknownRoot,
    /// No key with the requested id.
    KeyNotFound,
    /// The key exists but is not production class (cannot render production Verified).
    NotProduction,
    /// The key is outside its validity window.
    OutOfWindow,
    /// The key is revoked.
    Revoked,
    /// The key is not allowed for the requested protocol.
    ProtocolNotAllowed,
    /// A malformed public key / signature encoding.
    Malformed,
}

/// A pinned root trust anchor: the binary-pinned root key id + its Ed25519 public key. Provisioned in the
/// TCB (root-owned), never taken from the manifest itself.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PinnedRoot {
    pub root_key_id: String,
    pub public_key_hex: String,
}

/// Where a pinned root anchor came from — the CUSTODY question that no signature check can answer.
///
/// A manifest signed by an anchor this build (or its provisioning kit, or a compiled-in demonstration
/// key) generated verifies exactly as well as one signed by an operator's offline root: the arithmetic
/// is identical, so "the signature verified" says nothing about who could have produced it. Provenance
/// is therefore asserted by whoever provisioned the anchor and carried, unforgeably, into the trust
/// verdict — see [`VerifiedManifestRoot`]. It is deliberately NOT a field of [`KeyManifest`]: a manifest
/// that could name its own anchor's custody would be certifying itself.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RootProvenance {
    /// The root private key was generated and is held OUTSIDE this build/deployment kit (offline
    /// custody ceremony). The only provenance that can support a production trust claim.
    External,
    /// The root keypair was generated by the same provisioning kit that signed the manifest — a real,
    /// complete chain run, but the signer and the verifier are the same party.
    KitGenerated,
    /// A compiled-in fixture anchor whose private half ships in the source tree, used to exercise the
    /// chain. Anyone with the binary can mint a manifest under it.
    Demonstration,
}

impl RootProvenance {
    /// Parse the provisioner's declared provenance. Fail-closed: an unknown, misspelled or absent value
    /// is `None`, never silently treated as [`RootProvenance::External`].
    pub fn parse(s: &str) -> Option<RootProvenance> {
        match s {
            "external" => Some(RootProvenance::External),
            "kit_generated" => Some(RootProvenance::KitGenerated),
            "demonstration" => Some(RootProvenance::Demonstration),
            _ => None,
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            RootProvenance::External => "external",
            RootProvenance::KitGenerated => "kit_generated",
            RootProvenance::Demonstration => "demonstration",
        }
    }

    /// True ONLY for [`RootProvenance::External`]. Everything else can exercise the chain honestly but
    /// can never render a PRODUCTION verdict.
    pub fn supports_production_claim(&self) -> bool {
        matches!(self, RootProvenance::External)
    }
}

/// A pinned root anchor together with the custody provenance the provisioner declared for it. This — not
/// a bare [`PinnedRoot`] — is what the production trust path verifies against.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RootAnchor {
    pub pinned: PinnedRoot,
    pub provenance: RootProvenance,
}

/// Evidence that ONE specific manifest's root signature verified under ONE specific anchor, carrying
/// that anchor's identity and provenance.
///
/// Every field is private and there is no public constructor: the ONLY way to obtain this value is
/// [`verify_manifest_anchored`] returning `Ok`. That is what makes it different from passing a
/// provenance string alongside a manifest — a caller cannot assemble a token that says `External`
/// without an anchor that actually said so having actually verified the signature.
///
/// LIMIT, stated plainly: this proves which anchor verified the manifest and what that anchor's
/// provisioner CLAIMED about its custody. It cannot prove the claim is true. A provisioner that writes
/// `external` over a key it generated itself is lying, and no code here can detect that — the anchor
/// file's TCB ownership/mode floor and the offline custody ceremony are what make the claim worth
/// anything.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VerifiedManifestRoot {
    root_key_id: String,
    provenance: RootProvenance,
    /// Binds the token to the exact manifest bytes it was issued for, so a token obtained for an
    /// externally-anchored manifest cannot be presented alongside a different one.
    manifest_content_hash: String,
}

impl VerifiedManifestRoot {
    pub fn root_key_id(&self) -> &str {
        &self.root_key_id
    }
    pub fn provenance(&self) -> RootProvenance {
        self.provenance
    }
    pub fn manifest_content_hash(&self) -> &str {
        &self.manifest_content_hash
    }
    /// True iff this token was issued for exactly `manifest`.
    pub fn covers(&self, manifest: &KeyManifest) -> bool {
        self.manifest_content_hash == manifest.content_hash()
    }
}

/// Verify the manifest against a pinned root anchor and, on success, return the [`VerifiedManifestRoot`]
/// naming the anchor that did the verifying. This is the entry point the production trust path requires;
/// [`verify_manifest`] answers only the arithmetic question and cannot say WHICH root was satisfied.
pub fn verify_manifest_anchored(
    manifest: &KeyManifest,
    root_sig_b64: &str,
    anchor: &RootAnchor,
) -> Result<VerifiedManifestRoot, ManifestError> {
    verify_manifest(manifest, root_sig_b64, &anchor.pinned)?;
    Ok(VerifiedManifestRoot {
        root_key_id: anchor.pinned.root_key_id.clone(),
        provenance: anchor.provenance,
        manifest_content_hash: manifest.content_hash(),
    })
}

fn verify_ed25519(public_key_hex: &str, msg: &[u8], signature_b64: &str) -> Result<(), ManifestError> {
    let key_bytes = decode_hex32(public_key_hex).ok_or(ManifestError::Malformed)?;
    let vk = VerifyingKey::from_bytes(&key_bytes).map_err(|_| ManifestError::Malformed)?;
    let sig_bytes = base64_decode(signature_b64).ok_or(ManifestError::Malformed)?;
    let sig = Signature::from_slice(&sig_bytes).map_err(|_| ManifestError::Malformed)?;
    vk.verify_strict(msg, &sig).map_err(|_| ManifestError::RootSignatureInvalid)
}

/// Verify the manifest is signed by the pinned root (binary-pinned anchor), refusing an unknown root id or
/// a bad signature. The `root_sig_b64` is a detached Ed25519 signature over `manifest.canonical_bytes()`.
///
/// This answers ONLY "did the signature verify under this key". It deliberately returns no evidence of
/// WHICH anchor was satisfied, which is why a caller rendering a production verdict must use
/// [`verify_manifest_anchored`] instead: a demonstration root verifies its own manifest just as well as
/// an operator's offline root, and a bare `Ok(())` cannot tell the two apart.
pub fn verify_manifest(
    manifest: &KeyManifest,
    root_sig_b64: &str,
    pinned: &PinnedRoot,
) -> Result<(), ManifestError> {
    if manifest.root_key_id != pinned.root_key_id {
        return Err(ManifestError::UnknownRoot);
    }
    verify_ed25519(&pinned.public_key_hex, &manifest.canonical_bytes(), root_sig_b64)
}

/// A resolved production key — the mandatory bind that renders `trusted_verified`. Only produced by
/// [`resolve_production_key`] after every check passes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ResolvedManifestKey {
    pub key_id: String,
    pub public_key_hex: String,
    pub key_epoch: u64,
}

/// Resolve a PRODUCTION key for `protocol` at `now_ms` from a (separately root-verified) manifest. Every
/// failure is fail-closed. Success ⇒ a production-class, in-window, non-revoked, protocol-allowed key that
/// may render production `trusted_verified`.
pub fn resolve_production_key(
    manifest: &KeyManifest,
    key_id: &str,
    protocol: &str,
    now_ms: i64,
) -> Result<ResolvedManifestKey, ManifestError> {
    let k = manifest.keys.iter().find(|k| k.key_id == key_id).ok_or(ManifestError::KeyNotFound)?;
    if k.trust_class != TrustClass::Production {
        return Err(ManifestError::NotProduction);
    }
    if k.revoked {
        return Err(ManifestError::Revoked);
    }
    if now_ms < k.valid_from_ms || now_ms >= k.valid_to_ms {
        return Err(ManifestError::OutOfWindow);
    }
    if !k.allowed_protocols.iter().any(|p| p == protocol) {
        return Err(ManifestError::ProtocolNotAllowed);
    }
    Ok(ResolvedManifestKey { key_id: k.key_id.clone(), public_key_hex: k.public_key_hex.clone(), key_epoch: k.key_epoch })
}

/// The durable anti-rollback floor: the highest accepted `manifest_epoch` + its content hash.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AntiRollbackFloor {
    pub highest_epoch: u64,
    pub highest_hash: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RollbackError {
    /// The new manifest's epoch is below the highest accepted (a rollback).
    EpochBelowFloor,
    /// Same epoch as the floor but a DIFFERENT content hash (a fork/tamper at the same epoch).
    SameEpochDifferentHash,
}

/// Anti-rollback CAS (3b-0 contract): accept `manifest` only if its epoch is strictly higher than the
/// floor, OR equal to the floor with the SAME content hash (idempotent re-accept). Refuse a lower epoch,
/// or an equal epoch with a differing hash. On accept, returns the advanced floor to persist.
///
/// **This function alone is not the anti-rollback control.** It is a comparison; the control is the
/// comparison PLUS a floor that (a) outlives the process and (b) is not derived from the very manifest
/// being checked. The audit found three of four call sites failing one of those: two advanced a floor
/// that was only ever held in memory, and one built the floor from `manifest.content_hash()` seconds
/// before comparing it against the same manifest — a predicate that cannot fail. Prefer
/// [`check_and_persist`], which cannot be called without somewhere durable to put the result.
#[must_use = "the advanced floor MUST be persisted, or the anti-rollback control is in-memory only"]
pub fn check_and_advance(
    floor: &AntiRollbackFloor,
    manifest: &KeyManifest,
) -> Result<AntiRollbackFloor, RollbackError> {
    let new_hash = manifest.content_hash();
    if manifest.manifest_epoch < floor.highest_epoch {
        return Err(RollbackError::EpochBelowFloor);
    }
    if manifest.manifest_epoch == floor.highest_epoch && new_hash != floor.highest_hash {
        return Err(RollbackError::SameEpochDifferentHash);
    }
    Ok(AntiRollbackFloor { highest_epoch: manifest.manifest_epoch, highest_hash: new_hash })
}

/// Why a durable anti-rollback advance refused. Every variant is a REFUSAL — there is deliberately no
/// "could not persist, carried on anyway" outcome, because that is precisely the state the audit found:
/// a floor that advanced in memory and reset to the provisioned constant on the next process start.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FloorPersistError {
    /// The manifest is a rollback or a same-epoch fork.
    Rollback(RollbackError),
    /// The advanced floor could not be written durably. The turn is refused: a floor that did not
    /// survive is not a floor.
    NotPersisted(String),
}

impl std::fmt::Display for FloorPersistError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            FloorPersistError::Rollback(e) => write!(f, "anti_rollback: {e:?}"),
            FloorPersistError::NotPersisted(why) => {
                write!(f, "anti_rollback_floor_not_persisted: {why}")
            }
        }
    }
}

/// The on-disk `{highest_epoch, highest_hash}` form both Linux drivers read and write.
pub fn floor_json_bytes(floor: &AntiRollbackFloor) -> Vec<u8> {
    serde_json::to_vec(&serde_json::json!({
        "highest_epoch": floor.highest_epoch,
        "highest_hash": floor.highest_hash,
    }))
    .expect("floor serializes")
}

/// Parse the on-disk floor form. `None` for absent/malformed — a caller MUST treat that as a refusal
/// and never as "no floor required" (audit R-06: an absent floor that reads as absent is not a floor).
pub fn parse_floor_json(bytes: &[u8]) -> Option<AntiRollbackFloor> {
    let v: serde_json::Value = serde_json::from_slice(bytes).ok()?;
    Some(AntiRollbackFloor {
        highest_epoch: v.get("highest_epoch")?.as_u64()?,
        highest_hash: v.get("highest_hash")?.as_str()?.to_string(),
    })
}

/// Anti-rollback CAS **plus the durable advance**, as one operation that cannot be half-done.
///
/// The audited defect was not that [`check_and_advance`] was wrong — it is right — but that its result
/// was dropped. Two of the four call sites advanced an in-memory floor and never wrote it back, so a
/// restart reset the floor to whatever the provisioner had written and the "highest accepted epoch"
/// never actually rose. This function writes the advanced floor through a temp file + rename, and a
/// write failure REFUSES the turn rather than proceeding on an unadvanced floor.
///
/// Custody is NOT solved here and this doc does not pretend otherwise: whoever can write `path` can
/// write a lower floor. What this establishes is that the floor the next process reads is the one this
/// process accepted, which is the precondition for any custody control to mean anything.
pub fn check_and_persist(
    floor: &AntiRollbackFloor,
    manifest: &KeyManifest,
    path: &std::path::Path,
) -> Result<AntiRollbackFloor, FloorPersistError> {
    let advanced = check_and_advance(floor, manifest).map_err(FloorPersistError::Rollback)?;
    write_floor_atomically(path, &floor_json_bytes(&advanced))?;
    Ok(advanced)
}

/// Temp-file + rename so a crash mid-write cannot leave a truncated floor that reads as absent.
pub fn write_floor_atomically(path: &std::path::Path, bytes: &[u8]) -> Result<(), FloorPersistError> {
    let tmp = path.with_extension("json.tmp");
    std::fs::write(&tmp, bytes)
        .map_err(|e| FloorPersistError::NotPersisted(format!("write {}: {e}", tmp.display())))?;
    std::fs::rename(&tmp, path)
        .map_err(|e| FloorPersistError::NotPersisted(format!("rename {}: {e}", path.display())))?;
    Ok(())
}

// --- tiny hex/base64 helpers (no extra deps; base64 crate is present but keep this module self-checking) -
fn decode_hex32(s: &str) -> Option<[u8; 32]> {
    if s.len() != 64 {
        return None;
    }
    let mut out = [0u8; 32];
    let b = s.as_bytes();
    for i in 0..32 {
        let hi = (b[2 * i] as char).to_digit(16)?;
        let lo = (b[2 * i + 1] as char).to_digit(16)?;
        out[i] = (hi * 16 + lo) as u8;
    }
    Some(out)
}
fn base64_decode(s: &str) -> Option<Vec<u8>> {
    use base64::Engine;
    base64::engine::general_purpose::STANDARD.decode(s.as_bytes()).ok()
}

#[cfg(test)]
mod tests {
    use super::*;
    use base64::Engine;
    use ed25519_dalek::{Signer, SigningKey};

    fn signing_key(seed: u8) -> SigningKey {
        SigningKey::from_bytes(&[seed; 32])
    }
    fn pubhex(k: &SigningKey) -> String {
        k.verifying_key().to_bytes().iter().map(|b| format!("{:02x}", b)).collect()
    }
    fn sign_b64(k: &SigningKey, msg: &[u8]) -> String {
        base64::engine::general_purpose::STANDARD.encode(k.sign(msg).to_bytes())
    }

    fn manifest(epoch: u64, prod_key: &SigningKey) -> KeyManifest {
        KeyManifest {
            manifest_epoch: epoch,
            root_key_id: "root-1".into(),
            keys: vec![ManifestKey {
                key_id: "prod-1".into(),
                public_key_hex: pubhex(prod_key),
                trust_class: TrustClass::Production,
                valid_from_ms: 1000,
                valid_to_ms: 9999,
                key_epoch: 7,
                revoked: false,
                allowed_protocols: vec!["brops.governed-receipt-envelope.v1".into()],
            }],
        }
    }

    #[test]
    fn verifies_a_root_signed_manifest_and_rejects_a_bad_one() {
        let root = signing_key(1);
        let prod = signing_key(2);
        let pinned = PinnedRoot { root_key_id: "root-1".into(), public_key_hex: pubhex(&root) };
        let m = manifest(5, &prod);
        let sig = sign_b64(&root, &m.canonical_bytes());
        assert!(verify_manifest(&m, &sig, &pinned).is_ok());
        // wrong root key
        let other = signing_key(9);
        let badsig = sign_b64(&other, &m.canonical_bytes());
        assert_eq!(verify_manifest(&m, &badsig, &pinned), Err(ManifestError::RootSignatureInvalid));
        // unknown root id
        let m2 = KeyManifest { root_key_id: "root-2".into(), ..m.clone() };
        let sig2 = sign_b64(&root, &m2.canonical_bytes());
        assert_eq!(verify_manifest(&m2, &sig2, &pinned), Err(ManifestError::UnknownRoot));
    }

    fn anchor(root: &SigningKey, provenance: RootProvenance) -> RootAnchor {
        RootAnchor {
            pinned: PinnedRoot { root_key_id: "root-1".into(), public_key_hex: pubhex(root) },
            provenance,
        }
    }

    #[test]
    fn an_anchored_verify_reports_the_anchor_that_verified_and_binds_the_manifest() {
        let root = signing_key(1);
        let prod = signing_key(2);
        let m = manifest(5, &prod);
        let sig = sign_b64(&root, &m.canonical_bytes());

        // The token names the anchor's OWN provenance — nothing in the manifest can influence it.
        let ext = verify_manifest_anchored(&m, &sig, &anchor(&root, RootProvenance::External)).unwrap();
        assert_eq!(ext.provenance(), RootProvenance::External);
        assert_eq!(ext.root_key_id(), "root-1");
        assert!(ext.covers(&m));

        // The SAME manifest and the SAME signature under a demonstration anchor yields a token that says
        // demonstration. If the token took its provenance from anywhere but the anchor, these two would
        // agree.
        let demo = verify_manifest_anchored(&m, &sig, &anchor(&root, RootProvenance::Demonstration)).unwrap();
        assert_eq!(demo.provenance(), RootProvenance::Demonstration);
        assert!(!demo.provenance().supports_production_claim());

        // The token does NOT cover a different manifest, so it cannot be carried across.
        let other = manifest(6, &prod);
        assert!(!ext.covers(&other));
    }

    #[test]
    fn no_token_is_issued_when_the_root_signature_does_not_verify() {
        // The token is the only route to a production verdict, so failing to issue it on a bad signature
        // IS the fail-closed behaviour. A wrong signer and an unknown root id both refuse.
        let root = signing_key(1);
        let prod = signing_key(2);
        let m = manifest(5, &prod);
        let a = anchor(&root, RootProvenance::External);
        let badsig = sign_b64(&signing_key(9), &m.canonical_bytes());
        assert_eq!(
            verify_manifest_anchored(&m, &badsig, &a),
            Err(ManifestError::RootSignatureInvalid)
        );
        let m2 = KeyManifest { root_key_id: "root-2".into(), ..m.clone() };
        let sig2 = sign_b64(&root, &m2.canonical_bytes());
        assert_eq!(verify_manifest_anchored(&m2, &sig2, &a), Err(ManifestError::UnknownRoot));
    }

    #[test]
    fn provenance_parsing_is_fail_closed() {
        assert_eq!(RootProvenance::parse("external"), Some(RootProvenance::External));
        assert_eq!(RootProvenance::parse("kit_generated"), Some(RootProvenance::KitGenerated));
        assert_eq!(RootProvenance::parse("demonstration"), Some(RootProvenance::Demonstration));
        // Anything else — empty, absent, misspelled, or a near-miss — is refused, never upgraded.
        for bad in ["", "External", "EXTERNAL", " external", "external ", "offline", "prod", "true"] {
            assert_eq!(RootProvenance::parse(bad), None, "{bad:?} must not parse");
        }
        assert!(RootProvenance::External.supports_production_claim());
        assert!(!RootProvenance::KitGenerated.supports_production_claim());
        assert!(!RootProvenance::Demonstration.supports_production_claim());
    }

    #[test]
    fn resolves_a_production_key_and_fails_closed_otherwise() {
        let prod = signing_key(2);
        let m = manifest(5, &prod);
        let proto = "brops.governed-receipt-envelope.v1";
        assert!(resolve_production_key(&m, "prod-1", proto, 5000).is_ok());
        assert_eq!(resolve_production_key(&m, "nope", proto, 5000), Err(ManifestError::KeyNotFound));
        assert_eq!(resolve_production_key(&m, "prod-1", proto, 500), Err(ManifestError::OutOfWindow));
        assert_eq!(resolve_production_key(&m, "prod-1", "other.proto", 5000), Err(ManifestError::ProtocolNotAllowed));
        // revoked
        let mut mr = m.clone(); mr.keys[0].revoked = true;
        assert_eq!(resolve_production_key(&mr, "prod-1", proto, 5000), Err(ManifestError::Revoked));
        // development class
        let mut md = m.clone(); md.keys[0].trust_class = TrustClass::Development;
        assert_eq!(resolve_production_key(&md, "prod-1", proto, 5000), Err(ManifestError::NotProduction));
    }

    #[test]
    fn anti_rollback_accepts_higher_refuses_lower_and_same_epoch_fork() {
        let prod = signing_key(2);
        let floor = AntiRollbackFloor { highest_epoch: 5, highest_hash: manifest(5, &prod).content_hash() };
        // strictly higher epoch => accept + advance
        let m6 = manifest(6, &prod);
        assert_eq!(check_and_advance(&floor, &m6).unwrap().highest_epoch, 6);
        // lower epoch => rollback
        let m4 = manifest(4, &prod);
        assert_eq!(check_and_advance(&floor, &m4), Err(RollbackError::EpochBelowFloor));
        // same epoch, same hash => idempotent accept
        let m5 = manifest(5, &prod);
        assert!(check_and_advance(&floor, &m5).is_ok());
        // same epoch, DIFFERENT hash => fork refused
        let mut m5b = manifest(5, &prod); m5b.keys[0].key_epoch = 8; // changes content hash
        assert_eq!(check_and_advance(&floor, &m5b), Err(RollbackError::SameEpochDifferentHash));
    }

    // ---- the durable half: an advance nobody wrote down is not an advance ----

    #[test]
    fn a_persisted_advance_is_what_the_next_process_reads() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("floor.json");
        let prod = signing_key(2);
        let m5 = manifest(5, &prod);
        std::fs::write(&path, floor_json_bytes(&AntiRollbackFloor { highest_epoch: 5, highest_hash: m5.content_hash() })).unwrap();

        // --- process 1: accept epoch 6 ---
        let floor = parse_floor_json(&std::fs::read(&path).unwrap()).expect("provisioned floor parses");
        let m6 = manifest(6, &prod);
        let advanced = check_and_persist(&floor, &m6, &path).expect("a higher epoch is accepted");
        assert_eq!(advanced.highest_epoch, 6);

        // --- process 2: the SAME rolled-back manifest that process 1 superseded ---
        // This is the whole point. With the advance held only in memory, process 2 re-read epoch 5 from
        // disk and accepted epoch 5 (and every lower-but-genuinely-signed manifest above it) forever.
        let reread = parse_floor_json(&std::fs::read(&path).unwrap()).expect("floor survived");
        assert_eq!(reread.highest_epoch, 6, "the advance must have been written down");
        assert_eq!(
            check_and_persist(&reread, &m5, &path),
            Err(FloorPersistError::Rollback(RollbackError::EpochBelowFloor)),
            "a manifest below the floor a PREVIOUS process accepted must be refused"
        );
    }

    #[test]
    fn a_floor_that_cannot_be_written_refuses_the_turn() {
        let dir = tempfile::tempdir().unwrap();
        // A directory where the floor file should be: `rename` onto it fails on every platform, and
        // so does creating `floor.json.tmp` inside a path component that is itself a file.
        let path = dir.path().join("nonexistent-subdir").join("floor.json");
        let prod = signing_key(2);
        let m5 = manifest(5, &prod);
        let floor = AntiRollbackFloor { highest_epoch: 1, highest_hash: "x".into() };
        match check_and_persist(&floor, &m5, &path) {
            Err(FloorPersistError::NotPersisted(_)) => {}
            other => panic!("an unwritable floor must refuse, got {other:?}"),
        }
    }

    #[test]
    fn an_absent_or_malformed_floor_does_not_parse_as_absent() {
        assert!(parse_floor_json(b"").is_none());
        assert!(parse_floor_json(b"{}").is_none());
        assert!(parse_floor_json(br#"{"highest_epoch":5}"#).is_none());
        assert!(parse_floor_json(br#"{"highest_hash":"a"}"#).is_none());
        assert!(parse_floor_json(br#"{"highest_epoch":"5","highest_hash":"a"}"#).is_none());
        // ...and a well-formed one round-trips.
        let f = AntiRollbackFloor { highest_epoch: 7, highest_hash: "abc".into() };
        assert_eq!(parse_floor_json(&floor_json_bytes(&f)), Some(f));
    }
}
