"""Operator and issuer control tool.

This is the half of the system that was missing. The repository could verify
signed task contracts, completion manifests, verifier receipts and mode grants,
and nothing anywhere could produce one, so every gate failed closed on an
artifact that could not exist.

It lives in tools/ and not runtime/ deliberately. runtime/bro_signature.py only
verifies and only loads public keys; an enforcement point that can sign is an
enforcement point that can forge. In production this tool runs as the issuer,
outside any agent process, holding private keys the agent never sees.

Development keys are written unencrypted and are labelled non-production in the
registry they produce. They are for tests and local bootstrap. A production
operator root key belongs offline.

    python tools/broctl.py keygen --authority operator-root --out KEYDIR
    python tools/broctl.py build-registry --keydir KEYDIR --out config/trusted-keys.json
    python tools/broctl.py sign --key KEYDIR/issuer.json --artifact task-contract --in t.json --out t.signed.json
    python tools/broctl.py sign --key KEYDIR/operator-root.json --artifact workspace-binding --in b.json --out b.signed.json
    python tools/broctl.py inspect --registry config/trusted-keys.json
"""

from __future__ import annotations

import argparse
import json
import os
import pathlib
import stat
import sys
import time

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "runtime"))

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

from bro_signature import (
    ACTIVE,
    ARTIFACT_AUTHORITY,
    AUTHORITY_TYPES,
    EVIDENCE,
    OPERATOR,
    SignatureError,
    canonical_bytes,
    load_trusted_keys,
)

DEFAULT_VALIDITY_SECONDS = 365 * 24 * 60 * 60

# Artifact types deliberately UNKNOWN to bro_signature.ARTIFACT_AUTHORITY. Their
# verifiers (bro_audit_log.verify_signed_payload; bro_backup's manifest check is
# built on it) bind the signature to an authority TYPE rather than a per-key
# allowed_artifact_types entry, so a signed audit head or backup manifest can
# never be replayed as a registry artifact and vice versa. The signing side must
# mirror those exact bindings: bro_audit_log.ANCHOR_AUTHORITIES for the head,
# bro_backup.MANIFEST_AUTHORITIES for the manifest.
OUT_OF_REGISTRY_ARTIFACTS = {
    "audit-head": (EVIDENCE, OPERATOR),
    "backup-manifest": (OPERATOR,),
}


def _artifacts_for(authority: str) -> list[str]:
    return sorted(a for a, required in ARTIFACT_AUTHORITY.items() if required == authority)


def generate_key(authority: str, key_id: str, production: bool,
                 subject_agent_id: str | None = None) -> dict:
    if authority not in AUTHORITY_TYPES:
        raise SignatureError(f"unknown authority type: {authority}")
    if production:
        raise SignatureError(
            "broctl does not generate production keys: a production root belongs "
            "offline, on hardware this tool cannot reach")
    private = Ed25519PrivateKey.generate()
    key = {
        "key_id": key_id,
        "authority_type": authority,
        "private_key": private.private_bytes_raw().hex(),
        "public_key": private.public_key().public_bytes_raw().hex(),
        "production": False,
        "warning": "DEVELOPMENT KEY - NOT FOR PRODUCTION - stored unencrypted",
    }
    if subject_agent_id is not None:
        key["subject_agent_id"] = subject_agent_id
    return key


def sign_payload(private_key_hex: str, payload: dict) -> dict:
    private = Ed25519PrivateKey.from_private_bytes(bytes.fromhex(private_key_hex))
    return {"payload": payload,
            "signature": private.sign(canonical_bytes(payload)).hex()}


def build_registry(keys: list[dict], now: int, validity: int) -> dict:
    operators = [k for k in keys if k["authority_type"] == OPERATOR]
    if len(operators) != 1:
        raise SignatureError(
            f"exactly one operator-root key must sign the registry, found {len(operators)}")
    operator = operators[0]
    payload = {
        "schema": 1,
        "artifact_type": "trusted-key-registry",
        "operator_public_key": operator["public_key"],
        "issued_at_epoch": now,
        "production": False,
        "warning": "DEVELOPMENT REGISTRY - keys generated by broctl are not production keys",
        "keys": [
            {
                "key_id": key["key_id"],
                "public_key": key["public_key"],
                "authority_type": key["authority_type"],
                "allowed_artifact_types": _artifacts_for(key["authority_type"]),
                "not_before_epoch": now,
                "not_after_epoch": now + validity,
                "status": ACTIVE,
                "issued_by": operator["key_id"],
                **({"subject_agent_id": key["subject_agent_id"]}
                   if key.get("subject_agent_id") else {}),
            }
            for key in sorted(keys, key=lambda k: k["key_id"])
        ],
    }
    return sign_payload(operator["private_key"], payload)


def _load(path: str) -> dict:
    return json.loads(pathlib.Path(path).read_text(encoding="utf-8"))


def _write(path: str, value: dict) -> pathlib.Path:
    out = pathlib.Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return out


def _require_private_key_dir(directory: pathlib.Path) -> pathlib.Path:
    """The directory that will hold a cleartext private key, or a refusal.

    Two refusals, both fail-closed. Inside the repository: a keydir in the tree
    commits cleanly (no ignore pattern matches issuer.json) and every specialist
    granted repo read gets the signing root. Group/other-accessible: on a shared
    host another local account reads the issuer key and mints valid leases. A
    directory this tool creates is born 0700; a pre-existing one must already be
    owner-only, it is not silently re-permissioned out from under its owner.
    """
    resolved = pathlib.Path(directory).expanduser().resolve()
    try:
        resolved.relative_to(REPO_ROOT.resolve())
    except ValueError:
        pass
    else:
        raise SignatureError(
            f"refusing to write key material inside the repository: {resolved}")
    if not resolved.exists():
        resolved.mkdir(parents=True, exist_ok=True)
        if os.name == "posix":
            os.chmod(resolved, 0o700)
    if not resolved.is_dir():
        raise SignatureError(f"key directory is not a directory: {resolved}")
    if os.name == "posix":
        mode = resolved.stat().st_mode
        if mode & (stat.S_IRWXG | stat.S_IRWXO):
            raise SignatureError(
                f"refusing group/other-accessible key directory: {resolved}")
    return resolved


def _write_key(path: pathlib.Path, value: dict) -> pathlib.Path:
    """Key material only: exclusive create, owner-only permissions.

    _write inherits the umask — often other-readable — which is fine for signed
    public artifacts and wrong for the private half of the trust chain. O_EXCL
    also refuses to clobber an existing key file: silently replacing a signing
    key is a rotation, and rotations should never happen by accident.
    """
    try:
        fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    except FileExistsError as exc:
        raise SignatureError(
            f"refusing to overwrite existing key file: {path}") from exc
    with os.fdopen(fd, "w", encoding="utf-8") as handle:
        handle.write(json.dumps(value, indent=2, sort_keys=True) + "\n")
    return path


def cmd_keygen(args) -> int:
    key = generate_key(args.authority, args.key_id or f"dev-{args.authority}",
                       args.production)
    keydir = _require_private_key_dir(pathlib.Path(args.out))
    out = _write_key(keydir / f"{key['authority_type']}.json", key)
    print(f"GREEN: development {key['authority_type']} key {key['key_id']}")
    print(f"  path:       {out}")
    print(f"  public key: {key['public_key']}")
    print("  NOT FOR PRODUCTION: stored unencrypted")
    return 0


def cmd_build_registry(args) -> int:
    keydir = pathlib.Path(args.keydir)
    keys = [_load(str(p)) for p in sorted(keydir.glob("*.json"))]
    if not keys:
        raise SignatureError(f"no keys in {keydir}")
    registry = build_registry(keys, int(time.time()), args.validity_seconds)
    out = _write(args.out, registry)
    print(f"GREEN: signed trusted key registry with {len(keys)} keys")
    print(f"  path: {out}")
    for key in registry["payload"]["keys"]:
        print(f"  {key['authority_type']:<18} {key['key_id']:<22} "
              f"{','.join(key['allowed_artifact_types'])}")
    return 0


def cmd_sign(args) -> int:
    key = _load(args.key)
    allowed = OUT_OF_REGISTRY_ARTIFACTS.get(args.artifact)
    if allowed is None:
        required = ARTIFACT_AUTHORITY.get(args.artifact)
        if required is None:
            raise SignatureError(f"unknown artifact type: {args.artifact}")
        allowed = (required,)
    if key["authority_type"] not in allowed:
        raise SignatureError(
            f"a {key['authority_type']} key may not sign {args.artifact}: that "
            f"requires {' or '.join(allowed)} authority")
    payload = dict(_load(args.input))
    payload["artifact_type"] = args.artifact
    payload["key_id"] = key["key_id"]
    payload.setdefault("issued_at_epoch", int(time.time()))
    out = _write(args.out, sign_payload(key["private_key"], payload))
    print(f"GREEN: signed {args.artifact} with {key['key_id']}")
    print(f"  path: {out}")
    return 0


def cmd_inspect(args) -> int:
    # load_trusted_keys reads <root>/config/trusted-keys.json. Deriving root as the
    # grandparent of --registry silently verifies THAT canonical path even when the
    # operator named a different file, so an operator could believe they inspected
    # registry X while the tool checked Y. Require --registry to BE the canonical path.
    registry_path = pathlib.Path(args.registry).resolve()
    root = registry_path.parent.parent
    if (root / "config" / "trusted-keys.json").resolve() != registry_path:
        print("RED: --registry must be a <root>/config/trusted-keys.json path: "
              f"{registry_path}", file=sys.stderr)
        return 1
    keys = load_trusted_keys(root)
    print(f"GREEN: registry verified against its operator root; {len(keys)} keys")
    for key in sorted(keys.values(), key=lambda k: k.key_id):
        print(f"  {key.status:<8} {key.authority_type:<18} {key.key_id:<22} "
              f"expires={key.not_after_epoch}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)

    keygen = sub.add_parser("keygen", help="generate a development key")
    keygen.add_argument("--authority", required=True, choices=sorted(AUTHORITY_TYPES))
    keygen.add_argument("--key-id")
    keygen.add_argument("--out", required=True, help="key directory, outside the repository")
    keygen.add_argument("--production", action="store_true",
                        help="refused: production roots belong offline")
    keygen.set_defaults(func=cmd_keygen)

    registry = sub.add_parser("build-registry", help="sign a trusted key registry")
    registry.add_argument("--keydir", required=True)
    registry.add_argument("--out", required=True)
    registry.add_argument("--validity-seconds", type=int, default=DEFAULT_VALIDITY_SECONDS)
    registry.set_defaults(func=cmd_build_registry)

    sign = sub.add_parser("sign", help="sign an artifact")
    sign.add_argument("--key", required=True)
    sign.add_argument("--artifact", required=True,
                      choices=sorted(set(ARTIFACT_AUTHORITY) | set(OUT_OF_REGISTRY_ARTIFACTS)))
    sign.add_argument("--in", dest="input", required=True)
    sign.add_argument("--out", required=True)
    sign.set_defaults(func=cmd_sign)

    inspect = sub.add_parser("inspect", help="verify and list a trusted key registry")
    inspect.add_argument("--registry", required=True)
    inspect.set_defaults(func=cmd_inspect)

    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except (SignatureError, OSError, ValueError) as exc:
        print(f"RED: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
