#!/usr/bin/env python3
"""Generate `config/negative-matrix.json` from `docs/design/SECURITY_NEGATIVE_TEST_MATRIX.md`.

**Why this generator exists.** The matrix declares 242 stable test IDs across 20 domains and
says of each one exactly what fault is injected and what refusal must come back. Until this
file landed, **exactly one** of those 242 IDs appeared anywhere in `.rs`/`.py`/`.ts` source
(`NM-XBIND-10`, in a docstring in `engine/runtime/isolated_signer.py` that says the signer
raises neither reason it names). 241 obligations were declared and nothing established any of
them -- the same defect shape `check_spec_references.py` was built for, one level up: there, a
section reference was a claim nothing checked; here, a whole test plan was.

**The markdown stays the normative source.** This tool never writes to it. It PARSES it, so
the mirror cannot be a hand-kept second list that drifts -- the failure mode the repository has
hit in every audit round. `--check` re-derives and refuses on any difference.

**What is derived and what is not.** The ID, the `under_test` cell and the `section` cell are
DERIVED from the row and are overwritten on every regeneration. `status`, `test`, `blocked_on`
and `reason` are JUDGEMENTS a person made about the tree; regeneration preserves them. A new
markdown row appears as `unreviewed`, which `tools/check_negative_matrix.py` then REFUSES
unless the ID is also added to `unreviewed_baseline` -- so new debt is a visible, reviewable
diff and can never arrive silently.

**Table shapes differ by section and the parser reads the header rather than assuming.**
Section 6 has four columns (`Cut point` / `Expected durable state`), section 10 leads with
`Case`, section 12 with `Actor -> target`, and section 19 has three columns and NO section-ref
column at all. Where a row carries no section-ref cell the `section` field records the PLAN's
own section (`plan 19`) rather than inventing an addendum reference the row does not make.
Section 20 is a coverage cross-reference whose first cell is a prose label and whose ID
mentions are ranges (`NM-REPLAY-01..10`); only rows whose FIRST cell is exactly one ID are
taken, which excludes it by construction.

**One row in the normative source is malformed, and this parser found it rather than papering
over it.** `NM-CRASH-16` carries FIVE cells in section 6's FOUR-column table, so a markdown
renderer drops its last cell and the row's `§5(9)-(10)` reference is invisible in the rendered
document. The matrix is normative and is not edited to fix it. Instead: the section-ref column
is the LAST column of every table in this plan that has one (checked for all 19), so the
section ref is read from the row's last cell, which is correct for both the well-formed rows
and for `NM-CRASH-16`. A row with FEWER cells than its header is still a hard ParseError --
that one would lose data.

stdlib only. Run: `python tools/generate_negative_matrix.py [--check]`
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]
MATRIX = ROOT / "docs" / "design" / "SECURITY_NEGATIVE_TEST_MATRIX.md"
OUT = ROOT / "config" / "negative-matrix.json"

#: A row is a case iff its first cell is EXACTLY one test ID. This is what keeps section 20's
#: cross-reference table (`| replay | 1 (NM-REPLAY-01..10) |`) out of the mirror: its first
#: cell is a prose label, and its ID mentions are ranges that name no row.
ID_RE = re.compile(r"^NM-[A-Z]+-[0-9]+$")
HEADING_RE = re.compile(r"^##\s+(\d+)\.\s")

#: Header cells that mark the section-ref column. Reading the header rather than counting
#: columns is what lets sections 6/10/12/19 differ without a special case per section.
SECTION_HEADERS = {"\u00a7 ref", "\u00a7ref", "section"}
ID_HEADERS = {"test id", "id"}

_COMMENT = [
    "The machine mirror of docs/design/SECURITY_NEGATIVE_TEST_MATRIX.md, which declares 242",
    "negative test IDs and, until this file, bound them to nothing: exactly ONE of the 242",
    "appeared anywhere in .rs/.py/.ts source. A declared obligation nothing establishes is the",
    "defect shape this repository gates against, so the matrix is now an artifact a check reads.",
    "",
    "GENERATED by tools/generate_negative_matrix.py from the markdown. Do not hand-edit the",
    "id set, under_test or section -- they are re-derived and a hand edit is reverted. status,",
    "test, blocked_on and reason are the judgements and ARE preserved across regeneration.",
    "",
    "status is one of:",
    "  implemented  -- a test exists, names the ID in its function name and carries the ID as a",
    "                  string in its body, and goes RED when the control it tests is removed.",
    "                  Every one was mutation-verified: the control was broken, the test was",
    "                  observed failing, and the control was restored.",
    "  blocked      -- the code under test does not exist in this tree. blocked_on names what",
    "                  must exist first. This is NOT 'we did not get to it'.",
    "  unreviewed   -- nobody has established this row against the tree. It is NOT a pass and",
    "                  never was. It is the honest default for a plan retrofitted onto a tree.",
    "",
    "unreviewed_baseline freezes the debt. tools/check_negative_matrix.py refuses any ID that is",
    "unreviewed and not listed there, so a NEW markdown row cannot arrive as silent debt: it",
    "fails the gate until someone either reviews it or adds it to the baseline in a visible diff.",
]

UNREVIEWED_REASON = (
    "Nobody has established this row against the tree. `unreviewed` is the honest state for a "
    "plan retrofitted onto existing code -- it freezes the debt where it was found and refuses "
    "anything NEW."
)


class ParseError(RuntimeError):
    """The markdown did not parse into the shape this generator requires."""


def _cells(line: str) -> list[str]:
    """The cells of a markdown table row. The matrix contains no escaped pipes (verified with
    a grep for backslash-pipe, which returns 0), so a plain split is exact; a `|` appearing
    inside a cell would silently shift columns, which is why `parse` cross-checks every row
    width against its header rather than trusting the split."""
    return [c.strip() for c in line.strip().strip("|").split("|")]


def _is_separator(line: str) -> bool:
    return bool(re.fullmatch(r"\|[\s:\-|]+\|", line.strip()))


def parse(text: str) -> dict[str, dict[str, str]]:
    """Every case row in the plan, in document order.

    Raises ParseError rather than skipping when a table row is malformed. A parser that
    silently dropped a row it could not read would under-report the obligation, which is the
    one failure mode this whole file exists to prevent.
    """
    cases: dict[str, dict[str, str]] = {}
    lines = text.splitlines()
    heading = ""
    i = 0
    while i < len(lines):
        line = lines[i]
        match = HEADING_RE.match(line)
        if match:
            heading = match.group(1)
            i += 1
            continue
        if not line.strip().startswith("|"):
            i += 1
            continue
        header = _cells(line)
        if i + 1 >= len(lines) or not _is_separator(lines[i + 1]):
            i += 1
            continue
        lowered = [h.lower() for h in header]
        id_col = next((n for n, h in enumerate(lowered) if h in ID_HEADERS), None)
        section_col = next((n for n, h in enumerate(lowered) if h in SECTION_HEADERS), None)
        i += 2
        while i < len(lines) and lines[i].strip().startswith("|"):
            row = _cells(lines[i])
            i += 1
            if id_col is None or id_col >= len(row) or not ID_RE.match(row[id_col]):
                continue
            if len(row) < len(header):
                raise ParseError(
                    "%s: row has %d cells, its header has %d -- a short row loses data"
                    % (row[id_col], len(row), len(header))
                )
            case_id = row[id_col]
            if case_id in cases:
                raise ParseError("%s: declared twice; test IDs are never reused" % case_id)
            # The cell AFTER the ID is what the row puts under test, whatever the section
            # calls it (`Under test`, `Cut point`, `Case`, `Actor -> target`, `Formula`).
            if id_col + 1 >= len(row):
                raise ParseError("%s: no column after the test ID" % case_id)
            if section_col is None:
                section = "plan %s" % heading
            elif section_col == len(header) - 1:
                # The section ref is the LAST column of every table in this plan that has
                # one. Reading it from the END rather than by index is what makes the
                # over-wide NM-CRASH-16 row resolve to its real `§5(9)-(10)` instead of to
                # the outcome cell that happens to sit at the header's index.
                section = row[-1]
            else:
                section = row[section_col]
            if not section:
                raise ParseError("%s: empty section-ref cell" % case_id)
            cases[case_id] = {"under_test": row[id_col + 1], "section": section}
    if not cases:
        raise ParseError("no case rows found -- the matrix table shape changed")
    return cases


def build(previous: dict | None = None) -> dict:
    """The mirror: derived fields from the markdown, judgements carried over."""
    parsed = parse(MATRIX.read_text(encoding="utf-8"))
    prior_cases = (previous or {}).get("cases", {})
    cases: dict[str, dict] = {}
    for case_id, derived in parsed.items():
        prior = prior_cases.get(case_id, {})
        kept = {k: v for k, v in prior.items()
                if k in ("status", "test", "blocked_on", "reason")}
        entry: dict[str, object] = {"status": kept.get("status", "unreviewed")}
        entry.update(derived)
        for field in ("test", "blocked_on", "reason"):
            if field in kept:
                entry[field] = kept[field]
        if entry["status"] == "unreviewed" and "reason" not in entry:
            entry["reason"] = UNREVIEWED_REASON
        cases[case_id] = entry
    baseline = (previous or {}).get("unreviewed_baseline")
    if baseline is None:
        baseline = sorted(i for i, c in cases.items() if c["status"] == "unreviewed")
    return {"_comment": _COMMENT, "unreviewed_baseline": baseline, "cases": cases}


def serialise(document: dict) -> str:
    return json.dumps(document, indent=2, ensure_ascii=False) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="verify config/negative-matrix.json matches the markdown; write nothing")
    args = ap.parse_args()

    previous = json.loads(OUT.read_text(encoding="utf-8")) if OUT.exists() else None
    try:
        wanted = build(previous)
    except ParseError as exc:
        print("RED: cannot parse %s -- %s" % (MATRIX.relative_to(ROOT).as_posix(), exc))
        return 1

    if args.check:
        if previous is None:
            print("RED: %s does not exist. Run: python tools/generate_negative_matrix.py"
                  % OUT.relative_to(ROOT).as_posix())
            return 1
        problems = []
        have, want = previous.get("cases", {}), wanted["cases"]
        for missing in sorted(set(want) - set(have)):
            problems.append("%s: in the matrix, missing from the mirror" % missing)
        for extra in sorted(set(have) - set(want)):
            problems.append("%s: in the mirror, not in the matrix" % extra)
        for case_id in sorted(set(have) & set(want)):
            for field in ("under_test", "section"):
                if have[case_id].get(field) != want[case_id][field]:
                    problems.append(
                        "%s.%s: mirror has %r, the matrix row says %r"
                        % (case_id, field, have[case_id].get(field), want[case_id][field])
                    )
        if previous.get("_comment") != wanted["_comment"]:
            problems.append("_comment: drifted from the generator")
        if not problems and serialise(previous) != serialise(wanted):
            problems.append("the file is not in the generator's canonical serialisation")
        if problems:
            print("RED: config/negative-matrix.json does not match the matrix --")
            for problem in problems[:25]:
                print("  - %s" % problem)
            if len(problems) > 25:
                print("  ... and %d more" % (len(problems) - 25))
            print("\nRun: python tools/generate_negative_matrix.py")
            return 1
        print("GREEN: %d matrix cases mirrored in %s; derived fields match the markdown."
              % (len(want), OUT.relative_to(ROOT).as_posix()))
        return 0

    OUT.write_text(serialise(wanted), encoding="utf-8")
    print("wrote %d cases to %s" % (len(wanted["cases"]), OUT.relative_to(ROOT).as_posix()))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
